/* The Bookshelf page (#/books and /books/): which timeline books sit on which shelf, and which family member minds each shelf.
   Every book is a timeline entry of kind "bk" (title, author, publisher and other facts live in timeline-data.js and timeline-extra.js).
   Shelf: {id, h heading, intro, reader [family id, options, Connie's line], books [timeline titles]} */
var BOOKSHELF=[
{"id":"sierra","h":"The Sierra shelf","intro":"Two people at a kitchen table in 1980 start a company that makes adventure games. Four decades later, you can read how it went.","reader":["zack",{},"Zack Zip is the neighbor kid, and he is in every adventure party. He has read the Sierra books and says he was in them. He was not."],"books":["Not All Fairy Tales Have Happy Endings","Once Upon a Point and Click","Hackers: Heroes of the Computer Revolution"]},
{"id":"doom","h":"Doom, id and the shooters","intro":"Two guys, one 386 and a lot of pizza. These books cover the people, the code and the cultural earthquake.","reader":["emma",{},"Emma 386 says Doom ran on a 386, so these books are basically about her. Nobody has been brave enough to disagree."],"books":["Masters of Doom","Doom Guy: Life in First Person","Game Engine Black Book: DOOM","Rocket Jump: Quake and the Golden Age of First-Person Shooters","Stairway to Badass: The Making and Remaking of Doom"]},
{"id":"blizzard","h":"Blizzard and Diablo","intro":"A dungeon, a town of people who really need your help and, somewhere, a secret cow level.","reader":["nibble",{},"Nibble has read the cow level chapter nine times. He says it is nothing like his wheel. He says he has not been back since."],"books":["Stay Awhile and Listen, Book I","Stay Awhile and Listen, Book II"]},
{"id":"consoles","h":"Consoles, Nintendo and Atari","intro":"Before the 90s PC took over the living room, there was a box under the TV. These are the best books about it.","reader":["sandy",{},"Sandy Blaster takes sides in every console war, loudly, on IRQ 5. She says Sega did it better. Nobody has asked her."],"books":["Console Wars","Game Over: How Nintendo Zapped an American Industry","The Ultimate History of Video Games","Replay: The History of Video Games","Racing the Beam","Atari Inc.: Business Is Fun","Super Mario: How Nintendo Conquered America"]},
{"id":"makers","h":"How games actually get made","intro":"Behind every great game there is a crunch, a miracle, and a build that would not compile. Here is the real story.","reader":["hiram",{},"Hiram says he has read all of these from the loft, where no one can see him. He says he has also written a game. We have not seen that either."],"books":["Blood, Sweat, and Pixels","Press Reset","The Making of Prince of Persia: Journals 1985-1993","ZZT (Boss Fight Books)"]},
{"id":"design","h":"Game design and virtual worlds","intro":"What makes a game fun, what makes a world feel alive, and where multiplayer came from.","reader":["rhoda",{},"My mom, Rhoda, says every game is rules you can read but cannot edit. She is read-only. She has strong opinions on these."],"books":["A Theory of Fun for Game Design","Designing Virtual Worlds","Dungeons and Dreamers","Playing at the World"]},
{"id":"history","h":"Computer history","intro":"The people, the garages and the companies that put a computer on every desk.","reader":["floyd",{},"Grandpa Floyd Dysk says he was there for all of it. He was not. He was a floppy. He was in a shirt pocket."],"books":["Hackers: Heroes of the Computer Revolution","Accidental Empires","The Soul of a New Machine","Commodore: A Company on the Edge","Insanely Great","Dealers of Lightning","Where Wizards Stay Up Late","The Cuckoo's Egg","Code: The Hidden Language of Computer Hardware and Software"]},
{"id":"fun","h":"Just for fun","intro":"Novels with the same energy as the games.","reader":["toner",{},"Toner, our puppy, thinks the cat in Dungeon Crawler Carl is personally his responsibility. He has left a pawprint on the cover."],"books":["Dungeon Crawler Carl","Ready Player One (novel)"]}
];

/* books.js: the Bookshelf page. A spine shelf (taller means more pages), then the shelves with a family reader on each.
   Books are timeline entries of kind "bk"; the affiliate links come from gear.js and affiliate.js. */
window.CMBooks=(function(){
 var app,PAL={sierra:"#0000aa",doom:"#aa0000",blizzard:"#aa5500",consoles:"#00aa00",makers:"#aa00aa",design:"#00aaaa",history:"#555599",fun:"#ff55ff"};
 function E(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
 function row(t){return TL.filter(function(r){return r[2]===t})[0]}
 function info(t){var r=row(t)||["","bk",t,"","",""],x=(typeof TLX!=="undefined"&&TLX[t])||{},sp=x.specs||{};return{t:t,r:r,x:x,sp:sp,name:String(t).replace(/ \((book|novel|Boss Fight Books)\)$/,""),au:sp.Author||"",pub:sp.Publisher||"",pg:+sp.Pages||0,y:String(r[0]).slice(0,4)}}
 function links(b){if(typeof affOn!=="function"||!affOn())return"";var f=gearFinds(gearCtx(b.t,b.pub,b.t),b.t,b.pub)[0];if(!f)return"";var a=affUrl("amazon",f[1]),e=affUrl("ebay",f[1]);
  return'<p class="bk-l">'+(a?'<a href="'+E(a)+'" target="_blank" rel="sponsored noopener noreferrer">Check Amazon</a>':"")+(a&&e?" &middot; ":"")+(e?'<a href="'+E(e)+'" target="_blank" rel="sponsored noopener noreferrer">Check eBay</a>':"")+"</p>"}
 function spines(){var seen={},h="";BOOKSHELF.forEach(function(s){s.books.forEach(function(t){if(seen[t])return;seen[t]=1;var b=info(t),c=PAL[s.id]||"#555",ht=120+Math.min(b.pg||320,800)/800*140,w=34+(hstr(t)%3)*8;
  h+='<a class="spine" href="#/books" data-b="'+E(t)+'" style="height:'+ht.toFixed(0)+'px;width:'+w+'px;background:'+c+';color:'+inkOn(c)+'" title="'+E(b.name+(b.au?", "+b.au:""))+'" aria-label="'+E(b.name+(b.au?" by "+b.au:"")+(b.y?", "+b.y:""))+'"><span>'+E(b.name)+'</span><small>'+E(b.y.slice(2))+'</small></a>'})});
  return'<div class="shelfw"><div class="shelf">'+h+'</div></div>'}
 function card(t,i){var b=info(t),tl="#/timeline/"+b.y+"/"+encodeURIComponent(t);
  return'<div class="bk" id="bk-'+hstr(t)+'"><h4><a href="'+E(tl)+'">'+E(b.name)+'</a></h4><p class="bk-m">'+E(b.au)+(b.y?" &middot; "+E(b.y):"")+(b.pub?" &middot; "+E(b.pub.replace(/ \(original\).*/,"")):"")+(b.pg?" &middot; "+b.pg+" pages":"")+'</p><p>'+E(b.r[4])+'</p>'+links(b)+'</div>'}
 function reader(rd){if(typeof CMCast==="undefined"||!rd)return"";var o={tall:1},k;for(k in rd[1])o[k]=rd[1][k];return'<aside class="cm-cameo noprint" aria-label="A cameo from Connie\u2019s family"><div class="cm-cs">'+(typeof mascot==="function"?mascot(64,"happy",undefined,false):"")+'</div><div class="cm-cg">'+CMCast.svg(rd[0],56,o)+'</div><div class="cm-ct"><p><b>Connie:</b> \u201c'+E(rd[2])+'\u201d</p></div></aside>'}
 function mount(el){app=el;
  var h='<section class="bks"><h2>The Bookshelf</h2><div class="bks-in">'+(typeof mascot==="function"?mascot(88,"wink",undefined,true):"")+'<div><p class="sp-lead">Books on computer history, game history and how it all gets made, from Sierra and Doom to consoles, virtual worlds and a very violent cat. Each spine is a book, and taller means more pages.</p><p class="tn">Every book is also a <a href="#/timeline">timeline</a> entry. '+(typeof AFF_SHORT!=="undefined"&&typeof affOn==="function"&&affOn()?E(AFF_SHORT)+" <a href=\"#/disclosure\">Disclosure</a>":"")+'</p></div></div>'+spines();
  BOOKSHELF.forEach(function(s){h+='<h3 class="bks-h" id="sh-'+s.id+'">'+E(s.h)+'</h3><p>'+E(s.intro)+'</p>'+reader(s.reader)+'<div class="bkgrid">'+s.books.map(card).join("")+'</div>'});
  h+='<p class="tn">Want the web version for sharing? It lives at <a href="/books/">/books/</a>.</p></section>';app.innerHTML=h;
  var sh=app.querySelector(".shelf");if(sh)sh.addEventListener("click",function(e){var a=e.target.closest&&e.target.closest(".spine");if(!a)return;e.preventDefault();var t=a.getAttribute("data-b"),el2=document.getElementById("bk-"+hstr(t));if(el2){el2.scrollIntoView({behavior:"smooth",block:"center"});el2.classList.add("bk-on");setTimeout(function(){el2.classList.remove("bk-on")},1600)}})}
 return{mount:mount,unmount:function(){}}})();
