/* Catalog (#/catalog). Two styles, remembered per device:
   "book" = a mail-order catalog you page through (catbook.js), "pro" = a tidy, filterable list.
   Pro style: a Filters drawer, removable filter chips, grouping with a jump strip, three densities and "show more". */
var CATST={q:"",cats:{},dec:"",min:0,sort:"",view:"cards",status:"",group:"none",dens:"cards",shown:24,panel:false,mode:null};
function catMode(){var m=CATST.mode;if(!m){try{m=localStorage.getItem("cm-catmode")}catch(e){}CATST.mode=m==="pro"?"pro":"book"}return CATST.mode}
function catalog(){
 var S=CATST,mode=catMode();
 var cats={},decs={},sts={};
 ITEMS.forEach(function(i){cats[i.cat]=(cats[i.cat]||0)+1;var d=i.year?Math.floor(i.year/10)*10:0;if(d)decs[d]=(decs[d]||0)+1;if(i.status)sts[i.status]=(sts[i.status]||0)+1});
 var scored=ITEMS.filter(function(i){return i.score!=null}),avg=scored.length?scored.reduce(function(a,i){return a+i.score},0)/scored.length:null;
 var head='<h2>Catalog</h2><div class="cstat"><div><b>'+ITEMS.length+'</b>exhibits</div><div><b>'+Object.keys(cats).length+'</b>categories</div><div><b>'+(avg==null?"--":outOf10(avg))+'</b>average out of 10</div><div><b>'+ITEMS.reduce(function(a,i){return a+(i.qty||1)},0)+'</b>pieces on the shelves</div></div>'
  +'<div class="cmode" role="group" aria-label="Catalog style"><span>Style:</span><button type="button" class="btn'+(mode==="book"?" pri":"")+'" data-m="book" aria-pressed="'+(mode==="book")+'">Mail-order catalog</button><button type="button" class="btn'+(mode==="pro"?" pri":"")+'" data-m="pro" aria-pressed="'+(mode==="pro")+'">Pro</button></div>';
 function setMode(m){CATST.mode=m;try{localStorage.setItem("cm-catmode",m)}catch(e){}catalog()}
 window.CATRE=catalog;
 if(mode==="book"&&window.CMBook){app.innerHTML='<section class="catw">'+head+'<div id="bkmount"></div></section>';wireMode();CMBook.mount(document.getElementById("bkmount"));return}
 function wireMode(){document.querySelector(".cmode").onclick=function(e){var b=e.target.closest("[data-m]");if(b&&b.dataset.m!==catMode())setMode(b.dataset.m)}}
 var VIEWS=[["cards","Cards"],["shelf","Shelf"],["years","Time machine"],["next","Next up"],["dir","DIR"]];
 app.innerHTML='<section class="catw">'+head+tagChips()
  +'<div class="tools ctb"><input id="q" type="search" placeholder="Search names, makers, years, specs (press / to jump here)" aria-label="Search" value="'+esc(S.q)+'"><select id="s" aria-label="Sort"><option value="">Catalog order</option><option value="score">Highest score</option><option value="old">Oldest first</option><option value="new">Newest first</option><option value="name">Name A to Z</option></select>'
  +'<select id="gp" aria-label="Group by"><option value="none">No grouping</option><option value="cat">Group by category</option><option value="dec">Group by decade</option><option value="az">Group by letter</option></select>'
  +'<button class="btn" id="fb" type="button" aria-expanded="false" aria-controls="fp">Filters</button><button class="btn" id="sur" type="button">Surprise me</button></div>'
  +'<div id="fp" class="cpanel" hidden><div class="cchips" id="cc" role="group" aria-label="Categories">'+Object.keys(cats).map(function(c){return'<button type="button" class="chip" data-c="'+esc(c)+'" aria-pressed="false">'+(typeof pxCat==="function"?pxCat(c,14):"")+esc(c)+' <b>'+cats[c]+'</b></button>'}).join("")+'</div>'
  +'<div class="cchips" id="cd" role="group" aria-label="Decades and status">'+Object.keys(decs).sort().map(function(d){return'<button type="button" class="chip dec" data-d="'+d+'" aria-pressed="false">'+d+'s <b>'+decs[d]+'</b></button>'}).join("")+Object.keys(sts).map(function(t){return'<button type="button" class="chip st" data-t="'+esc(t)+'" aria-pressed="false">'+esc(t)+' <b>'+sts[t]+'</b></button>'}).join("")+'</div>'
  +'<label class="cmin">Minimum score: <b id="mv">0</b>K <input id="mn" type="range" min="0" max="600" step="50" value="'+S.min+'" aria-label="Minimum score"></label></div>'
  +'<div class="crow"><span class="cviews" role="group" aria-label="View">'+VIEWS.map(function(v){return'<button type="button" class="btn" data-v="'+v[0]+'" aria-pressed="false">'+v[1]+'</button>'}).join("")+'</span><span class="cdens" role="group" aria-label="Density"><button type="button" class="btn" data-n="cards" aria-pressed="false">Big</button><button type="button" class="btn" data-n="rows" aria-pressed="false">List</button><button type="button" class="btn" data-n="table" aria-pressed="false">Table</button></span></div>'
  +'<div id="af" class="cact"></div><p id="cn" class="tn" role="status"></p><div id="jm"></div><div id="g"></div><p id="more" class="cmore"></p></section>';
 wireMode();
 var q=document.getElementById("q"),so=document.getElementById("s"),g=document.getElementById("g"),mn=document.getElementById("mn"),gp=document.getElementById("gp"),fp=document.getElementById("fp"),fb=document.getElementById("fb");so.value=S.sort;gp.value=S.group;
 function match(i){var t=(i.name+" "+i.maker+" "+i.year+" "+i.cat+" "+(i.acc||"")+" "+(i.tags||[]).join(" ")+" "+(i.text||"")+" "+Object.keys(i.specs||{}).map(function(k){return i.specs[k]}).join(" ")).toLowerCase();var okc=Object.keys(S.cats).filter(function(k){return S.cats[k]});
  return t.indexOf(S.q.toLowerCase())>=0&&(!okc.length||okc.indexOf(i.cat)>=0)&&(!S.dec||(i.year&&Math.floor(i.year/10)*10===+S.dec))&&(!S.status||i.status===S.status)&&(S.min<=0||(i.score!=null&&i.score>=S.min))}
 function shelf(l){var h='<p class="tn">Every spine is an exhibit. Taller means a higher score. Hover or tab to a spine to read its full title.</p><div class="shelfw"><div class="shelf">'+l.map(function(i,n){var sc=i.score==null?200:i.score,ht=130+sc/640*130,c=i.score!=null?tier(i.score).c:"#808080",w=40+((hstr?hstr(i.name):n)%3)*8;return'<a class="spine" href="#/item/'+esc(i.id)+'" style="height:'+ht.toFixed(0)+'px;width:'+w+'px;background:'+c+';color:'+inkOn(c)+'" aria-label="'+esc(i.name+(i.year?", "+i.year:"")+(i.score!=null?", "+tier(i.score).l:""))+'" data-n="'+esc(i.name)+'" data-m="'+esc((i.maker||"")+(i.year?" · "+i.year:"")+(i.score!=null?" · "+i.score+"K "+tier(i.score).l:""))+'"><i class="spx">'+(typeof pxCat==="function"?pxCat(i.cat,16):"")+'</i><span>'+esc(i.name)+'</span><small>'+(i.year?String(i.year).slice(2):"")+'</small></a>'}).join("")+'</div><div class="shtip" role="tooltip" hidden></div></div>';return h}
 function shelfWire(){var w=document.querySelector(".shelfw");if(!w)return;var t=w.querySelector(".shtip");function show(e){var a=e.target.closest&&e.target.closest(".spine");if(!a)return;t.innerHTML="<b></b><span></span>";t.firstChild.textContent=a.dataset.n;t.lastChild.textContent=a.dataset.m;t.hidden=false;var wr=w.getBoundingClientRect(),ar=a.getBoundingClientRect(),tw=t.offsetWidth,x=ar.left-wr.left+ar.width/2-tw/2;x=Math.max(4,Math.min(x,wr.width-tw-4));var y=Math.max(2,ar.top-wr.top-t.offsetHeight-8);t.style.left=x+"px";t.style.top=y+"px"}function hide(){t.hidden=true}w.addEventListener("mouseover",show);w.addEventListener("focusin",show);w.addEventListener("mouseout",function(e){var r=e.relatedTarget;if(!r||!r.closest||!r.closest(".spine"))hide()});w.addEventListener("focusout",hide)}
 function years(l){var by={};l.forEach(function(i){var y=i.year||0;(by[y]=by[y]||[]).push(i)});return'<div class="tm">'+Object.keys(by).sort().map(function(y){return'<div class="tmy"><a class="tmh" href="#/timeline/'+y+'">'+(+y||"Undated")+'</a>'+by[y].map(function(i){return'<a class="tmi" href="#/item/'+esc(i.id)+'"><span class="tmd"></span>'+esc(i.name)+(i.score!=null?' <small>'+i.score+'K</small>':'')+'</a>'}).join("")+'</div>'}).join("")+'</div>'}
 function nextUp(){var seen={},rows=[];ITEMS.forEach(function(it){var r=typeof tlRowOfItem==="function"?tlRowOfItem(it):null;if(!r)return;tlLinks(r[2]).forEach(function(l){if(tlOwn(l[0])||seen[l[0]])return;var row=TL.filter(function(z){return z[2]===l[0]})[0];if(!row||!/^(hw|sw|gt|gn|gc)$/.test(row[1]))return;seen[l[0]]=1;rows.push({r:row,rel:l[1],from:it})})});
  rows.sort(function(a,b){return a.r[0]<b.r[0]?-1:1});
  return'<p class="tn">Timeline entries connected to the collection that are not in it yet: sequels, rivals, upgrades and the things that ran on what is here. Click one to read about it.</p>'+(rows.length?'<div class="nu">'+rows.map(function(x){return'<a class="nui" href="#/timeline" data-tl="'+esc(x.r[2])+'"><b>'+esc(x.r[2])+'</b><span>'+esc(String(x.r[0]).slice(0,4))+(x.r[3]?" &middot; "+esc(x.r[3].replace(/ \(.*$/,"")):"")+'</span><small>'+esc(x.rel)+' of '+esc(x.from.name)+'</small></a>'}).join("")+'</div>':'<div class="empty">Nothing connected yet.</div>')}
 function itemNo(it){return typeof CMBook!=="undefined"?CMBook.itemNo(it):""}
 function row(i){return'<a class="crw" href="#/item/'+esc(i.id)+'"><span class="crw-p">'+pic(i)+'</span><span class="crw-n"><b>'+esc(i.name)+'</b><small>'+esc(i.maker||"")+(i.year?" &middot; "+i.year:"")+' &middot; '+esc(itemNo(i))+'</small></span><span class="crw-c">'+(typeof pxCat==="function"?pxCat(i.cat,14):"")+esc(i.cat)+'</span><span class="crw-s">'+(i.score!=null?'<i style="width:'+(i.score/640*100)+'%;background:'+tier(i.score).c+'"></i><em>'+i.score+'K</em>':"")+'</span>'+(i.status?'<span class="tag">'+esc(i.status)+'</span>':'')+(typeof srcBadge==="function"?srcBadge(i):"")+'</a>'}
 function tbl(l){return'<div class="mx-wrap"><table class="ctab"><thead><tr><th>No.</th><th>Name</th><th>Maker</th><th>Year</th><th>Category</th><th>Score</th><th>Status</th></tr></thead><tbody>'+l.map(function(i){return'<tr><td>'+esc(itemNo(i))+'</td><td><a href="#/item/'+esc(i.id)+'">'+esc(i.name)+'</a></td><td>'+esc(i.maker||"")+'</td><td>'+(i.year||"")+'</td><td>'+esc(i.cat)+'</td><td>'+(i.score!=null?i.score+'K':"")+'</td><td>'+esc(i.status||"")+'</td></tr>'}).join("")+'</tbody></table></div>'}
 function gkey(i){return S.group==="cat"?i.cat:S.group==="dec"?(i.year?Math.floor(i.year/10)*10+"s":"Undated"):(String(i.name||"?").charAt(0).toUpperCase().replace(/[^A-Z]/,"#"))}
 function draw(l){return S.dens==="rows"?'<div class="crows">'+l.map(row).join("")+'</div>':S.dens==="table"?tbl(l):'<div class="grid">'+l.map(card).join("")+'</div>'}
 function slug2(k){return"grp-"+String(k).replace(/[^a-z0-9]+/gi,"-")}
 function run(){var r=ITEMS.filter(match);
  if(S.sort==="score")r.sort(function(a,b){return(b.score||0)-(a.score||0)});else if(S.sort==="old")r.sort(function(a,b){return a.year-b.year});else if(S.sort==="new")r.sort(function(a,b){return b.year-a.year});else if(S.sort==="name"||(S.group==="az"&&!S.sort))r.sort(function(a,b){return a.name.localeCompare(b.name)});
  document.getElementById("mv").textContent=S.min;
  document.querySelectorAll("[data-c]").forEach(function(b){var on=!!S.cats[b.dataset.c];b.classList.toggle("on",on);b.setAttribute("aria-pressed",on)});
  document.querySelectorAll("[data-d]").forEach(function(b){var on=S.dec===b.dataset.d;b.classList.toggle("on",on);b.setAttribute("aria-pressed",on)});
  document.querySelectorAll("[data-t]").forEach(function(b){var on=S.status===b.dataset.t;b.classList.toggle("on",on);b.setAttribute("aria-pressed",on)});
  document.querySelectorAll("[data-v]").forEach(function(b){var on=S.view===b.dataset.v;b.classList.toggle("pri",on);b.setAttribute("aria-pressed",on)});
  document.querySelectorAll("[data-n]").forEach(function(b){var on=S.dens===b.dataset.n;b.classList.toggle("pri",on);b.setAttribute("aria-pressed",on)});
  fp.hidden=!S.panel;fb.setAttribute("aria-expanded",S.panel);fb.classList.toggle("pri",S.panel);
  var act=[];if(S.q)act.push(["q",'Search: "'+S.q+'"']);Object.keys(S.cats).forEach(function(k){if(S.cats[k])act.push(["c:"+k,k])});if(S.dec)act.push(["d",S.dec+"s"]);if(S.status)act.push(["t",S.status]);if(S.min>0)act.push(["m","Score "+S.min+"K+"]);
  document.getElementById("af").innerHTML=act.map(function(a){return'<button type="button" class="chip on" data-x="'+esc(a[0])+'" aria-label="Remove filter '+esc(a[1])+'">'+esc(a[1])+' &times;</button>'}).join("")+(act.length>1?'<button class="btn" id="clr" type="button">Clear all</button>':"");
  document.getElementById("cn").textContent="Showing "+Math.min(r.length,S.view==="cards"?S.shown:r.length)+" of "+r.length+(r.length!==ITEMS.length?" matching ("+ITEMS.length+" in the museum)":" exhibits");
  var cl=document.getElementById("clr");if(cl)cl.onclick=function(){S.q="";S.cats={};S.dec="";S.status="";S.min=0;q.value="";mn.value=0;S.shown=24;run()};
  var jm=document.getElementById("jm"),mo=document.getElementById("more");jm.innerHTML="";mo.innerHTML="";
  g.className="";
  if(!r.length){g.innerHTML='<div class="empty">No items match. Clear a filter or two.</div>';return}
  if(S.view==="cards"){var vis=r.slice(0,S.shown),h="";
   if(S.group==="none")h=draw(vis);else{var keys=[],by={};vis.forEach(function(i){var k=gkey(i);if(!by[k]){by[k]=[];keys.push(k)}by[k].push(i)});if(S.group!=="cat")keys.sort();
    jm.innerHTML='<div class="cjump" role="navigation" aria-label="Jump to a group">'+keys.map(function(k){return'<button type="button" class="chip" data-j="'+slug2(k)+'">'+esc(k)+' <b>'+by[k].length+'</b></button>'}).join("")+'</div>';
    h=keys.map(function(k){return'<h3 class="cgh" id="'+slug2(k)+'">'+(S.group==="cat"&&typeof pxCat==="function"?pxCat(k,16):"")+esc(k)+' <small>'+by[k].length+'</small></h3>'+draw(by[k])}).join("")}
   g.innerHTML=h;
   if(r.length>S.shown)mo.innerHTML='<button class="btn pri" id="sm" type="button">Show '+Math.min(24,r.length-S.shown)+' more</button> <button class="btn" id="sa" type="button">Show all '+r.length+'</button>'}
  else g.innerHTML=S.view==="dir"?dir(r):S.view==="shelf"?shelf(r):S.view==="years"?years(r):nextUp();
  if(S.view==="shelf")shelfWire()}
 q.oninput=function(){S.q=q.value;S.shown=24;run()};so.onchange=function(){S.sort=so.value;run()};gp.onchange=function(){S.group=gp.value;run()};mn.oninput=function(){S.min=+mn.value;S.shown=24;run()};
 fb.onclick=function(){S.panel=!S.panel;run()};
 document.getElementById("cc").onclick=function(e){var b=e.target.closest("[data-c]");if(b){S.cats[b.dataset.c]=!S.cats[b.dataset.c];S.shown=24;run()}};
 document.getElementById("cd").onclick=function(e){var b=e.target.closest("[data-d]");if(b){S.dec=S.dec===b.dataset.d?"":b.dataset.d;S.shown=24;run();return}b=e.target.closest("[data-t]");if(b){S.status=S.status===b.dataset.t?"":b.dataset.t;S.shown=24;run()}};
 document.getElementById("af").onclick=function(e){var b=e.target.closest("[data-x]");if(!b)return;var k=b.dataset.x;if(k==="q"){S.q="";q.value=""}else if(k==="d")S.dec="";else if(k==="t")S.status="";else if(k==="m"){S.min=0;mn.value=0}else if(k.indexOf("c:")===0)S.cats[k.slice(2)]=false;S.shown=24;run()};
 document.querySelector(".cviews").onclick=function(e){var b=e.target.closest("[data-v]");if(b){S.view=b.dataset.v;run()}};
 document.querySelector(".cdens").onclick=function(e){var b=e.target.closest("[data-n]");if(b){S.dens=b.dataset.n;S.view="cards";run()}};
 document.getElementById("jm").onclick=function(e){var b=e.target.closest("[data-j]");if(!b)return;var t=document.getElementById(b.dataset.j);if(t)t.scrollIntoView({behavior:document.documentElement.getAttribute("data-motion")==="off"?"auto":"smooth",block:"start"})};
 document.getElementById("more").onclick=function(e){if(e.target.id==="sm"){S.shown+=24;run()}else if(e.target.id==="sa"){S.shown=1e9;run()}};
 document.getElementById("sur").onclick=function(){var l=ITEMS.filter(match);if(!l.length)l=ITEMS;location.hash="#/item/"+l[Math.floor(Math.random()*l.length)].id};
 g.addEventListener("click",function(e){var n=e.target.closest("[data-tl]");if(n){e.preventDefault();var r=TL.filter(function(z){return z[2]===n.dataset.tl})[0];if(r){window.TLJUMP=r[2];location.hash="#/timeline/"+String(r[0]).slice(0,4)}}});
 run()}
document.addEventListener("keydown",function(e){if(e.key==="/"&&!/^(INPUT|TEXTAREA|SELECT)$/.test((document.activeElement||{}).tagName||"")&&location.hash.indexOf("#/catalog")===0){var q=document.getElementById("q");if(q){e.preventDefault();q.focus()}}});
