/* Real photographs from Wikimedia Commons (free-licensed files only).
   CIMG[title] = [file name on Commons, what the photo shows]. The site hotlinks the image through
   Special:FilePath and always links the credit to the Commons file page, where the author and the
   exact license are listed. If an image fails to load, the generated drawing stays in place.
   File names were taken from Commons search results; a few show a closely related model, and the
   caption says so. */
var CIMG={
"Roland MT-32":["Roland MT-32.jpg","A Roland MT-32 sound module"],
"Sound Blaster 16":["Sound Blaster 16.JPG","A Sound Blaster 16 ISA card"],
"IBM Model M":["IBM Model M 1391403 keyboard.jpg","An IBM Model M keyboard"],
"IBM Model M keyboard":["IBM Model M 1391403 keyboard.jpg","An IBM Model M keyboard"],
"Toshiba Libretto 110CT":["Libretto 70CT.jpg","A Toshiba Libretto 70CT, a close relative of the 110CT"],
"IBM Personal Computer":["IBM PC 5150.jpg","An IBM PC 5150"],
"Sony Mavica MVC-A7AF":["Pro Mavica MVC-A7AF (1987).jpg","A Pro Mavica MVC-A7AF"],
"Sony Digital Mavica MVC-FD7":["Sony Mavica MVC-FD7 digital camera (52267498373).jpg","A Sony Mavica MVC-FD7"],
"Sony Digital Mavica MVC-FD81":["Sony Digital Mavica MVC-FD81.jpg","A Sony Digital Mavica MVC-FD81"],
"Sony Digital Mavica MVC-FD88":["Sony Mavica MVC-FD88.JPG","A Sony Mavica MVC-FD88"],
"Sony Digital Mavica MVC-FD95":["Sony Mavica MVC-FD95.JPG","A Sony Mavica MVC-FD95"],
"Sony Mavica MVC-FD100":["Sony Mavica MVC-FD100 digital camera - insert a 720k floppy disk (52132518117).jpg","A Sony Mavica MVC-FD100 taking a floppy disk"],
"Apple iPod":["IPod 1G.jpg","A first-generation iPod"],
"Apple iPod classic (6th generation)":["Ipod-classic-6th-gen.jpg","A sixth-generation iPod classic"],
"Apple iPod shuffle (1st generation)":["IPod Shuffle 1st Generation.jpg","A first-generation iPod shuffle"],
"Apple iPod touch (1st generation)":["Ipod-touch-1st-gen.jpg","A first-generation iPod touch"],
"Apple QuickTake 200":["Apple QuickTake 200 Digital Camera.jpg","An Apple QuickTake 200"],
"Atari 2600 (VCS)":["Atari-2600-Wood-4Sw-Set.jpg","A woodgrain four-switch Atari 2600 with controllers"],
"Atari 2600 Jr.":["Atari-2600-Jr-Console-02.jpg","An Atari 2600 Jr."],
"Nintendo Entertainment System (US nationwide)":["NES-Console-Set.jpg","An NES with controllers"],
"Sega Genesis (North America)":["Sega-Genesis-Mod1-Set.jpg","A Sega Genesis Model 1 with controller"],
"Commodore 64":["Commodore-64-Computer-FL.jpg","A Commodore 64"],
"Magnavox Odyssey":["Magnavox-Odyssey-Console-Set.jpg","A Magnavox Odyssey with controllers"],
"Magnavox Odyssey 2":["Magnavox-Odyssey-2-Console-04.jpg","A Magnavox Odyssey 2"],
"Vectrex":["Vectrex-Console-Set.jpg","A Vectrex console with controller"],
"Apple I":["CHM Apple I.JPG","An Apple I at the Computer History Museum"],
"Home Pong":["TeleGames-Atari-Pong.jpg", "A Sears Tele-Games Atari Pong (the Atari-branded Home Pong looks similar)"],
"Magnavox Odyssey 200":["Magnavox Odyssey 200.jpg", "A Magnavox Odyssey 200"],
"Coleco Telstar":["Coleco Telstar (1976) 2.jpg", "A Coleco Telstar"],
"Magnavox Odyssey 300":["Odyssey-300.jpg", "A Magnavox Odyssey 300"],
"Fairchild Channel F":["Fairchild-Channel-F.jpg", "A Fairchild Channel F"],
"Coleco Telstar Arcade":["Coleco-Telstar-Arcade-Pongside-L.jpg", "A Coleco Telstar Arcade"],
"RCA Studio II":["RCA-Studio-II-FL.jpg", "An RCA Studio II"],
"Nintendo Color TV-Game 6":["Nintendo Color TV game 6 (Cut out).jpg", "A Nintendo Color TV-Game 6"],
"Interton VC 4000":["Interton-Electronic-VC-4000-Console-01.jpg", "An Interton VC 4000"],
"Bally Astrocade":["Bally Astrocade.jpg", "A Bally Astrocade"],
"APF-MP1000":["APF-MP1000-Console-BL.jpg", "An APF MP1000"],
"Microvision":["Milton-Bradley-Microvision-Handheld-FL.jpg", "A Milton Bradley Microvision"],
"Mattel Intellivision":["Mattel-Intellivision-Console-BR.jpg", "A Mattel Intellivision"],
"Game & Watch":["Game-and-watch-ball.png", "A Nintendo Game  Watch Ball (the first Game  Watch)"],
"VTech CreatiVision":["VTech-CreatiVision-Console-02.jpg", "A VTech CreatiVision"],
"Entex Select-A-Game":["Entex-SelectAGame.jpg", "An Entex Select-A-Game"],
"Cassette Vision":["Epoch Cassette Vision.JPG", "An Epoch Cassette Vision"],
"Arcadia 2001":["Emerson-Arcadia-2001.jpg", "An Emerson Arcadia 2001"],
"ColecoVision":["ColecoVision-Console-Front.jpg", "A ColecoVision"],
"Entex Adventure Vision":["Entex-AdventureVision.jpg", "An Entex Adventure Vision"],
"Atari 5200":["Atari-5200-Console-Set.jpg", "An Atari 5200"],
"Philips Videopac+ G7400":["Philips Videopac G7400.jpg", "A Philips Videopac+ G7400"],
"Nintendo Famicom (Japan)":["Nintendo-Famicom-Console-FL.jpg", "A Nintendo Famicom"],
"SG-1000":["Sega-SG-1000-Console-Set.jpg", "A Sega SG-1000"],
"Casio PV-1000":["Casio-PV-1000-Console-01.jpg", "A Casio PV-1000"],
"Gakken Compact Vision TV Boy":["Compact Vision TV Boy, Gakken 01.png", "A Gakken Compact Vision TV Boy"],
"Epoch Game Pocket Computer":["Epoch-Game-Pocket-Computer-FL.jpg", "An Epoch Game Pocket Computer"],
"Super Cassette Vision":["Super-Cassette-Vision-Console-L.jpg", "An Epoch Super Cassette Vision"],
"Nintendo Entertainment System (US test market)":["Nintendo Entertainment System NES (1985) 1.jpg", "A Nintendo Entertainment System (the US retail version looks similar)"],
"Sega Mark III (Japan)":["Sega Mark III.jpg", "A Sega Mark III"],
"Atari 7800":["Atari-7800-Console-Set.png", "An Atari 7800"],
"Sega Master System (North America)":["Sega-Master-System-Set.jpg", "A Sega Master System"],
"Atari XEGS":["Atari XEGS.jpg", "An Atari XEGS"],
"Micro Genius":["Micro Genius IQ-901 5614992132.jpg", "A Micro Genius IQ-901 Famicom clone console"],
"NEC PC Engine (Japan)":["PC-Engine-Console-Set.jpg", "An NEC PC Engine"],
"Sega Mega Drive (Japan)":["Sega-Mega-Drive-JP-Mk1-Console-Set.jpg", "A Sega Mega Drive (Japan, Model 1)"],
"TurboGrafx-16 (North America)":["TurboGrafx-16-Console.jpg", "A TurboGrafx-16"],
"Sega Master System II":["Master System II.jpg", "A Sega Master System II"],
"Super Famicom (Japan)":["Super-Famicom-Console-Set.jpg", "A Nintendo Super Famicom"],
"Super NES (North America)":["SNES-Mod1-Console-Set.png", "A Super Nintendo Entertainment System"],
"NEC PC Engine Duo":["PC-Engine-Duo-Console-Set.png", "An NEC PC Engine Duo"],
"Philips CD-i":["Philips-CDi-Console-Back.jpg", "A Philips CD-i (rear view)"],
"Sega Mega-CD (Japan)":["MegaCD.png", "A Sega Mega-CD"],
"Sega Genesis Model 2":["Sega-Genesis-Mk2-6button.jpg", "A Sega Genesis Model 2 with a six-button controller"],
"NES-101 (New-Style NES)":["NES-101-Console-Set.jpg", "A Nintendo NES-101 (new-style NES)"],
"NEC PC-FX":["PC-FX-Console-Set.jpg", "An NEC PC-FX"],
"Bandai Playdia":["Playdia-Console-Set.png", "A Bandai Playdia"],
"Sega Nomad":["Sega-Genesis-Nomad-Console-01.jpg", "A Sega Nomad portable Genesis"],
"Casio Loopy":["Casio-Loopy-Console-Set.jpg", "A Casio Loopy console"],
"Super A'Can":["Super-ACan-Console-set-h.jpg", "A Funtech Super A'Can console"],
"Neo Geo CDZ":["Neo-Geo-CDZ-FR.jpg", "An SNK Neo Geo CDZ console"],
"Apple Bandai Pippin":["Bandai-Apple-Pippin-Console-FL.jpg", "An Apple Bandai Pippin console"],
"Nintendo 64 (Japan)":["N64-Console-Set.jpg", "A Nintendo 64 console (the Japanese model looks similar)"],
"Nintendo 64 (North America)":["N64-Console-Set.jpg", "A Nintendo 64 console with controller"],
"Super NES (SNS-101 Redesign)":["Nintendo-Super-NES-Console-101-FL.jpg", "A Super NES SNS-101 redesigned console"],
"Sega Genesis 3":["Sega-Genesis-3-Console-FL.jpg", "A Sega Genesis 3 console"],
"Game Boy Light":["Game-Boy-Light-FL.jpg", "A Nintendo Game Boy Light handheld"],
"Game Boy Color":["Nintendo-Game-Boy-Color-FL.jpg", "A Nintendo Game Boy Color handheld"],
"Sega Dreamcast (Japan)":["Dreamcast-Console-Set.jpg", "A Sega Dreamcast console (the Japanese model looks similar)"],
"Sega Dreamcast (North America)":["Dreamcast-Console-Set.jpg", "A Sega Dreamcast console with controller"],
"Neo Geo Pocket Color":["Neo-Geo-Pocket-Color-Blue-Left.jpg", "An SNK Neo Geo Pocket Color handheld"],
"Nuon":["Nuon-N2000-Console-FR.jpg", "A Nuon N2000 DVD player console"],
"PlayStation 2 (Japan)":["PS2-Fat-Console-Set.jpg", "A Sony PlayStation 2 console (the Japanese model looks similar)"],
"PlayStation 2 (North America)":["PS2-Fat-Console-Set.jpg", "A Sony PlayStation 2 console with controller"],
"Game Boy Advance (Japan)":["Nintendo-Game-Boy-Advance-Purple-FL.jpg", "A Nintendo Game Boy Advance (Japanese model looks similar)"],
"Game Boy Advance (North America)":["Nintendo-Game-Boy-Advance-Purple-FL.jpg", "A Nintendo Game Boy Advance handheld"],
"Nintendo GameCube (Japan)":["GameCube-Console-Set.png", "A Nintendo GameCube console (the Japanese model looks similar)"],
"Nintendo GameCube (North America)":["GameCube-Console-Set.png", "A Nintendo GameCube console with controller"],
"Microsoft Xbox":["Xbox-Console-Front.jpg", "A Microsoft Xbox console"],
"SwanCrystal":["Wonder-Swan-Crystal.jpg", "A Bandai WonderSwan Crystal (SwanCrystal) handheld"],
"Game Boy Advance SP":["Game-Boy-Advance-SP-Mk1-Blue.jpg", "A Nintendo Game Boy Advance SP handheld"],
"Nokia N-Gage":["Nokia-NGage-L.jpg", "A Nokia N-Gage handheld"],
"Tapwave Zodiac":["Tapwave-Zodiac2-FL.jpg", "A Tapwave Zodiac 2 handheld (the Zodiac 1 looks similar)"],
"iQue Player":["Nintendo-N64-iQue-Player-FL.jpg", "An iQue Player console"],
"Xavix PORT":["XaviX-XaviXPORT-Console-FL.jpg", "A XaviX PORT console"],
"Nokia N-Gage QD":["Nokia-NGage-QD.jpg", "A Nokia N-Gage QD handheld"],
"V.Smile":["Vtech Vsmile French version.JPG", "A VTech V.Smile console (French version)"],
"PlayStation 2 Slim (SCPH-70000)":["Sony-PlayStation-2-70001-Console-FL.jpg", "A Sony PlayStation 2 Slim SCPH-70001 console"],
"Nintendo DS (North America)":["Nintendo-DS-Fat-Blue.jpg", "A Nintendo DS handheld"],
"Gizmondo":["Gizmondo.jpg", "A Gizmondo handheld"],
"PlayStation Portable (North America)":["Sony-PSP-1000-Body.jpg", "A Sony PlayStation Portable PSP-1000 handheld"],
"Neo Geo Mini":["Neo Geo Mini 20210313.jpg", "A Neo Geo Mini"],
"PlayStation Classic":["PlayStation Classic Konsole + Controller (transparenter Hintergrund).png", "A PlayStation Classic console with controller"],
"Nintendo Switch Lite":["Nintendo Switch Lite Grey - 01.jpg", "A grey Nintendo Switch Lite"],
"Evercade VS":["Evercade vs with 1 gamepad.png", "An Evercade VS console with a gamepad"],
"Xbox Series X and Series S":["Xbox Series XとSeries S.jpg", "An Xbox Series X and Series S"],
"PlayStation 5":["Playstation 5.jpg", "A PlayStation 5 console"],
"Analogue Pocket":["Analogue Pocket in Yellow (53367343185).jpg", "A yellow Analogue Pocket handheld"],
"Atari VCS":["Atari VCS 03.jpg", "An Atari VCS console"],
"Nintendo Switch (OLED model)":["Nintendo Switch OLED Model.jpg", "A Nintendo Switch OLED model"],
"Playdate":["Playdate front-view.png", "A Playdate handheld, front view"],
"Steam Deck":["Steam Deck (front).jpg", "A Steam Deck, front view"],
"ROG Ally":["ROG ALLY - 2.jpg", "An Asus ROG Ally handheld"],
"Atari 2600+":["Atari 2600 Plus.png", "An Atari 2600+ console"],
"PlayStation 5 Pro":["PlayStation 5 Pro no disc drive.jpg", "A PlayStation 5 Pro console"],
"Nintendo Switch 2":["Nintendo Switch 2 in Handheld Mode.jpg", "A Nintendo Switch 2 in handheld mode"],
"ROG Xbox Ally":["ROG xbox ally.png", "An ROG Xbox Ally handheld"],
"MITS Altair 8800":["MITS Altair 8800 Computer (1975).jpg", "A MITS Altair 8800 computer"],
"Commodore PET 2001":["Commodore PET2001.jpg", "A Commodore PET 2001"],
"Apple II":["Apple-II.jpg", "An Apple II computer"],
"TRS-80 Model I":["Radio Shack Tandy TRS-80 Model I System.JPG", "A Radio Shack TRS-80 Model I system"],
"Atari 400":["Atari-400-Comp.jpg", "An Atari 400 computer"],
"Macintosh SE/30":["Apple Macintosh SE-30 computer (1989) clear background.png", "A Macintosh SE/30 computer"],
"Macintosh Portable":["Macintosh Portable-IMG 7541.jpg", "A Macintosh Portable"],
"Commodore Amiga 3000":["Amiga 3000 Front with White BG.jpg", "A Commodore Amiga 3000"],
"IBM PS/1":["IBM PS1 2011, ValorosoIT collection 1.jpg", "An IBM PS/1 computer"],
"Macintosh Classic":["Mac Classic.jpg", "A Macintosh Classic"],
"Macintosh LC":["Macintosh LC III front.jpg", "A Macintosh LC III (the original LC looks similar)"],
"Commodore CDTV":["Commodore CDTV Setup.jpg", "A Commodore CDTV set-up"],
"HP 95LX":["HP 95LX Pocket Computer.JPG", "An HP 95LX pocket computer"],
"PowerBook 140":["Macintosh PowerBook 140.jpg", "A Macintosh PowerBook 140"],
"Apple PowerBook 100":["Powerbook 100 pose.jpg", "An Apple PowerBook 100"],
"Compaq Contura":["Compaq Contura 430C front.jpg", "A Compaq Contura 430C notebook"],
"Amiga 600":["Amiga 600.jpg", "A Commodore Amiga 600"],
"Amiga 1200":["Amiga 1200.jpg", "A Commodore Amiga 1200"],
"Compaq ProLiant":["Compaq Proliant 2500.JPG", "A Compaq ProLiant 2500 server"],
"Dell Dimension":["Dell Dimension 433SV 486.jpg", "A Dell Dimension 433SV desktop PC"],
"Dell OptiPlex":["Dell OptiPlex GX1.jpg", "A Dell OptiPlex GX1 (a later model in the OptiPlex line)"],
"Dell XPS":["Dell XPS 700.JPG", "A Dell XPS 700 (a much later model in the XPS line)"],
"Compaq Presario":["Compaq Presario 5000.jpg", "A Compaq Presario 5000 desktop PC"],
"Dell Latitude":["Dell Latitude CPx .jpg", "A Dell Latitude CPx laptop (a later model in the Latitude line)"],
"Power Macintosh":["Apple-power-macintosh-6500-300.jpg", "A Power Macintosh 6500 (a later model in the Power Macintosh line)"],
"IBM Aptiva":["Ibm aptiva.jpg", "An IBM Aptiva computer"],
"IBM ThinkPad 701C":["Thinkpad 701.jpg", "An IBM ThinkPad 701 (the 701C looks the same)"],
"HP Pavilion 5030":["Detail of HP Pavilion 5030.webp", "An HP Pavilion 5030 desktop PC"],
"Gateway 2000 Solo":["Gateway Solo 2200.JPG", "A Gateway Solo 2200 (a later Solo model)"],
"Gateway Destination":["Gateway 2000 Destination.jpg", "A Gateway 2000 Destination PC"],
"Kodak DCS 520":["Kodak DCS 520C.jpg", "A Kodak DCS 520 (the 520C color version)"],
"Kodak DCS 560":["Kodak DCS 560 Front.jpg", "A Kodak DCS 560 digital SLR"],
"Game Boy Camera":["Game-Boy-Camera.jpg", "A Nintendo Game Boy Camera"],
"Sony Digital Mavica MVC-FD83":["Sony Mavica MVC-FD 83 (51878635648).jpg", "A Sony Digital Mavica MVC-FD83"],
"Kodak DC260":["Kodak Dc 260 digital camera.JPG", "A Kodak DC260 digital camera"],
"Sony Digital Mavica MVC-FD90":["Sony Mavica FD-90 digital camera. Using floppy disk to store photos. (52215832870).jpg", "A Sony Mavica FD-90 floppy disk camera"],
"Sony Digital Mavica MVC-FD91":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD91 looks similar)"],
"Sony Digital Mavica MVC-FD85":["Sony Digital Mavica MVC-FD81.jpg", "A Sony Digital Mavica MVC-FD81 (the FD85 looks similar)"],
"Sony Mavica MVC-FD87":["Sony Mavica MVC-FD88.JPG", "A Sony Mavica MVC-FD88 (the FD87 looks similar)"],
"Sony Mavica MVC-FD92":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD92 looks similar)"],
"Sony Mavica MVC-FD97":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD97 looks similar)"],
"Sony CD Mavica MVC-CD300":["Mavica-cd400-front.jpg", "A Sony CD Mavica MVC-CD400 (the CD300 looks similar)"],
"Sony CD Mavica MVC-CD400":["Mavica-cd400-front.jpg", "A Sony CD Mavica MVC-CD400"],
"Nikon D1":["Nikon D1 8373.jpg", "A Nikon D1 digital SLR"],
"Nikon Coolpix 990":["Nikon Coolpix 990.jpg", "A Nikon Coolpix 990 digital camera"],
"Canon EOS D30":["EOS D30 with Pentacon lens.JPG", "A Canon EOS D30 digital SLR fitted with a Pentacon lens"],
"Sharp J-SH04":["Sharp J-SH04 CP+ 2011.jpg", "A Sharp J-SH04 camera phone"],
"Apple iPod nano (4th generation)":["IPod Nano 4G black.jpg", "A black Apple iPod nano (4th generation)"],
"Apple iPod touch (2nd generation)":["IPod Touch 2G Backlight.JPG", "An Apple iPod touch (2nd generation) with its screen lit"],
"Apple iPod classic (160 GB, 2009)":["IPod Classic 6th Generation Black.jpg", "An Apple iPod classic (6th generation, the 160 GB model looks similar)"],
"Apple iPod touch (4th generation)":["4th generation iPod touch.JPG", "An Apple iPod touch (4th generation)"],
"Apple iPod nano (7th generation)":["IPod nano 7G pink front.JPG", "A pink Apple iPod nano (7th generation)"],
"IBM Color/Graphics Adapter (CGA)":["IBM Color Graphics Adapter.jpg", "An IBM Color Graphics Adapter card"],
"IBM Monochrome Display Adapter (MDA)":["MDA IBM 1501985.jpg", "An IBM Monochrome Display Adapter card"],
"Hercules Graphics Card":["Hercules Graphics Card.jpg", "A Hercules Graphics Card"],
"IBM Enhanced Graphics Adapter (EGA)":["EGA card.jpg", "An IBM-style Enhanced Graphics Adapter (EGA) card"],
"ATI Mach64":["KL ATI Mach 64 VLB.jpg", "An ATI Mach64 VLB graphics card"],
"NVIDIA RIVA 128":["NVidia Riva 128.jpg", "An NVIDIA RIVA 128 graphics card"],
"3dfx Voodoo2":["3dfx Voodoo2.jpg", "A 3dfx Voodoo2 graphics card"],
"3dfx Voodoo Banshee":["3D Blaster Banshee.jpg", "A Creative 3D Blaster Banshee, a 3dfx Voodoo Banshee card"],
"NVIDIA RIVA TNT":["NVidia Riva TNT.jpg", "An NVIDIA RIVA TNT graphics card"],
"NVIDIA RIVA TNT2":["NVIDIA RIVA-TNT2.JPG", "An NVIDIA RIVA TNT2 graphics card"],
"3dfx Voodoo3":["3dfx Voodoo 3000.jpg", "A 3dfx Voodoo3 3000 graphics card"],
"3dfx Voodoo5 5500":["3dfx Voodoo 5500.jpg", "A 3dfx Voodoo5 5500 graphics card"],
"ATI Radeon HD 4870":["ATI HD4870.JPG", "An ATI Radeon HD 4870 graphics card"]
};
function cimgUrl(t,w){var c=CIMG[t];return c?"https://commons.wikimedia.org/wiki/Special:FilePath/"+encodeURIComponent(c[0].replace(/ /g,"_"))+"?width="+(w||480):""}
function cimgPage(t){var c=CIMG[t];return c?"https://commons.wikimedia.org/wiki/File:"+encodeURIComponent(c[0].replace(/ /g,"_")):""}
function cimg(t,w,cls){var u=cimgUrl(t,w);return u?'<img class="cm-photo'+(cls?" "+cls:"")+'" src="'+u+'" alt="'+String(CIMG[t][1]).replace(/[<>&"]/g,"")+'" loading="lazy" referrerpolicy="no-referrer" data-t="'+String(t).replace(/[<>&"]/g,"")+'">':""}
function cimgCredit(t){var c=CIMG[t];return c?'<small class="cm-credit" data-t="'+String(t).replace(/[<>&"]/g,"")+'" hidden>Photo: '+String(c[1]).replace(/[<>&"]/g,"")+'. Free-licensed image from <a href="'+cimgPage(t)+'" target="_blank" rel="noopener noreferrer">Wikimedia Commons</a>; author and license are on that page.</small>':""}
document.addEventListener("error",function(e){var t=e.target;if(t&&t.classList&&t.classList.contains("cm-photo")){var f=t.closest(".cm-fig");t.remove();if(f)f.classList.remove("cm-fig")}},true);
document.addEventListener("load",function(e){var t=e.target;if(t&&t.classList&&t.classList.contains("cm-photo")){var k=t.getAttribute("data-t");document.querySelectorAll(".cm-credit").forEach(function(c){if(c.getAttribute("data-t")===k)c.hidden=false})}},true);
