/* Real photographs from Wikimedia Commons (free-licensed files only).
   CIMG[title] = [file name on Commons, what the photo shows]. The site hotlinks the image through
   Special:FilePath and always links the credit to the Commons file page, where the author and the
   exact license are listed. If an image fails to load, the generated drawing stays in place.
   File names were taken from Commons search results; a few show a closely related model, and the
   caption says so. */
var CIMG={
"Mac mini":["Mac-mini-1st-gen.jpg","First-generation PowerPC G4 Mac mini (2005)."],
"Game Boy Micro":["Game Boy Micro.jpg","The Nintendo Game Boy Micro."],
"Apple iPod mini (2nd generation)":["IPod mini blue front 2G.jpg","Second-generation iPod mini in blue."],
"Leica M8":["Leica M8 IMG 0672.jpg","Leica M8 digital rangefinder camera."],
"Canon EOS 5D":["Canon EOS 5D.jpg","Canon EOS 5D full-frame DSLR."],
"GP2X":["GP2X 01.jpg","The GP2X handheld."],
"Microsoft Zune":["Zune80and4.jpg","Zune 80 and Zune 4 (later models of the player line)."],
"MacBook Air":["SteveJobsMacbookAir.jpg","Steve Jobs introducing the original MacBook Air at Macworld 2008."],
"Wii Balance Board":["Wii Balance Board.jpg","The Wii Balance Board."],
"Acer Aspire One":["Acer Aspire One D250.jpg","Acer Aspire One D250, a later model of the netbook line."],
"GP2X Wiz":["Gp2xwiz.jpg","The GP2X Wiz handheld."],
"Zeebo":["Zeebo-Real Console.jpg","The Zeebo console."],
"Asus Eee PC":["Asus Eee 701.jpg","The original Asus Eee PC 701 netbook."],
"Apple iPhone":["IPhone First Generation 8GB (3677961514).jpg","A first-generation 8 GB iPhone."],
"Apple iPhone 3G":["IPhone & iPhone 3G.jpg","The iPhone 3G (right) shown beside the original iPhone."],
"HTC Dream (T-Mobile G1)":["T-Mobile G1.png","The HTC Dream sold as the T-Mobile G1."],
"Nintendo DSi":["Nintendo-DSi-Bl-Open.jpg","A blue Nintendo DSi, open."],
"BlackBerry Storm":["Blackberry-storm-orig.jpg","The BlackBerry Storm."],
"Microsoft Zune 80":["Zune80and4.jpg","Zune 80 and Zune 4 players."],
"Microsoft Zune 4":["Zune80and4.jpg","Zune 80 and Zune 4 players."],
"Apple iMac (aluminum, 2007)":["IMac aluminium.png","An aluminum iMac."],
"OLPC XO-1":["XO-Beta1-mikemcgregor-2.jpg","An early beta unit of the OLPC XO-1 laptop."],
"Panasonic Lumix DMC-G1":["Lumix G1 IMG 2426.jpg","The Panasonic Lumix DMC-G1."],
"NVIDIA GeForce GTX 280":["NVIDIA GeForce GTX280 DSC00997 (23791208991).jpg","An NVIDIA GeForce GTX 280 graphics card."],
"Apple Magic Trackpad":["AppleMagicTrackpad.jpg","Apple Magic Trackpad."],
"PlayStation Move":["Sony-PlayStation-Move-Controller.jpg","Sony PlayStation Move motion controller."],
"Barnes & Noble Nook Color":["Nook Color Showing Wikipedia Index On Dolphin Browser HD.jpg","Barnes & Noble Nook Color displaying a web page."],
"Apple iPhone 3GS":["IPhone 3G and 3G S backs.jpg","Backs of the iPhone 3G and iPhone 3GS (the 3GS shares the 3G's case design)."],
"Palm Pre":["Palm Pre.jpg","Palm Pre smartphone with slide-out keyboard."],
"Canon PowerShot S100":["Canon PowerShot S100 20120121.jpg","Canon PowerShot S100 compact camera."],
"Microsoft Zune HD":["ZuneHD-Radio.jpg","Microsoft Zune HD showing its FM radio screen."],
"NVIDIA GeForce GTX 480":["Nvidia GeForce GTX480.jpg","NVIDIA GeForce GTX 480 graphics card."],
"Wii MotionPlus":["Wiimote-with-Motionplus-Attach.jpg","Wii MotionPlus attached to a Wii Remote."],
"Olympus PEN E-P1":["Bfishadow Olympus E-P1.jpg","Olympus PEN E-P1 Micro Four Thirds camera."],
"Apple iPod touch (3rd generation)":["IPod touch 3rd Gen.jpg","Apple iPod touch, third generation."],
"Apple iPad":["IPad-WiFi-1stGen.jpg","First-generation Apple iPad (Wi-Fi)."],
"Apple iPhone 4":["IPhone 4 Black.jpg","Black Apple iPhone 4."],
"Kinect for Xbox 360":["Xbox-360-Kinect-Standalone.png","Kinect sensor for Xbox 360."],
"Sony Ericsson Xperia Play":["Sony-Xperia-Play-Open-FL.jpg","Sony Ericsson Xperia Play with the gamepad slid open."],
"Neo Geo X":["Neo-geo-x-console.png","The Neo Geo X handheld."],
"PlayStation TV":["PlayStation-TV-FL.jpg","The PlayStation TV microconsole."],
"New Nintendo 3DS":["New-3DS-XL-Black.jpg","A black New Nintendo 3DS XL (the model sold at launch in North America)."],
"Analogue Super Nt":["SuperNT.jpg","The Analogue Super Nt."],
"Evercade":["Evercade Original Handheld Console SwitchedOff.jpg","The original Evercade handheld, switched off."],
"Ouya":["OUYA-Console-set-h.jpg","The Ouya console with its controller."],
"Nintendo 2DS":["Nintendo-2DS-angle.jpg","The Nintendo 2DS seen at an angle."],
"Super NES Classic Edition":["Super NES Classic Edition.jpg","The Super NES Classic Edition mini console."],
"Sega Genesis Mini":["Sega Genesis Mini 02.jpg","The Sega Genesis Mini console."],
"Lenovo Legion Go":["Lenovo Legion Go.jpg","The Lenovo Legion Go handheld."],
"Nexus 7 (2012)":["Front view of Nexus 7 (cropped).png","Front view of the 2012 Nexus 7 tablet."],
"Kenbak-1":["Kenbak-1 personal computer.jpg","A Kenbak-1 personal computer."],
"Intel 4004":["Intel C4004.jpg","An Intel C4004 microprocessor in ceramic package."],
"HP-35":["HP-35 Red Dot.jpg","An HP-35 pocket calculator."],
"Intel 8008":["KL Intel C8008-1.jpg","An Intel C8008-1 microprocessor."],
"Xerox Alto":["Xerox Alto mit Rechner.jpg","A Xerox Alto workstation with its display, keyboard and mouse."],
"IBM 5100":["IBM 5100 - MfK Bern.jpg","An IBM 5100 portable computer at the Museum fuer Kommunikation, Bern."],
"IMSAI 8080":["IMSAI 8080, cropped.jpg","An IMSAI 8080 computer."],
"KIM-1":["MOS KIM-1 IMG 4211 cropped scale.jpg","A MOS Technology KIM-1 single-board computer."],
"Cray-1":["Cray-1-Computer History Museum-20070512.jpg","A Cray-1 supercomputer at the Computer History Museum."],
"Zilog Z80":["Zilog Z80.jpg","A Zilog Z80 microprocessor."],
"MOS 6502":["MOS 6502AD 4585 top.jpg","A MOS Technology 6502 microprocessor."],
"NEC TK-80":["TK-80.jpg","An NEC TK-80 training computer."],
"SWTPC 6800":["SWTPC6800 Computer.jpg","A Southwest Technical Products SWTPC 6800 computer."],
"Motorola 6800":["Motorola MC6800 microprocessor.jpg","A Motorola MC6800 microprocessor."],
"Intel 8085":["KL Intel P8085AH.jpg","An Intel P8085AH microprocessor."],
"TMS9900":["KL TI TMS9900 Black Background.jpg","A Texas Instruments TMS9900 microprocessor."],
"Motorola 6809":["KL Motorola MC6809.jpg","A Motorola MC6809 microprocessor."],
"RCA CDP1802":["KL RCA 1802.jpg","An RCA 1802 COSMAC microprocessor."],
"Mattel Auto Race":["Mattel Electronics Auto Race, No. 9879, Red LED, Made In Hong Kong, Copyright 1976 (LED Handheld Electronic Game).jpg","A Mattel Electronics Auto Race handheld game."],
"Atari CX40 Joystick":["Atari CX40 Joystick.jpg","An Atari CX40 joystick."],
"Altair 680":["Altair 680.jpg","An Altair 680 computer."],
"Intel 8080":["Intel 8080 open-closed.jpg","An Intel 8080 microprocessor, packaged and with the lid removed."],
"Heathkit H8":["Heathkit H-8 computer.jpg","A Heathkit H-8 computer."],
"VAX-11/780":["VAX 11-780 intero.jpg","A VAX-11/780 computer."],
"COSMAC Elf":["COSMAC ELF CHM.jpg","A COSMAC Elf computer at the Computer History Museum."],
"Cybiko":["Cybiko.jpg","The Cybiko handheld."],
"Power Mac G4":["GraphiteG4.jpg","Power Mac G4 in the original Graphite case."],
"Power Mac G4 Cube":["PowerMac_Cube.jpg","Apple Power Mac G4 Cube."],
"Nokia 3310":["Nokia_3310_grey_all_sides.jpg","Nokia 3310 phone, seen from all sides."],
"NVIDIA GeForce 256":["VisionTek_GeForce_256.jpg","VisionTek GeForce 256 graphics card."],
"Matrox G400":["Matrox_G400max.jpg","Matrox Millennium G400 MAX graphics card."],
"Intel Pentium III Coppermine":["KL_Intel_Pentium_III_Coppermine.jpg","Intel Pentium III Coppermine processor."],
"AMD Duron":["AMD_Duron_D600AUT1B.jpg","AMD Duron 600 MHz processor."],
"AMD Athlon Thunderbird":["KL_AMD_Athlon_XP_Thunderbird.jpg","AMD Athlon processor with Thunderbird core."],
"WonderSwan Color":["WonderSwan-Color-Blue-Left.jpg","WonderSwan Color handheld in blue."],
"Transmeta Crusoe":["Transmeta_TM5600.jpg","Transmeta Crusoe TM5600 processor, a closely related model."],
"Creative Nomad Jukebox":["Creative_Nomad_Jukebox_2.jpg","Creative Nomad Jukebox 2, the successor to the original Nomad Jukebox."],
"GameCube Controller":["GameCube controller.png","The standard GameCube controller."],
"Nintendo e-Reader":["Nintendo E-Reader.jpg","Nintendo e-Reader card scanner for Game Boy Advance."],
"Kodak DCS Pro 14n":["Kodak DCS Pro 14n 7638.jpg","Kodak DCS Pro 14n DSLR."],
"eMac":["Apple-eMac-FL (transparent).png","Apple eMac, front view."],
"iMac G4":["Apple iMac G4 (32871160027).jpg","Apple iMac G4 on its adjustable arm."],
"PowerBook G4 Titanium":["1ghz Titanium Apple PowerBook G4.jpg","Titanium PowerBook G4 (later 1 GHz model; same design as the 2001 original)."],
"GP32":["Gp32.jpg","The GP32 handheld."],
"NVIDIA GeForce4 Ti 4600":["NVIDIA GeForce4 Ti 4600 Mac.jpg","GeForce4 Ti 4600 card (Mac edition)."],
"Nintendo WaveBird":["Nintendo-GameCube-Wavebird-Silver.jpg","Silver Nintendo WaveBird wireless GameCube controller."],
"NVIDIA GeForce 3":["GeForce3 Ti 500.jpg","GeForce3 Ti 500 card (higher-clocked variant of the GeForce 3 family)."],
"Sigma SD9":["Sigma SD9 front.jpg","Sigma SD9 DSLR with Foveon X3 sensor."],
"Sound Blaster Audigy":["Creative Sound Blaster Audigy SB0090.jpg","Creative Sound Blaster Audigy sound card."],
"Capcom Steel Battalion Controller":["Steel Battalion controllers.jpg","The Steel Battalion mech controller for Xbox."],
"Intel Itanium 2":["KL Intel Itanium2.jpg","An Intel Itanium 2 processor."],
"Apple Xserve":["Xserve G4.jpg","The original G4-based Apple Xserve 1U rack server."],
"Matrox Parhelia-512":["Matrox parhelia 128mb agp.jpg","A Matrox Parhelia-512 128 MB AGP card."],
"xD-Picture Card":["XD card 16M Fujifilm front.png","A Fujifilm 16 MB xD-Picture Card."],
"Power Mac G5":["Apple Power Macintosh G5 2003 7982.jpg","A 2003 Apple Power Mac G5."],
"Apple iSight":["Apple iSight FireWire Camera.jpg","The Apple iSight FireWire webcam."],
"Canon EOS 10D":["Canon EOS 10D with lens.jpg","A Canon EOS 10D with a lens attached."],
"Nokia 1100":["Nokia1100 new.jpg","The Nokia 1100."],
"Canon EOS 300D (Digital Rebel)":["Eos 300d v sst.jpg","The Canon EOS 300D (Digital Rebel)."],
"AMD Athlon 64":["AMD Athlon 64 3200+ ADA3200AEP5AP.jpg","An AMD Athlon 64 3200+ processor."],
"Game Boy Player":["GameCube-Game-Boy-Player.jpg","The Game Boy Player attached to a GameCube."],
"Olympus E-1":["E-1 vorne.jpg","The Olympus E-1, front view."],
"Linksys WRT54G":["Linksys WRT54G.jpg","A Linksys WRT54G wireless router."],
"ATI Radeon 9700 Pro":["ATI-9700-nl-lg.jpg","An ATI Radeon 9700 graphics card (closely related to the 9700 Pro)."],
"Sound Blaster Audigy 2 ZS":["Soundblaster Audigy2 ZS.jpg","A Sound Blaster Audigy 2 ZS card."],
"EyeToy":["PS2-Eyetoy.jpg","The PlayStation 2 EyeToy USB camera."],
"iBook G4":["IBook G4.jpg","An Apple iBook G4."],
"Apple iPod mini (1st generation)":["Green ipodmini 1stgen.jpg","A green first-generation iPod mini."],
"iMac G5":["IMac G5 Rev. A front.jpg","The first-revision iMac G5, front view."],
"Nikon D70":["Nikon D70 with 35mm f2.jpg","A Nikon D70 with a 35mm f/2 lens."],
"Canon EOS 20D":["Canon EOS 20D front.jpg","The Canon EOS 20D, front view."],
"C64 Direct-to-TV":["C64 DTV.jpg","The C64 Direct-to-TV joystick."],
"Das Keyboard":["DasKeyboardV1.jpg","The first-generation Das Keyboard."],
"Palm Treo 600":["Treo600.jpg","The Palm Treo 600."],
"Palm Treo 650":["Treo 650 TomTom Navigator.jpg","A Palm Treo 650 running TomTom Navigator."],
"AMD Sempron":["AMD Sempron 3400+.jpg","An AMD Sempron 3400+ processor."],
"Transmeta Efficeon":["Transmeta Efficeon TM8600 1GHz.jpg","A Transmeta Efficeon TM8600 1 GHz processor."],
"Intel Pentium 4 Prescott":["Intel Pentium4 640 Prescott (98 Quality JPG).jpg","An Intel Pentium 4 640 (Prescott) processor."],
"Apple AirPort Express":["Apple airport express.jpg","An Apple AirPort Express base station."],
"Arduino":["Arduino Uno - R3.jpg","An Arduino Uno R3, a later board in the platform that began in 2005."],
"Creative Zen Touch":["Zen touch.jpg","A Creative Zen Touch player."],
"Creative Zen Micro":["Zenmicro.jpg","A Creative Zen Micro player."],
"NVIDIA GeForce 6800 Ultra":["NVIDIA GeForce 6800 Ultra 512MB.jpg","A GeForce 6800 Ultra card (512 MB variant)."],
"NVIDIA GeForce 6600 GT (SLI)":["Gigabyte GV-NX66T128VP.jpg","A Gigabyte GeForce 6600 GT card."],
"Power Macintosh 9500":["PowerMac 9500 132 front.jpg","Front of a Power Macintosh 9500/132, a later speed grade of the same case."],
"Virtual Boy (Japan)":["Virtual-Boy-Set.jpg","Virtual Boy console with its controller."],
"Virtual Boy (North America)":["Virtual-Boy-Set.jpg","Virtual Boy console with its controller."],
"BeBox":["Samsung SyncMaster 191T and BeBox 20081114.jpg","A BeBox next to a monitor, showing the front LED bars."],
"Cyrix 6x86":["Cyrix 6x86-P166.jpg","A Cyrix 6x86 P166+ processor, a later speed grade of the same CPU."],
"AMD Am5x86":["KL AMD 5x86.jpg","An AMD Am5x86 processor."],
"Satellaview":["Satellaview with Super Famicom.jpg","A Satellaview unit attached to a Super Famicom."],
"Microsoft SideWinder 3D Pro":["Sidewinder 3D Pro.jpg","Microsoft SideWinder 3D Pro joystick."],
"Intel Pentium Pro":["Ppro512K.jpg","An Intel Pentium Pro processor in its ceramic Socket 8 package."],
"Sound Blaster AWE64":["KL Creative Labs Soundblaster AWE64 Gold CT4390.jpg","Sound Blaster AWE64 Gold, a closely related model."],
"ATI Rage Pro":["ATI 3D Rage Pro PCI 8MB.jpg","ATI 3D Rage Pro PCI card with 8 MB."],
"PlayStation Net Yaroze":["Net-Yaroze-Full-Sdk.jpg","The Net Yaroze full development kit."],
"Twentieth Anniversary Macintosh":["Apple Museum (Prague) 20th Anniversary Mac (1997).jpg","Twentieth Anniversary Macintosh on display at the Apple Museum, Prague."],
"Nokia 9000 Communicator":["Nokia9000.png","Nokia 9000 Communicator open."],
"AMD K6":["AMD K6-166ALR.jpg","AMD K6-166 processor."],
"AMD K5":["AMD K5 PR166 Front.jpg","AMD K5 PR166 processor, front."],
"Happy Hacking Keyboard":["Happy Hacking Keyboard (1st Generation).jpg","The first-generation Happy Hacking Keyboard."],
"Intel Pentium MMX":["Intel Pentium MMX 166 PGA Front.jpg","Intel Pentium MMX 166 MHz processor."],
"Toshiba Libretto 20":["Libretto 70CT.jpg","Toshiba Libretto 70CT, a later model in the same line."],
"Nintendo 64 Rumble Pak":["N64-Rumble-Pak.jpg","The Nintendo 64 Rumble Pak."],
"Sony Glasstron":["Glasstron.jpg","Sony Glasstron head-mounted display."],
"Sony Digital Mavica MVC-FD5":["Sony Mavica FD5 4040.jpg","Sony Digital Mavica MVC-FD5."],
"ATI 3D Rage II":["3DRageIICard.jpg","ATI 3D Rage II graphics card."],
"PalmPilot":["Palmpilot5000 eu.png","Palm Pilot 5000, a closely related model to the Pilot 1000."],
"Intel Pentium II":["Pentium II.jpg","Intel Pentium II processor in its Slot 1 cartridge."],
"Game Boy Printer":["Game Boy Printer.jpg","Game Boy Printer, the thermal sticker printer for the Game Boy."],
"Palm III":["Palm III 24.jpg","Palm III handheld."],
"Hyper Neo Geo 64":["Noegeo64.jpg","Hyper Neo Geo 64 arcade hardware."],
"Sony DualShock":["PlayStation-DualShock.jpg","The original PlayStation DualShock controller."],
"Power Macintosh G3 (Beige)":["Macintosh G3 DT.jpg","Beige Power Macintosh G3 in the desktop case."],
"Intel Celeron":["KL Intel Celeron Covington.jpg","Intel Celeron 'Covington' (266 MHz class), the first cacheless Celeron."],
"AMD K6-2":["AMD K6-2 266 MHz (16498137495).jpg","AMD K6-2 266 MHz processor."],
"Intel i740":["Intel I740 4mb 3.jpg","Intel i740 AGP graphics card."],
"Nintendo 64 Transfer Pak":["Nintendo-64-GB-Transfer-Pak.jpg","Nintendo 64 Transfer Pak for Game Boy cartridges."],
"Power Macintosh G3 (Blue and White)":["Apple Yosemite.jpg","Power Mac G3 Blue and White (codename Yosemite)."],
"Palm VII":["Palm7-dock.jpg","Palm VII in its docking cradle."],
"Palm V":["Palm V by Andrew Fresh (cropped).jpg","A Palm V handheld."],
"IBM Microdrive":["IBM Microdrive 0321.jpg","An IBM Microdrive, a hard drive in a CompactFlash Type II package."],
"iBook G3":["IBookG3 Palourde2.png","An original iBook G3 clamshell."],
"Sound Blaster Live!":["Sblive!.jpg","A Creative Sound Blaster Live! card."],
"iMac G3":["Imac G3 Bondi Blue side.jpg","The original Bondi Blue iMac G3, side view."],
"Intel Celeron 300A":["Intel Celeron 300A MHz.jpg","An Intel Celeron 300A processor."],
"Diamond Rio PMP300":["Rio pmp300.jpg","The Diamond Rio PMP300 MP3 player."],
"Sony Memory Stick":["Memory Stick Front and Back.jpg","Front and back of an original Sony Memory Stick."],
"Nintendo 64 Expansion Pak":["Nintendo-64-Memory-Expansion-Pak.jpg","The Nintendo 64 Memory Expansion Pak."],
"PocketStation":["Sony-PocketStation.png","The Sony PocketStation."],
"Nikon Coolpix 950":["DSCN1606-coolpix-950.jpg","A Nikon Coolpix 950."],
"Intel Pentium III":["Intel Pentium III Katmai.jpg","An Intel Pentium III (Katmai) processor."],
"WonderSwan":["WonderSwan-Black-Left.jpg","A black WonderSwan handheld."],
"Apple AirPort":["Apple graphite airport base station front.jpg","The original graphite AirPort Base Station."],
"Microsoft SideWinder Freestyle Pro":["Microsoft-SideWinder-Freestyle-Pro-Gamepad.jpg","The Microsoft SideWinder Freestyle Pro gamepad."],
"S3 Savage4":["S3 Savage 4.jpg","An S3 Savage4 graphics card."],
"Macintosh IIsi":["Macintosh IIsi 2.jpg","Macintosh IIsi, a low-cost 68030 Macintosh introduced in October 1990."],
"Macintosh Quadra 700":["Macintosh Quadra 700.png","Macintosh Quadra 700."],
"Macintosh Quadra 900":["Macintosh Quadra 900.jpg","Macintosh Quadra 900."],
"Macintosh Classic II":["Macintosh Classic 2.jpg","Macintosh Classic II."],
"PowerBook 170":["PowerBook 170.jpg","PowerBook 170."],
"Sega Game Gear (Japan)":["Sega GameGear 003.jpg","Sega Game Gear handheld."],
"Commodore 64 Games System":["Commodore 64GS.jpg","Commodore 64 Games System (C64GS)."],
"Psion Series 3":["Psion Series 3a.jpg","Psion Series 3a, a closely related later model of the Series 3."],
"Atari Lynx II":["Atari-Lynx-II-Handheld-Angled.jpg","Atari Lynx II handheld."],
"Sound Blaster 2.0":["KL Creative Labs Soundblaster 2.0 CT1350B.jpg","Sound Blaster 2.0 (CT1350B)."],
"Sound Blaster Pro":["CT1330A.jpg","Sound Blaster Pro card (CT1330A)."],
"Apple StyleWriter":["Apple StyleWriter.jpg","Apple StyleWriter inkjet printer."],
"AMD Am386":["Am386DX-40.jpg","AMD Am386DX-40 processor."],
"Sega CD":["Sega-CD-Model1-Set.jpg","Sega CD Model 1 attached to a Genesis Model 1."],
"Atari Falcon030":["Atari_Falcon_030_(white_bg).jpg","Atari Falcon030 computer."],
"Amiga 4000":["Amiga_4000_desktop_original.png","Commodore Amiga 4000 desktop."],
"Sun SPARCstation 10":["Sun_SparcStation_10_with_CRT.jpg","Sun SPARCstation 10 with CRT monitor."],
"Macintosh Quadra 950":["Quadra_950_hero.jpg","Macintosh Quadra 950 tower."],
"Macintosh Performa":["Macintosh_Performa_5200.jpg","A Macintosh Performa 5200, a later model of the Performa line."],
"Dendy":["Dendy_Classic-2_Game_console.jpg","A Dendy Classic-2, a later model of the Famicom clone."],
"IBM ThinkPad 300, 700 and 700C":["IBM_ThinkPad_720C.jpg","IBM ThinkPad 720C, a closely related ThinkPad 700 series model."],
"TurboDuo":["NEC-TurboDuo-Console-wController-L.jpg","NEC TurboDuo console with controller."],
"DEC Alpha 21064":["Alpha_AXP_21064_diephoto1.jpg","Die photo of the DEC Alpha 21064 (Alpha AXP)."],
"Super NES (Europe)":["Wikipedia_SNES_PAL.jpg","A PAL-region Super Nintendo console."],
"IBM TrackPoint":["Pointing_stick_of_a_Lenovo_ThinkPad_keyboard-4488.jpg","A TrackPoint pointing stick on a later ThinkPad keyboard."],
"Gravis UltraSound":["Ultrasound_classic.jpg","Gravis UltraSound Classic card."],
"Intel 486DX2":["Intel_i486_DX2_66_CPU_SX955.jpg","Intel 486DX2-66 processor."],
"Macintosh Color Classic":["Macintosh Colour Classic 1994 (retouched).jpg","A Macintosh Color Classic."],
"Amiga CD32":["Amiga-CD32-wController-L-TRSP.png","The Amiga CD32 console with its controller."],
"Apple Newton MessagePad":["Apple Newton-IMG 0454-cropped.jpg","An Apple Newton MessagePad."],
"SGI Indy":["Silicon Graphics Indy.jpg","A Silicon Graphics Indy workstation."],
"Intel Pentium":["KL Intel Pentium P5.jpg","An Intel Pentium (P5) processor."],
"Sega Pico":["SEGA Pico folded.png","The Sega Pico, folded closed."],
"Pioneer LaserActive":["Pioneer-LaserActive-Set-FL.jpg","A Pioneer LaserActive set."],
"FM Towns Marty":["FM-Towns-Marty-Console-Set.jpg","The Fujitsu FM Towns Marty console set."],
"Mega Duck":["Mega-Duck-Handheld-FL.jpg","The Mega Duck handheld."],
"Apple Adjustable Keyboard":["Apple Adjustable Keyboard M1242 different views.jpeg","The Apple Adjustable Keyboard shown from several angles."],
"HP OmniBook 300":["HP OmniBook 300.jpg","An HP OmniBook 300."],
"Sega Genesis CDX":["Genesis-CDX-Console-Set.jpg","The Sega Genesis CDX console set."],
"PowerPC 601":["IBM PowerPC601 PPC601FD-080-2 top.jpg","An IBM PowerPC 601 processor."],
"Kodak DCS 420":["Kodak DCS 420 Digital Camera Back 01 (white bg).jpg","The Kodak DCS 420 digital camera back."],
"Macintosh Quadra 840AV":["Macintosh Quadra 840AV.jpg","A Macintosh Quadra 840AV."],
"Roland SC-88":["Roland SC-88Pro.jpg","The Roland SC-88Pro, a later model of the SC-88 line."],
"Number Nine Imagine 128":["NumberNine Imagine128 1280 PCI.jpg","A Number Nine Imagine 128 graphics card."],
"Macintosh TV":["Macintosh TV.png","The Macintosh TV."],
"Sinclair QL":["Sinclair QL Top.jpg","Sinclair QL home computer, top view."],
"TRS-80 Model 100":["Radio Shack TRS-80 Model 100.jpg","Radio Shack TRS-80 Model 100 portable computer."],
"Apple Lisa":["Apple Lisa Computer.jpg","Apple Lisa computer."],
"IBM PC XT":["IBM PC XT 5160.JPG","IBM PC XT model 5160."],
"Sharp X68000":["Sharp X68000 XVI.jpg","The Sharp X68000 XVI, a later model in the X68000 line."],
"Macintosh Plus":["Apple Macintosh Plus.jpg","A Macintosh Plus."],
"Commodore 64C":["Commodore 64C.jpg","A Commodore 64C."],
"Famicom Disk System":["Nintendo-Famicom-Disk-System.jpg","The Famicom Disk System drive attached to a Famicom."],
"Apple IIGS":["Apple IIgs 004.jpg","An Apple IIGS."],
"Roland MT-32":["Roland MT-32.jpg","A Roland MT-32 sound module"],
"Sound Blaster 16":["Sound Blaster 16.JPG","A Sound Blaster 16 ISA card"],
"IBM Model M":["IBM Model M 1391403 keyboard.jpg","An IBM Model M keyboard"],
"IBM Model M keyboard":["IBM Model M 1391403 keyboard.jpg","An IBM Model M keyboard"],
"Toshiba Libretto 110CT":["Libretto 70CT.jpg","A Toshiba Libretto 70CT, a close relative of the 110CT"],
"IBM Personal Computer":["IBM PC 5150.jpg","An IBM PC 5150"],
"Sony Mavica MVC-A7AF":["Pro Mavica MVC-A7AF (1987).jpg","A Pro Mavica MVC-A7AF"],
"Sony Digital Mavica MVC-FD7":["Sony Mavica MVC-FD7 digital camera (52267498373).jpg","A Sony Mavica MVC-FD7"],
"Sony Digital Mavica MVC-FD81":["Sony Digital Mavica MVC-FD81.jpg","A Sony Digital Mavica MVC-FD81"],
"Sony Digital Mavica MVC-FD88":["Sony Mavica MVC-FD88.JPG","A Sony Mavica MVC-FD88"],
"Sony Digital Mavica MVC-FD95":["Sony Mavica MVC-FD95.JPG","A Sony Mavica MVC-FD95"],
"Sony Mavica MVC-FD100":["Sony Mavica MVC-FD100 digital camera - insert a 720k floppy disk (52132518117).jpg","A Sony Mavica MVC-FD100 taking a floppy disk"],
"Apple iPod":["IPod 1G.jpg","A first-generation iPod"],
"Apple iPod classic (6th generation)":["Ipod-classic-6th-gen.jpg","A sixth-generation iPod classic"],
"Apple iPod shuffle (1st generation)":["IPod Shuffle 1st Generation.jpg","A first-generation iPod shuffle"],
"Apple iPod touch (1st generation)":["Ipod-touch-1st-gen.jpg","A first-generation iPod touch"],
"Apple QuickTake 200":["Apple QuickTake 200 Digital Camera.jpg","An Apple QuickTake 200"],
"Atari 2600 (VCS)":["Atari-2600-Wood-4Sw-Set.jpg","A woodgrain four-switch Atari 2600 with controllers"],
"Atari 2600 Jr.":["Atari-2600-Jr-Console-02.jpg","An Atari 2600 Jr."],
"Nintendo Entertainment System (US nationwide)":["NES-Console-Set.jpg","An NES with controllers"],
"Sega Genesis (North America)":["Sega-Genesis-Mod1-Set.jpg","A Sega Genesis Model 1 with controller"],
"Commodore 64":["Commodore-64-Computer-FL.jpg","A Commodore 64"],
"Magnavox Odyssey":["Magnavox-Odyssey-Console-Set.jpg","A Magnavox Odyssey with controllers"],
"Magnavox Odyssey 2":["Magnavox-Odyssey-2-Console-04.jpg","A Magnavox Odyssey 2"],
"Vectrex":["Vectrex-Console-Set.jpg","A Vectrex console with controller"],
"Apple I":["CHM Apple I.JPG","An Apple I at the Computer History Museum"],
"Home Pong":["TeleGames-Atari-Pong.jpg", "A Sears Tele-Games Atari Pong (the Atari-branded Home Pong looks similar)"],
"Magnavox Odyssey 200":["Magnavox Odyssey 200.jpg", "A Magnavox Odyssey 200"],
"Coleco Telstar":["Coleco Telstar (1976) 2.jpg", "A Coleco Telstar"],
"Magnavox Odyssey 300":["Odyssey-300.jpg", "A Magnavox Odyssey 300"],
"Fairchild Channel F":["Fairchild-Channel-F.jpg", "A Fairchild Channel F"],
"Coleco Telstar Arcade":["Coleco-Telstar-Arcade-Pongside-L.jpg", "A Coleco Telstar Arcade"],
"RCA Studio II":["RCA-Studio-II-FL.jpg", "An RCA Studio II"],
"Nintendo Color TV-Game 6":["Nintendo Color TV game 6 (Cut out).jpg", "A Nintendo Color TV-Game 6"],
"Interton VC 4000":["Interton-Electronic-VC-4000-Console-01.jpg", "An Interton VC 4000"],
"Bally Astrocade":["Bally Astrocade.jpg", "A Bally Astrocade"],
"APF-MP1000":["APF-MP1000-Console-BL.jpg", "An APF MP1000"],
"Microvision":["Milton-Bradley-Microvision-Handheld-FL.jpg", "A Milton Bradley Microvision"],
"Mattel Intellivision":["Mattel-Intellivision-Console-BR.jpg", "A Mattel Intellivision"],
"Game & Watch":["Game-and-watch-ball.png", "A Nintendo Game  Watch Ball (the first Game  Watch)"],
"VTech CreatiVision":["VTech-CreatiVision-Console-02.jpg", "A VTech CreatiVision"],
"Entex Select-A-Game":["Entex-SelectAGame.jpg", "An Entex Select-A-Game"],
"Cassette Vision":["Epoch Cassette Vision.JPG", "An Epoch Cassette Vision"],
"Arcadia 2001":["Emerson-Arcadia-2001.jpg", "An Emerson Arcadia 2001"],
"ColecoVision":["ColecoVision-Console-Front.jpg", "A ColecoVision"],
"Entex Adventure Vision":["Entex-AdventureVision.jpg", "An Entex Adventure Vision"],
"Atari 5200":["Atari-5200-Console-Set.jpg", "An Atari 5200"],
"Philips Videopac+ G7400":["Philips Videopac G7400.jpg", "A Philips Videopac+ G7400"],
"Nintendo Famicom (Japan)":["Nintendo-Famicom-Console-FL.jpg", "A Nintendo Famicom"],
"SG-1000":["Sega-SG-1000-Console-Set.jpg", "A Sega SG-1000"],
"Casio PV-1000":["Casio-PV-1000-Console-01.jpg", "A Casio PV-1000"],
"Gakken Compact Vision TV Boy":["Compact Vision TV Boy, Gakken 01.png", "A Gakken Compact Vision TV Boy"],
"Epoch Game Pocket Computer":["Epoch-Game-Pocket-Computer-FL.jpg", "An Epoch Game Pocket Computer"],
"Super Cassette Vision":["Super-Cassette-Vision-Console-L.jpg", "An Epoch Super Cassette Vision"],
"Nintendo Entertainment System (US test market)":["Nintendo Entertainment System NES (1985) 1.jpg", "A Nintendo Entertainment System (the US retail version looks similar)"],
"Sega Mark III (Japan)":["Sega Mark III.jpg", "A Sega Mark III"],
"Atari 7800":["Atari-7800-Console-Set.png", "An Atari 7800"],
"Sega Master System (North America)":["Sega-Master-System-Set.jpg", "A Sega Master System"],
"Atari XEGS":["Atari XEGS.jpg", "An Atari XEGS"],
"Micro Genius":["Micro Genius IQ-901 5614992132.jpg", "A Micro Genius IQ-901 Famicom clone console"],
"NEC PC Engine (Japan)":["PC-Engine-Console-Set.jpg", "An NEC PC Engine"],
"Sega Mega Drive (Japan)":["Sega-Mega-Drive-JP-Mk1-Console-Set.jpg", "A Sega Mega Drive (Japan, Model 1)"],
"TurboGrafx-16 (North America)":["TurboGrafx-16-Console.jpg", "A TurboGrafx-16"],
"Sega Master System II":["Master System II.jpg", "A Sega Master System II"],
"Super Famicom (Japan)":["Super-Famicom-Console-Set.jpg", "A Nintendo Super Famicom"],
"Super NES (North America)":["SNES-Mod1-Console-Set.png", "A Super Nintendo Entertainment System"],
"NEC PC Engine Duo":["PC-Engine-Duo-Console-Set.png", "An NEC PC Engine Duo"],
"Philips CD-i":["Philips-CDi-Console-Back.jpg", "A Philips CD-i (rear view)"],
"Sega Mega-CD (Japan)":["MegaCD.png", "A Sega Mega-CD"],
"Sega Genesis Model 2":["Sega-Genesis-Mk2-6button.jpg", "A Sega Genesis Model 2 with a six-button controller"],
"NES-101 (New-Style NES)":["NES-101-Console-Set.jpg", "A Nintendo NES-101 (new-style NES)"],
"NEC PC-FX":["PC-FX-Console-Set.jpg", "An NEC PC-FX"],
"Bandai Playdia":["Playdia-Console-Set.png", "A Bandai Playdia"],
"Sega Nomad":["Sega-Genesis-Nomad-Console-01.jpg", "A Sega Nomad portable Genesis"],
"Casio Loopy":["Casio-Loopy-Console-Set.jpg", "A Casio Loopy console"],
"Super A'Can":["Super-ACan-Console-set-h.jpg", "A Funtech Super A'Can console"],
"Neo Geo CDZ":["Neo-Geo-CDZ-FR.jpg", "An SNK Neo Geo CDZ console"],
"Apple Bandai Pippin":["Bandai-Apple-Pippin-Console-FL.jpg", "An Apple Bandai Pippin console"],
"Nintendo 64 (Japan)":["N64-Console-Set.jpg", "A Nintendo 64 console (the Japanese model looks similar)"],
"Nintendo 64 (North America)":["N64-Console-Set.jpg", "A Nintendo 64 console with controller"],
"Super NES (SNS-101 Redesign)":["Nintendo-Super-NES-Console-101-FL.jpg", "A Super NES SNS-101 redesigned console"],
"Sega Genesis 3":["Sega-Genesis-3-Console-FL.jpg", "A Sega Genesis 3 console"],
"Game Boy Light":["Game-Boy-Light-FL.jpg", "A Nintendo Game Boy Light handheld"],
"Game Boy Color":["Nintendo-Game-Boy-Color-FL.jpg", "A Nintendo Game Boy Color handheld"],
"Sega Dreamcast (Japan)":["Dreamcast-Console-Set.jpg", "A Sega Dreamcast console (the Japanese model looks similar)"],
"Sega Dreamcast (North America)":["Dreamcast-Console-Set.jpg", "A Sega Dreamcast console with controller"],
"Neo Geo Pocket Color":["Neo-Geo-Pocket-Color-Blue-Left.jpg", "An SNK Neo Geo Pocket Color handheld"],
"Nuon":["Nuon-N2000-Console-FR.jpg", "A Nuon N2000 DVD player console"],
"PlayStation 2 (Japan)":["PS2-Fat-Console-Set.jpg", "A Sony PlayStation 2 console (the Japanese model looks similar)"],
"PlayStation 2 (North America)":["PS2-Fat-Console-Set.jpg", "A Sony PlayStation 2 console with controller"],
"Game Boy Advance (Japan)":["Nintendo-Game-Boy-Advance-Purple-FL.jpg", "A Nintendo Game Boy Advance (Japanese model looks similar)"],
"Game Boy Advance (North America)":["Nintendo-Game-Boy-Advance-Purple-FL.jpg", "A Nintendo Game Boy Advance handheld"],
"Nintendo GameCube (Japan)":["GameCube-Console-Set.png", "A Nintendo GameCube console (the Japanese model looks similar)"],
"Nintendo GameCube (North America)":["GameCube-Console-Set.png", "A Nintendo GameCube console with controller"],
"Microsoft Xbox":["Xbox-Console-Front.jpg", "A Microsoft Xbox console"],
"SwanCrystal":["Wonder-Swan-Crystal.jpg", "A Bandai WonderSwan Crystal (SwanCrystal) handheld"],
"Game Boy Advance SP":["Game-Boy-Advance-SP-Mk1-Blue.jpg", "A Nintendo Game Boy Advance SP handheld"],
"Nokia N-Gage":["Nokia-NGage-L.jpg", "A Nokia N-Gage handheld"],
"Tapwave Zodiac":["Tapwave-Zodiac2-FL.jpg", "A Tapwave Zodiac 2 handheld (the Zodiac 1 looks similar)"],
"iQue Player":["Nintendo-N64-iQue-Player-FL.jpg", "An iQue Player console"],
"Xavix PORT":["XaviX-XaviXPORT-Console-FL.jpg", "A XaviX PORT console"],
"Nokia N-Gage QD":["Nokia-NGage-QD.jpg", "A Nokia N-Gage QD handheld"],
"V.Smile":["Vtech Vsmile French version.JPG", "A VTech V.Smile console (French version)"],
"PlayStation 2 Slim (SCPH-70000)":["Sony-PlayStation-2-70001-Console-FL.jpg", "A Sony PlayStation 2 Slim SCPH-70001 console"],
"Nintendo DS (North America)":["Nintendo-DS-Fat-Blue.jpg", "A Nintendo DS handheld"],
"Gizmondo":["Gizmondo.jpg", "A Gizmondo handheld"],
"PlayStation Portable (North America)":["Sony-PSP-1000-Body.jpg", "A Sony PlayStation Portable PSP-1000 handheld"],
"Neo Geo Mini":["Neo Geo Mini 20210313.jpg", "A Neo Geo Mini"],
"PlayStation Classic":["PlayStation Classic Konsole + Controller (transparenter Hintergrund).png", "A PlayStation Classic console with controller"],
"Nintendo Switch Lite":["Nintendo Switch Lite Grey - 01.jpg", "A grey Nintendo Switch Lite"],
"Evercade VS":["Evercade vs with 1 gamepad.png", "An Evercade VS console with a gamepad"],
"Xbox Series X and Series S":["Xbox Series XとSeries S.jpg", "An Xbox Series X and Series S"],
"PlayStation 5":["Playstation 5.jpg", "A PlayStation 5 console"],
"Analogue Pocket":["Analogue Pocket in Yellow (53367343185).jpg", "A yellow Analogue Pocket handheld"],
"Atari VCS":["Atari VCS 03.jpg", "An Atari VCS console"],
"Nintendo Switch (OLED model)":["Nintendo Switch OLED Model.jpg", "A Nintendo Switch OLED model"],
"Playdate":["Playdate front-view.png", "A Playdate handheld, front view"],
"Steam Deck":["Steam Deck (front).jpg", "A Steam Deck, front view"],
"ROG Ally":["ROG ALLY - 2.jpg", "An Asus ROG Ally handheld"],
"Atari 2600+":["Atari 2600 Plus.png", "An Atari 2600+ console"],
"PlayStation 5 Pro":["PlayStation 5 Pro no disc drive.jpg", "A PlayStation 5 Pro console"],
"Nintendo Switch 2":["Nintendo Switch 2 in Handheld Mode.jpg", "A Nintendo Switch 2 in handheld mode"],
"ROG Xbox Ally":["ROG xbox ally.png", "An ROG Xbox Ally handheld"],
"MITS Altair 8800":["MITS Altair 8800 Computer (1975).jpg", "A MITS Altair 8800 computer"],
"Commodore PET 2001":["Commodore PET2001.jpg", "A Commodore PET 2001"],
"Apple II":["Apple-II.jpg", "An Apple II computer"],
"TRS-80 Model I":["Radio Shack Tandy TRS-80 Model I System.JPG", "A Radio Shack TRS-80 Model I system"],
"Atari 400":["Atari-400-Comp.jpg", "An Atari 400 computer"],
"Macintosh SE/30":["Apple Macintosh SE-30 computer (1989) clear background.png", "A Macintosh SE/30 computer"],
"Macintosh Portable":["Macintosh Portable-IMG 7541.jpg", "A Macintosh Portable"],
"Commodore Amiga 3000":["Amiga 3000 Front with White BG.jpg", "A Commodore Amiga 3000"],
"IBM PS/1":["IBM PS1 2011, ValorosoIT collection 1.jpg", "An IBM PS/1 computer"],
"Macintosh Classic":["Mac Classic.jpg", "A Macintosh Classic"],
"Macintosh LC":["Macintosh LC III front.jpg", "A Macintosh LC III (the original LC looks similar)"],
"Commodore CDTV":["Commodore CDTV Setup.jpg", "A Commodore CDTV set-up"],
"HP 95LX":["HP 95LX Pocket Computer.JPG", "An HP 95LX pocket computer"],
"PowerBook 140":["Macintosh PowerBook 140.jpg", "A Macintosh PowerBook 140"],
"Apple PowerBook 100":["Powerbook 100 pose.jpg", "An Apple PowerBook 100"],
"Compaq Contura":["Compaq Contura 430C front.jpg", "A Compaq Contura 430C notebook"],
"Amiga 600":["Amiga 600.jpg", "A Commodore Amiga 600"],
"Amiga 1200":["Amiga 1200.jpg", "A Commodore Amiga 1200"],
"Compaq ProLiant":["Compaq Proliant 2500.JPG", "A Compaq ProLiant 2500 server"],
"Dell Dimension":["Dell Dimension 433SV 486.jpg", "A Dell Dimension 433SV desktop PC"],
"Dell OptiPlex":["Dell OptiPlex GX1.jpg", "A Dell OptiPlex GX1 (a later model in the OptiPlex line)"],
"Dell XPS":["Dell XPS 700.JPG", "A Dell XPS 700 (a much later model in the XPS line)"],
"Compaq Presario":["Compaq Presario 5000.jpg", "A Compaq Presario 5000 desktop PC"],
"Dell Latitude":["Dell Latitude CPx .jpg", "A Dell Latitude CPx laptop (a later model in the Latitude line)"],
"Power Macintosh":["Apple-power-macintosh-6500-300.jpg", "A Power Macintosh 6500 (a later model in the Power Macintosh line)"],
"IBM Aptiva":["Ibm aptiva.jpg", "An IBM Aptiva computer"],
"IBM ThinkPad 701C":["Thinkpad 701.jpg", "An IBM ThinkPad 701 (the 701C looks the same)"],
"HP Pavilion 5030":["Detail of HP Pavilion 5030.webp", "An HP Pavilion 5030 desktop PC"],
"Gateway 2000 Solo":["Gateway Solo 2200.JPG", "A Gateway Solo 2200 (a later Solo model)"],
"Gateway Destination":["Gateway 2000 Destination.jpg", "A Gateway 2000 Destination PC"],
"Kodak DCS 520":["Kodak DCS 520C.jpg", "A Kodak DCS 520 (the 520C color version)"],
"Kodak DCS 560":["Kodak DCS 560 Front.jpg", "A Kodak DCS 560 digital SLR"],
"Game Boy Camera":["Game-Boy-Camera.jpg", "A Nintendo Game Boy Camera"],
"Sony Digital Mavica MVC-FD83":["Sony Mavica MVC-FD 83 (51878635648).jpg", "A Sony Digital Mavica MVC-FD83"],
"Kodak DC260":["Kodak Dc 260 digital camera.JPG", "A Kodak DC260 digital camera"],
"Sony Digital Mavica MVC-FD90":["Sony Mavica FD-90 digital camera. Using floppy disk to store photos. (52215832870).jpg", "A Sony Mavica FD-90 floppy disk camera"],
"Sony Digital Mavica MVC-FD91":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD91 looks similar)"],
"Sony Digital Mavica MVC-FD85":["Sony Digital Mavica MVC-FD81.jpg", "A Sony Digital Mavica MVC-FD81 (the FD85 looks similar)"],
"Sony Mavica MVC-FD87":["Sony Mavica MVC-FD88.JPG", "A Sony Mavica MVC-FD88 (the FD87 looks similar)"],
"Sony Mavica MVC-FD92":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD92 looks similar)"],
"Sony Mavica MVC-FD97":["Sony Mavica MVC-FD95.JPG", "A Sony Mavica MVC-FD95 (the FD97 looks similar)"],
"Sony CD Mavica MVC-CD300":["Mavica-cd400-front.jpg", "A Sony CD Mavica MVC-CD400 (the CD300 looks similar)"],
"Sony CD Mavica MVC-CD400":["Mavica-cd400-front.jpg", "A Sony CD Mavica MVC-CD400"],
"Nikon D1":["Nikon D1 8373.jpg", "A Nikon D1 digital SLR"],
"Nikon Coolpix 990":["Nikon Coolpix 990.jpg", "A Nikon Coolpix 990 digital camera"],
"Canon EOS D30":["EOS D30 with Pentacon lens.JPG", "A Canon EOS D30 digital SLR fitted with a Pentacon lens"],
"Sharp J-SH04":["Sharp J-SH04 CP+ 2011.jpg", "A Sharp J-SH04 camera phone"],
"Apple iPod nano (4th generation)":["IPod Nano 4G black.jpg", "A black Apple iPod nano (4th generation)"],
"Apple iPod touch (2nd generation)":["IPod Touch 2G Backlight.JPG", "An Apple iPod touch (2nd generation) with its screen lit"],
"Apple iPod classic (160 GB, 2009)":["IPod Classic 6th Generation Black.jpg", "An Apple iPod classic (6th generation, the 160 GB model looks similar)"],
"Apple iPod touch (4th generation)":["4th generation iPod touch.JPG", "An Apple iPod touch (4th generation)"],
"Apple iPod nano (7th generation)":["IPod nano 7G pink front.JPG", "A pink Apple iPod nano (7th generation)"],
"IBM Color/Graphics Adapter (CGA)":["IBM Color Graphics Adapter.jpg", "An IBM Color Graphics Adapter card"],
"IBM Monochrome Display Adapter (MDA)":["MDA IBM 1501985.jpg", "An IBM Monochrome Display Adapter card"],
"Hercules Graphics Card":["Hercules Graphics Card.jpg", "A Hercules Graphics Card"],
"IBM Enhanced Graphics Adapter (EGA)":["EGA card.jpg", "An IBM-style Enhanced Graphics Adapter (EGA) card"],
"ATI Mach64":["KL ATI Mach 64 VLB.jpg", "An ATI Mach64 VLB graphics card"],
"NVIDIA RIVA 128":["NVidia Riva 128.jpg", "An NVIDIA RIVA 128 graphics card"],
"3dfx Voodoo2":["3dfx Voodoo2.jpg", "A 3dfx Voodoo2 graphics card"],
"3dfx Voodoo Banshee":["3D Blaster Banshee.jpg", "A Creative 3D Blaster Banshee, a 3dfx Voodoo Banshee card"],
"NVIDIA RIVA TNT":["NVidia Riva TNT.jpg", "An NVIDIA RIVA TNT graphics card"],
"NVIDIA RIVA TNT2":["NVIDIA RIVA-TNT2.JPG", "An NVIDIA RIVA TNT2 graphics card"],
"3dfx Voodoo3":["3dfx Voodoo 3000.jpg", "A 3dfx Voodoo3 3000 graphics card"],
"3dfx Voodoo5 5500":["3dfx Voodoo 5500.jpg", "A 3dfx Voodoo5 5500 graphics card"],
"ATI Radeon HD 4870":["ATI HD4870.JPG", "An ATI Radeon HD 4870 graphics card"]
};
/* Titles whose photo was added in the Round 24 fact check. The Admin photo audit lists them for review. */
var CIMG_NEW=["Mac mini","Game Boy Micro","Apple iPod mini (2nd generation)","Leica M8","Canon EOS 5D","GP2X","Microsoft Zune","MacBook Air","Wii Balance Board","Acer Aspire One","GP2X Wiz","Zeebo","Asus Eee PC","Apple iPhone","Apple iPhone 3G","HTC Dream (T-Mobile G1)","Nintendo DSi","BlackBerry Storm","Microsoft Zune 80","Microsoft Zune 4","Apple iMac (aluminum, 2007)","OLPC XO-1","Panasonic Lumix DMC-G1","NVIDIA GeForce GTX 280","Apple Magic Trackpad","PlayStation Move","Barnes & Noble Nook Color","Apple iPhone 3GS","Palm Pre","Canon PowerShot S100","Microsoft Zune HD","NVIDIA GeForce GTX 480","Wii MotionPlus","Olympus PEN E-P1","Apple iPod touch (3rd generation)","Apple iPad","Apple iPhone 4","Kinect for Xbox 360","Sony Ericsson Xperia Play","Neo Geo X","PlayStation TV","New Nintendo 3DS","Analogue Super Nt","Evercade","Ouya","Nintendo 2DS","Super NES Classic Edition","Sega Genesis Mini","Lenovo Legion Go","Nexus 7 (2012)","Kenbak-1","Intel 4004","HP-35","Intel 8008","Xerox Alto","IBM 5100","IMSAI 8080","KIM-1","Cray-1","Zilog Z80","MOS 6502","NEC TK-80","SWTPC 6800","Motorola 6800","Intel 8085","TMS9900","Motorola 6809","RCA CDP1802","Mattel Auto Race","Atari CX40 Joystick","Altair 680","Intel 8080","Heathkit H8","VAX-11/780","COSMAC Elf","Cybiko","Power Mac G4","Power Mac G4 Cube","Nokia 3310","NVIDIA GeForce 256","Matrox G400","Intel Pentium III Coppermine","AMD Duron","AMD Athlon Thunderbird","WonderSwan Color","Transmeta Crusoe","Creative Nomad Jukebox","GameCube Controller","Nintendo e-Reader","Kodak DCS Pro 14n","eMac","iMac G4","PowerBook G4 Titanium","GP32","NVIDIA GeForce4 Ti 4600","Nintendo WaveBird","NVIDIA GeForce 3","Sigma SD9","Sound Blaster Audigy","Capcom Steel Battalion Controller","Intel Itanium 2","Apple Xserve","Matrox Parhelia-512","xD-Picture Card","Power Mac G5","Apple iSight","Canon EOS 10D","Nokia 1100","Canon EOS 300D (Digital Rebel)","AMD Athlon 64","Game Boy Player","Olympus E-1","Linksys WRT54G","ATI Radeon 9700 Pro","Sound Blaster Audigy 2 ZS","EyeToy","iBook G4","Apple iPod mini (1st generation)","iMac G5","Nikon D70","Canon EOS 20D","C64 Direct-to-TV","Das Keyboard","Palm Treo 600","Palm Treo 650","AMD Sempron","Transmeta Efficeon","Intel Pentium 4 Prescott","Apple AirPort Express","Arduino","Creative Zen Touch","Creative Zen Micro","NVIDIA GeForce 6800 Ultra","NVIDIA GeForce 6600 GT (SLI)","Power Macintosh 9500","Virtual Boy (Japan)","Virtual Boy (North America)","BeBox","Cyrix 6x86","AMD Am5x86","Satellaview","Microsoft SideWinder 3D Pro","Intel Pentium Pro","Sound Blaster AWE64","ATI Rage Pro","PlayStation Net Yaroze","Twentieth Anniversary Macintosh","Nokia 9000 Communicator","AMD K6","AMD K5","Happy Hacking Keyboard","Intel Pentium MMX","Toshiba Libretto 20","Nintendo 64 Rumble Pak","Sony Glasstron","Sony Digital Mavica MVC-FD5","ATI 3D Rage II","PalmPilot","Intel Pentium II","Game Boy Printer","Palm III","Hyper Neo Geo 64","Sony DualShock","Power Macintosh G3 (Beige)","Intel Celeron","AMD K6-2","Intel i740","Nintendo 64 Transfer Pak","Power Macintosh G3 (Blue and White)","Palm VII","Palm V","IBM Microdrive","iBook G3","Sound Blaster Live!","iMac G3","Intel Celeron 300A","Diamond Rio PMP300","Sony Memory Stick","Nintendo 64 Expansion Pak","PocketStation","Nikon Coolpix 950","Intel Pentium III","WonderSwan","Apple AirPort","Microsoft SideWinder Freestyle Pro","S3 Savage4","Macintosh IIsi","Macintosh Quadra 700","Macintosh Quadra 900","Macintosh Classic II","PowerBook 170","Sega Game Gear (Japan)","Commodore 64 Games System","Psion Series 3","Atari Lynx II","Sound Blaster 2.0","Sound Blaster Pro","Apple StyleWriter","AMD Am386","Sega CD","Atari Falcon030","Amiga 4000","Sun SPARCstation 10","Macintosh Quadra 950","Macintosh Performa","Dendy","IBM ThinkPad 300, 700 and 700C","TurboDuo","DEC Alpha 21064","Super NES (Europe)","IBM TrackPoint","Gravis UltraSound","Intel 486DX2","Macintosh Color Classic","Amiga CD32","Apple Newton MessagePad","SGI Indy","Intel Pentium","Sega Pico","Pioneer LaserActive","FM Towns Marty","Mega Duck","Apple Adjustable Keyboard","HP OmniBook 300","Sega Genesis CDX","PowerPC 601","Kodak DCS 420","Macintosh Quadra 840AV","Roland SC-88","Number Nine Imagine 128","Macintosh TV","Sinclair QL","TRS-80 Model 100","Apple Lisa","IBM PC XT","Sharp X68000","Macintosh Plus","Commodore 64C","Famicom Disk System","Apple IIGS"];
function cimgUrl(t,w){var c=CIMG[t];return c?"https://commons.wikimedia.org/wiki/Special:FilePath/"+encodeURIComponent(c[0].replace(/ /g,"_"))+"?width="+(w||480):""}
function cimgPage(t){var c=CIMG[t];return c?"https://commons.wikimedia.org/wiki/File:"+encodeURIComponent(c[0].replace(/ /g,"_")):""}
function cimg(t,w,cls){var u=cimgUrl(t,w);return u?'<img class="cm-photo'+(cls?" "+cls:"")+'" src="'+u+'" alt="'+String(CIMG[t][1]).replace(/[<>&"]/g,"")+'" loading="lazy" referrerpolicy="no-referrer" data-t="'+String(t).replace(/[<>&"]/g,"")+'">':""}
function cimgCredit(t){var c=CIMG[t];return c?'<small class="cm-credit" data-t="'+String(t).replace(/[<>&"]/g,"")+'" hidden>Photo: '+String(c[1]).replace(/[<>&"]/g,"")+'. Free-licensed image from <a href="'+cimgPage(t)+'" target="_blank" rel="noopener noreferrer">Wikimedia Commons</a>; author and license are on that page.</small>':""}
document.addEventListener("error",function(e){var t=e.target;if(t&&t.classList&&t.classList.contains("cm-photo")){var f=t.closest(".cm-fig");t.remove();if(f)f.classList.remove("cm-fig")}},true);
document.addEventListener("load",function(e){var t=e.target;if(t&&t.classList&&t.classList.contains("cm-photo")){var k=t.getAttribute("data-t");document.querySelectorAll(".cm-credit").forEach(function(c){if(c.getAttribute("data-t")===k)c.hidden=false})}},true);
