/* ipod-data.js: Tony's iPod Bench. Facts about what is inside each iPod and how it is repaired and modded.
   Every line was written in our own words from the pages listed under "src" on each model, and anything we could not confirm is left out or said plainly in "gaps".
   Layer kinds drawn by ipodbench.js: back, shell, bezel, bracket, drive, mdrive, batt, logic, lcd, wheel, jack, front, frame, nand.
   A layer with n:1 is numbered in the order a repairer meets it, taken from a published teardown. Layers without it are shown unnumbered because we have not confirmed their order. */
var IPOD={
 pages:{
  ifx:["iFixit device pages and repair guides","https://www.ifixit.com/Device/iPod"],
  everymac:["EveryMac iPod specifications","https://everymac.com/systems/apple/ipod/index-ipod.html"],
  tawiki:["The Apple Wiki","https://theapplewiki.com/wiki/IPod"],
  iflash:["iFlash product pages (iflash.xyz)","https://www.iflash.xyz/"],
  rbx:["Rockbox target status (mirror of the Rockbox wiki)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]
 },
 flash:{
  conv:"4th Gen iPod to iFlash converter",
  sd:"iFlash Solo (one SD card), Dual (two SD cards) or Quad (four microSD cards)",
  sata:"iFlash Sata (mSATA or M.2 SSD)",
  cf:"iFlash CF (CompactFlash card)",
  sdcf:"iFlash SD-CF adapter"
 },
 m:[
 {id:"g1",n:"iPod 1st generation",yrs:"2001 to 2002",num:"No A-number confirmed",blurb:"The one with the mechanical scroll wheel and a FireWire port. We could not find a teardown we trust for it, so we have not drawn its insides.",
  facts:[["Screen","160 x 128 monochrome LCD, about 2 inches"],["Wheel","A mechanical scroll wheel that turns, with four buttons around it"],["Connection","FireWire only, no USB"],["Chip","PortalPlayer PP5002"],["Storage","1.8 inch Toshiba hard drive, 4,200 rpm, 5GB or 10GB"],["Battery","About 1,200 mAh lithium polymer"]],
  layers:[],open:[],
  flash:["No flash adapter is confirmed for this model. iFlash lists the 2nd generation and earlier as not compatible, and iPodWiki says the boards depend on FireWire."],
  rbx:["Limited","Rockbox lists the first and second generations with serious issues, and on some units the scroll wheel does not work under it."],
  fail:[["Sad iPod icon, or a folder with an exclamation mark","Usually the hard drive. Charge it, reset it, try disk mode, and if it still clicks or whirs, replace the drive."]],
  parts:["iPod 1st generation battery","iPod 1st generation hard drive"],
  gaps:["How the case opens, what the parts are called and how they are laid out. We found no source we trust.","Battery voltage and connector."],
  src:[["EveryMac: iPod (1st generation)","https://www.everymac.com/systems/apple/ipod/specs/ipod.html"],["The Apple Wiki: iPod (1st and 2nd generation)","https://theapplewiki.com/wiki/IPod_(1st_and_2nd_generation)"],["iPodWiki: iFlash","https://ipodwiki.com/wiki/IFlash"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"g3",n:"iPod 3rd generation",yrs:"2003 to 2004",num:"A1040",blurb:"Four touch buttons in a row above a touch wheel, and the first dock connector. It opens like a book, from the right edge.",
  facts:[["Model","A1040, EMC 1961. Launched April 2003"],["Storage","1.8 inch Toshiba hard drive, 4,200 rpm, 10 to 40GB over the model run"],["Battery","Sources disagree on the original (630 and 850 mAh are both quoted). iFixit sells an 850 mAh replacement. It plugs in with a white connector."],["Case","Plastic front, metal back"]],
  layers:[
   {k:"back",t:"Metal rear case",d:"Opens last, like the back cover of a book. Lock the hold switch first.",n:0},
   {k:"jack",t:"Headphone-jack ribbon",d:"The first thing to unplug. Its connector is unusually tall, so do not pull the plastic base off the ribbon.",n:1,cable:1},
   {k:"drive",t:"Hard drive and its ribbon",d:"1.8 inch drive on a flat ribbon.",n:2,cable:1},
   {k:"batt",t:"Battery",d:"Unplugs at a white connector. It lifts out of the front section late in the job.",n:3},
   {k:"logic",t:"Logic board",d:"Six T6 Torx screws hold it. The orange touch-wheel cable comes off first.",n:4,cable:1},
   {k:"lcd",t:"Display",d:"Comes away on its own orange ribbon once the logic board is out.",n:5,cable:1},
   {k:"front",t:"Front panel",d:"Carries the touch wheel and button row. Last to come apart.",n:6}],
  open:["Lock the hold switch.","Slide an opening pick into the seam between the plastic front and the metal back at the right edge.","Rock the pick along the right edge to release the five retaining tabs.","Open the two halves like a book and unplug the headphone-jack ribbon first."],
  tools:"Plastic opening pick, spudger, T6 Torx driver",
  flash:["The 4th Gen iPod to iFlash converter fits the 3rd generation, so iFlash Solo, Dual, Quad and CF can go in through it. iPodWiki says some options can stress the drive ribbon, and that the iFlash-ATA1 board supports the 3rd and 4th generations directly."],
  rbx:["Stable","Rockbox lists it with no major issues."],
  fail:[["Touch wheel not responding","The touch-wheel cable has its own iFixit guide, so reseat or replace that first."],["Sad iPod icon, or a folder with an exclamation mark","Usually the hard drive. Replace the drive or fit a flash adapter."],["Won't hold a charge","Replace the battery."]],
  parts:["iPod 3rd generation battery","iPod 3rd generation touch wheel cable","iPod 3rd generation hard drive cable","iPod 3rd generation headphone jack"],
  gaps:["Where each part sits inside the case (top, bottom, left, right) and the dock connector's position.","Pin counts for the ribbons.","Battery voltage and original capacity."],
  src:[["iFixit: 3rd Generation Front Panel Replacement","https://www.ifixit.com/Guide/iPod+3rd+Generation+Front+Panel+Replacement/387"],["iFixit: 3rd Generation Touch Wheel Cable Replacement","https://www.ifixit.com/Guide/iPod+3rd+Generation+Touch+Wheel+Cable+Replacement/385"],["iFixit: iPod 3rd Generation parts","https://www.ifixit.com/Parts/iPod_3rd_Generation"],["EveryMac: iPod (3rd generation)","https://everymac.com/systems/apple/ipod/specs/ipod_3rdgen.html"],["iPodWiki: 4th gen iPod to iFlash converter","https://ipodwiki.com/wiki/4th_gen_iPod_to_iFlash_converter"],["iFlash: 4th Gen converter","https://www.iflash.xyz/store/4th-gen-iflash-converter/"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"g4",n:"iPod 4th generation",yrs:"2004 to 2005",num:"A1059",blurb:"The first click wheel, and a monochrome screen. The case opens at the right edge, like the 3rd generation.",
  facts:[["Model","A1059, EMC 1995. Launched July 2004"],["Storage","1.8 inch ATA-66 hard drive, 4,200 rpm, 20 or 40GB. Its flat ribbon (Apple part 632-0259) plugs into a ZIF connector on the logic board."],["Battery","iFixit sells a 750 mAh replacement shared with the iPod photo. Other sources quote 600 and 950 mAh for the original, so treat the original as unsettled."],["Rating","Apple rated music playback at about 12 hours"]],
  layers:[
   {k:"back",t:"Metal rear panel",d:"Pops off the plastic front from the right edge. Five retaining tabs.",n:0},
   {k:"drive",t:"Hard drive and ribbon",d:"On its own flat ribbon with ZIF connectors."},
   {k:"jack",t:"Headphone jack assembly",d:"A separate iFixit guide, so it comes out as its own piece."},
   {k:"logic",t:"Logic board",d:"The ZIF socket for the drive ribbon is on this board."},
   {k:"lcd",t:"Display",d:"Monochrome LCD."},
   {k:"batt",t:"Battery",d:"iFixit's photo guide shows it stuck down with adhesive in the front case and lifted by its leads, with a spudger to free the glue."},
   {k:"front",t:"Plastic front and click wheel",d:"Click wheel on the front side."}],
  open:["Slide the hold switch away from the headphone jack to lock it.","Put an opening pick into the seam between the plastic front and the metal back on the right edge.","Release the five retaining tabs along that edge, then open the halves."],
  tools:"Plastic opening pick, spudger",
  flash:["The 4th Gen iPod to iFlash converter fits it, then iFlash CF, Solo, Dual or Quad. The iFlash-ATA1 board supports it without the converter. iFlash states capacities up to 256GB with its cards."],
  rbx:["Stable","Rockbox lists the 4th generation greyscale iPod with no major issues."],
  fail:[["Sad iPod icon, or a folder with an exclamation mark","Usually the hard drive, or a torn or loose drive ribbon. Try charge, reset and disk mode first."],["Drive not detected after opening","A cracked ZIF connector on the logic board can do this. An iFixit answer says the repair needed microsoldering, and a new drive ribbon is the cheaper fix when the cable is the problem."],["Shuts down, will not charge","Battery. The same 750 mAh part fits the photo."]],
  parts:["iPod 4th generation battery 750mAh","iPod 4th generation hard drive cable","4th gen iFlash converter"],
  gaps:["The order the parts come out in, which we only have for the 3rd generation and the photo-model battery guide.","Where each part sits inside the case.","Battery voltage and connector."],
  src:[["iFixit: iPod 4th Generation or Photo","https://www.ifixit.com/Device/iPod_4th_Generation_or_Photo"],["EveryMac: iPod (4th generation)","https://everymac.com/systems/apple/ipod/specs/ipod_4thgen.html"],["iFlash: HDD ribbon","https://www.iflash.xyz/store/4g-ribbon/"],["iFixit parts: iPod batteries","https://www.ifixit.com/Parts/iPod/Batteries"],["iFlash: 4th Gen converter","https://www.iflash.xyz/store/4th-gen-iflash-converter/"],["iFixit answer: ZIF drive connector","https://pt.ifixit.com/Answers/View/563941/Zif+HDD+connector+type"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"ph",n:"iPod photo and iPod with color display",yrs:"2004 to 2005",num:"A1099",blurb:"A 4th generation iPod with a color screen. It opens, charges and takes the same battery as the 4th generation.",
  facts:[["Model","A1099, EMC 2022. Launched October 2004 as the iPod photo, renamed the iPod with color display in June 2005"],["Storage","1.8 inch ATA-66 hard drive, 4,200 rpm, 20, 30, 40 or 60GB over its run"],["Battery","The same 750 mAh iFixit replacement as the 4th generation"],["Rating","Apple rated music at up to 15 hours"]],
  layers:[
   {k:"back",t:"Metal rear panel",d:"Same right-edge seam and five tabs as the 4th generation."},
   {k:"drive",t:"Hard drive and ribbon",d:"Same drive family as the 4th generation."},
   {k:"jack",t:"Headphone jack assembly",d:"Separate iFixit guide."},
   {k:"logic",t:"Logic board",d:"Drive ribbon plugs in here."},
   {k:"lcd",t:"Color display",d:"2 inch color LCD."},
   {k:"batt",t:"Battery",d:"Held with adhesive in the front case, lifted by its leads."},
   {k:"front",t:"Plastic front and click wheel",d:"Click wheel on the front side."}],
  open:["Lock the hold switch.","Insert an opening pick between the plastic front and the metal back at the right edge.","Release the five retaining tabs along that edge."],
  tools:"Plastic opening pick, spudger",
  flash:["The 4th Gen converter lists the photo and color models, then iFlash CF, Solo, Dual or Quad goes on top."],
  rbx:["Stable","Rockbox lists iPod Color and Photo with no major issues."],
  fail:[["Sad iPod icon, or a folder with an exclamation mark","Usually the hard drive or its ribbon."],["Display problems, shutdowns, will not charge","These are the themes on iFixit's device page. Replace the battery first, because it is the cheapest."]],
  parts:["iPod photo battery","iPod photo hard drive cable","iPod color display battery"],
  gaps:["Order of parts and their positions inside the case.","Whether the front panel and click wheel come apart on this model."],
  src:[["iFixit: iPod 4th Generation or Photo","https://www.ifixit.com/Device/iPod_4th_Generation_or_Photo"],["EveryMac: iPod photo","https://everymac.com/systems/apple/ipod/specs/ipod_photo.html"],["EveryMac: iPod with color display","https://everymac.com/systems/apple/ipod/specs/ipod_color_20gb.html"],["iFlash: 4th Gen converter","https://www.iflash.xyz/store/4th-gen-iflash-converter/"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"mn",n:"iPod mini",yrs:"2004 to 2005",num:"A1051",blurb:"An aluminum tube with a Microdrive inside. It has no snap-fit halves: the plastic ends come off and the whole inside slides out.",
  facts:[["Model","A1051 for both generations. EMC 1984 (1st) and 2044 (2nd). Launched January 2004 and February 2005"],["Screen","1.67 inch monochrome, blue backlight"],["Storage","A 1 inch Microdrive, 4,200 rpm, ATA-66. 4GB in the 1st generation, 4GB or 6GB in the 2nd."],["Battery","450 mAh in the 1st generation and 650 mAh in the 2nd, both lithium polymer, per The Apple Wiki. iFixit sells one for each (EC007-3 and EC007-5)."],["Rating","Apple rated 8 hours (1st) and up to 18 hours (2nd)"]],
  layers:[
   {k:"shell",t:"Aluminum body",d:"The outer tube. Everything slides out of it.",n:0},
   {k:"bezel",t:"Top and bottom plastic end bezels",d:"Pried away with a small flat tool. A hair dryer on the adhesive helps.",n:1},
   {k:"bracket",t:"Metal retaining bracket",d:"Pushed out once the bezels are off.",n:2},
   {k:"wheel",t:"Click wheel and its orange ribbon",d:"Unplug the ribbon from the logic board.",n:3,cable:1},
   {k:"jack",t:"Headphone jack board",d:"Two Phillips screws. Then push at the bottom of the click wheel to slide the whole assembly out.",n:4},
   {k:"logic",t:"Logic board",d:"The battery sits on it and plugs in at a plain connector. Pull the connector, never the wires."},
   {k:"batt",t:"Battery",d:"Plugs into the logic board."},
   {k:"mdrive",t:"Microdrive on its orange ribbon",d:"Do not unplug the drive cable at the logic-board end. One modder caused a Sad iPod that way.",cable:1}],
  open:["Pry the top and bottom plastic end bezels away from the aluminum body with a small flat tool, warming the adhesive with a hair dryer.","Push out the metal retaining bracket.","Unplug the orange click-wheel ribbon from the logic board.","Remove the two Phillips screws holding the headphone jack.","Push at the bottom of the click wheel to slide the internal assembly out."],
  tools:"Small flat driver, plastic picks, hair dryer, Phillips screwdriver",
  flash:["Of the iFlash family, only the iFlash SD-CF adapter fits the mini. The Solo, Dual, Quad and CF boards list the mini as not compatible.","A CompactFlash card in place of the Microdrive also works. One tester reported cards from 512MB to 32GB working, suggests iPod firmware 1.4.1 first, and warns against unplugging the drive cable at the logic-board end."],
  rbx:["Stable","Rockbox lists the iPod mini (1st and 2nd generation) with no major issues, and the install manual lists it as supported."],
  fail:[["Sad iPod icon","A dead Microdrive, or cracked solder joints at the drive connector. A CompactFlash swap is the usual cure."],["Short battery life","Replace the battery. EveryMac calls the job difficult but says no soldering is needed."],["Crackly jack","The headphone jack board has its own iFixit guide."]],
  parts:["iPod mini battery","iPod mini hard drive cable","iPod mini headphone jack board","iFlash SD-CF adapter"],
  gaps:["Pin counts for the ribbons.","Battery voltage.","Which of the 1st and 2nd generation boards need extra care."],
  src:[["iFixit: iPod Mini device page","https://www.ifixit.com/Device/iPod_Mini"],["iFixit: iPod Mini battery replacement (German)","https://www.ifixit.com/Guide/iPod+Mini+Akku+tauschen/411"],["iFixit: iPod Mini hard drive replacement (German)","https://www.ifixit.com/Guide/iPod+Mini+Festplatte+tauschen/412"],["The Apple Wiki: iPod mini (2nd generation)","https://theapplewiki.com/wiki/IPod_mini_(2nd_generation)"],["iPod mini CF mod notes (siber-sonic)","https://siber-sonic.com/mac/handhelds/iPodMiniCFmod.html"],["iPodWiki: SD-CF adapter","https://ipodwiki.com/wiki/SD-CF_Adapter"],["Apple: iPod mini tech specs","https://support.apple.com/112317"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"v5",n:"iPod video (5th generation)",yrs:"2005 to 2006",num:"A1136",blurb:"A plastic front clipped to a curved metal back. The battery and headphone jack stay with the back.",
  facts:[["Model","A1136. Released October 2005, 30GB and 60GB"],["Screen","2.5 inch, 320 x 240"],["Chip","PortalPlayer PP5021C. Audio codec Wolfson WM8758."],["Storage","1.8 inch Toshiba ATA-66 hard drive, 4,200 rpm, ZIF connector"],["Battery","Lithium-ion, 3.7 V. Sources disagree on the 30GB size (580 and 650 mAh). The 60GB takes an 850 mAh battery (iFixit 616-0232), thicker than the 30GB one, so they are not interchangeable."]],
  layers:[
   {k:"back",t:"Curved metal back with battery",d:"The battery is stuck to the back. Its orange ribbon ends in a brown latch connector that must be lifted straight up or it breaks.",n:1,cable:1},
   {k:"jack",t:"Headphone jack and hold switch",d:"Its own orange ribbon. The hold switch's plastic part may need moving to a new jack.",n:2,cable:1},
   {k:"drive",t:"Hard drive",d:"1.8 inch, ZIF."},
   {k:"frame",t:"Inner framework",d:"A separate iFixit guide."},
   {k:"logic",t:"Logic board",d:"A separate iFixit guide."},
   {k:"lcd",t:"Display",d:"2.5 inch color LCD."},
   {k:"front",t:"Plastic front with click wheel",d:"The click wheel is also its own guide."}],
  open:["Slide the hold switch to the locked position.","Free the clips along the bottom edge with an opening tool, keeping the tool edge against the metal back so the plastic front is not scratched.","Pry up both sides. iFixit counts four clips a side plus top and bottom.","Unplug the battery ribbon and the headphone-jack ribbon, then separate the halves."],
  tools:"iPod opening tool, angled tweezers, optional guitar pick",
  flash:["iFlash Solo, Dual, Quad and CF all list the 5th generation as a native fit. iFlash warns that a very large library can cause random resets, and that an SD card needs FAT32 or exFAT prepared first. After the swap, do a full restore in iTunes."],
  rbx:["Stable","Rockbox lists the iPod video as stable. It needs a FAT32 (Windows-format) iPod."],
  fail:[["Sad iPod icon, or a folder with an exclamation mark","iFixit staff say it usually means a drive problem. Charge it, reset it, try disk mode and reformat. Last, reseat the drive and battery."],["Same icon after a battery swap","A torn drive flex cable can do it."],["Short battery life","Replace the battery, and mind the brown latch connector."]],
  parts:["iPod video 5th generation battery","iPod video 5th generation headphone jack","iFlash Solo iPod video"],
  gaps:["The order the inside parts come out in.","Where the dock connector flex sits and how the display ribbon runs.","iFixit's difficulty and time rating."],
  src:[["iFixit: iPod 5th Generation (Video) battery replacement","https://www.ifixit.com/Guide/iPod+5th+Generation+%28Video%29+Battery+Replacement/603"],["iFixit: iPod 5th Generation (Video) guides","https://www.ifixit.com/Guide/iPod/iPod-5th-Generation-Video/95"],["iFixit parts: iPod 5th Generation (Video)","https://www.ifixit.com/it-it/Parts/iPod_5th_Generation_(Video)"],["iFixit answer: folder with exclamation icon","https://zh.ifixit.com/Answers/View/349782/Folder+with+exclamation+icon"],["iFixit answer: drive failure after battery replacement","https://ts.ifixit.com/Answers/View/386178/Hard+Drive+Failure+after+Battery+replacement"],["iFlash Solo","https://iflash.xyz/store/iflash-solo"],["iFlash tips and advice","https://www.iflash.xyz/helpful-tips-and-advice"],["The Apple Wiki: iPod with video","https://theapplewiki.com/wiki/IPod_with_video"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"v55",n:"iPod video (5.5 generation)",yrs:"2006 to 2007",num:"A1136, EMC 2065",blurb:"The 5th generation again, with a brighter screen and a search function. Opening and parts are the same.",
  facts:[["Model","A1136, EMC 2065. Introduced September 2006, 30GB and 80GB"],["Storage","Same 1.8 inch ZIF drive family as the 5th generation"],["Battery","30GB: the same disputed 580 to 650 mAh class as the 5th generation. 80GB: 850 mAh, iFixit part 616-0232."],["Differences","Brighter display, longer video playback, search"]],
  layers:[
   {k:"back",t:"Curved metal back with battery",d:"Same as the 5th generation.",n:1,cable:1},
   {k:"jack",t:"Headphone jack and hold switch",d:"Same as the 5th generation.",n:2,cable:1},
   {k:"drive",t:"Hard drive",d:"1.8 inch, ZIF."},
   {k:"frame",t:"Inner framework",d:"Separate iFixit guide."},
   {k:"logic",t:"Logic board",d:"Separate iFixit guide."},
   {k:"lcd",t:"Display",d:"Brighter than the 5th generation."},
   {k:"front",t:"Plastic front with click wheel",d:"Same as the 5th generation."}],
  open:["Same as the 5th generation: lock the hold switch, free the clips, unplug the battery and headphone-jack ribbons."],
  tools:"iPod opening tool, angled tweezers",
  flash:["iFlash Solo and Quad list the 5.5 generation 30GB and 80GB as a native fit. The 5th generation notes apply: prepare the card, restore in iTunes."],
  rbx:["Stable","Rockbox's iPod video config is shared by the 5th and 5.5 generations."],
  fail:[["Sad iPod icon, or a folder with an exclamation mark","Same as the 5th generation."]],
  parts:["iPod video 5.5 generation battery","iPod video 80GB battery 616-0232","iFlash Solo iPod video"],
  gaps:["Anything that differs from the 5th generation inside the case. iFixit's guides treat them alike, but we have not seen a side-by-side."],
  src:[["EveryMac: iPod 5th generation enhanced","https://everymac.com/systems/apple/ipod/specs/ipod-5th-generation-enhanced-specs.html"],["iFixit: iPod 5th Generation (Video) battery replacement","https://www.ifixit.com/Guide/iPod+5th+Generation+%28Video%29+Battery+Replacement/603"],["iFlash Solo","https://iflash.xyz/store/iflash-solo"],["The Apple Wiki: iPod with video","https://theapplewiki.com/wiki/IPod_with_video"],["Rockbox config for iPod video","https://git.lenord.me/len0rd/rockbox/src/branch/v3.3/firmware/export/config-ipodvideo.h"]]},
 {id:"n2",n:"iPod nano (2nd generation)",yrs:"2006 to 2007",num:"A1199",blurb:"An anodized aluminum bar with its flash memory soldered to the logic board. There is no storage to swap, but the battery can be.",
  facts:[["Model","A1199. 2GB, 4GB and 8GB. Launched September 2006"],["Chip","Samsung S5L8701, the first Samsung chip in an iPod"],["Screen","176 x 132 color LCD, about 1.5 inches"],["Storage","Samsung NAND flash on the logic board, not a module you can unplug"],["Battery","3.7 V lithium polymer, about 370 mAh by one teardown's estimate (another source says 400). It is soldered at three points."],["Codec","Wolfson WM8975 per The Apple Wiki and Rockbox. One teardown reads WM8750S, so we call it unsettled."]],
  layers:[
   {k:"bezel",t:"Top bezel (with hold switch)",d:"Pry it off with an opening tool in the seam against the metal body. Lock the hold switch first.",n:1},
   {k:"bezel",t:"Bottom bezel",d:"Same method. It surrounds the dock connector and headphone jack.",n:2},
   {k:"shell",t:"Aluminum body",d:"Screws come out, then the inside slides free.",n:3},
   {k:"wheel",t:"Click wheel and headphone jack",d:"One assembly joined by a fragile ribbon. Do not detach that ribbon all the way.",n:4,cable:1},
   {k:"logic",t:"Logic board with flash memory",d:"The LCD ribbon needs a metal bracket removed and a black retaining bar lifted. The dock connector has two Phillips #00 screws, one each side.",n:5,cable:1},
   {k:"batt",t:"Battery",d:"Soldered. iFixit's guide has you desolder three connections.",n:6}],
  open:["Lock the hold switch.","Pry the top bezel off with a plastic opening tool, then the bottom bezel the same way.","Remove the screws, then unplug the cable between the logic board and the click wheel and headphone-jack assembly.","Push the logic board assembly out. The click wheel and jack stay in the case."],
  tools:"Plastic opening tool, spudger, Phillips #00 and #000, tweezers, soldering iron for the battery",
  flash:["There is no flash swap. The memory is soldered on, and the only chip-swap project we found is for the 3rd generation nano."],
  rbx:["Supported","Rockbox lists the nano 1st and 2nd generations with no major issues. We could not read the install page, so check the live Rockbox wiki for the steps."],
  fail:[["Blank white screen","A recurring theme in iFixit's answers. A new display or logic board is the listed fix."],["Won't power on or charge","Battery."],["Click wheel or center button unresponsive","The click wheel is part of the case assembly on this model."],["Hold switch will not lock the buttons","iFixit has a hold-switch cable guide."]],
  parts:["iPod nano 2nd generation battery","iPod nano 2nd generation color display","iPod nano 2nd generation top bezel hold switch"],
  gaps:["What the click wheel fix really is: the threads we read had no answers.","How to reconnect the click wheel and jack assembly. iFixit's teardown only shows taking it apart.","iFixit's difficulty and time ratings for the teardown and the battery."],
  src:[["iFixit: iPod Nano 2nd Generation teardown","https://www.ifixit.com/Teardown/iPod+Nano+2nd+Generation+Teardown/592"],["iFixit: iPod Nano 2nd Generation guides","https://www.ifixit.com/c/iPod_Nano_2nd_Generation"],["iFixit parts: iPod Nano","https://www.ifixit.com/Parts/iPod_Nano"],["iFixit: nano 2nd gen battery guide","https://ts.ifixit.com/Guide/edit/422/1830"],["Teardown of the 2nd gen nano (GlobalSpec)","https://electronics360.globalspec.com/article/3603/apple-ipod-nano-2nd-generation-4gb-teardown"],["The Apple Wiki: iPod nano (2nd generation)","https://theapplewiki.com/wiki/IPod_nano_(2nd_generation)"],["Rockbox config for the nano 2G","https://git.lenord.me/devs/foxbox/src/branch/master/firmware/export/config/ipodnano2g.h"],["Rockbox target status (mirror)","https://backiee.wasmer.app/http_www_rockbox_org/wiki/TargetStatus"]]},
 {id:"c6",n:"iPod classic, 2007 and 2008 (6th generation)",yrs:"2007 to 2008",num:"A1238",blurb:"A metal front and metal back held by 13 clips. iFixit rates the opening Very High. Every iPod classic shares the model number A1238.",
  facts:[["Model","A1238, EMC 2173. The 2007 80GB and 160GB (thick), and the 2008 120GB"],["Naming","Sources disagree on what 6th and 7th generation mean. Apple lists them by year and size, so we do too."],["Chip","Samsung S5L8702, 64 MiB RAM, Cirrus Logic CS42L55 codec"],["Storage","1.8 inch Toshiba ZIF hard drive, 4,200 rpm, ATA-66, in rubber brackets and foam"],["Battery","Lithium-ion, 3.7 V. Thin models take 650 mAh (iFixit 616-0229). The 160GB thick model takes 850 mAh (616-0232)."],["Ratings","Apple rates the 120GB at 36 hours of audio and 6 hours of video"]],
  layers:[
   {k:"back",t:"Metal back",d:"Joined to the front by 13 metal clips. Two ribbons cross over: the battery ribbon (orange) and the headphone-jack ribbon.",n:1,cable:1},
   {k:"drive",t:"Hard drive",d:"Sits in rubber brackets and foam. Reuse them on the new drive.",n:2},
   {k:"frame",t:"Front metal framework",d:"Holds the next layers.",n:3},
   {k:"lcd",t:"Display and its backplate",d:"The LCD ribbon comes off before the logic board lifts out.",n:4,cable:1},
   {k:"logic",t:"Logic board",d:"Click-wheel ribbon plugs in here with a locking tab that turns 90 degrees.",n:5,cable:1},
   {k:"wheel",t:"Click wheel assembly",d:"Last. iFixit's click-wheel guide runs to 38 steps, and users report around 45 minutes to an hour.",n:6}],
  open:["Use several plastic opening tools along the seam (they break), then a metal spudger and a thin metal spatula to release the 13 clips around both sides.","Unplug the battery ribbon and the headphone-jack ribbon that join the back to the front.","Lift the back away, then work through the layers in order."],
  tools:"Plastic opening tools, metal spudger, metal spatula, putty knife, Phillips screwdriver",
  flash:["iFlash Solo, Dual, Quad and Sata list the 80GB, 120GB and 160GB classics as a fit. For the 6th generation, iFlash says the limit is 128GB on stock firmware, because of how the original firmware addresses the disk.","The 160GB thick model needs the extra iFlash HDD ribbon.","Restore the iPod in iTunes (DFU mode) after the swap. A red X afterward means no talking to the drive, so check the ribbon. A very large SSD can draw enough power to trigger a low-power Sad iPod, so keep the battery above 20 percent."],
  rbx:["Stable","Rockbox's own page calls the classic port stable, with nearly everything working and strong battery life. Rockbox Utility installs it, and the original firmware stays available through a dual-boot bootloader."],
  fail:[["Clicking or dead drive","Replace the drive or fit a flash adapter."],["Folder with an exclamation mark","Often the drive. A torn drive flex while opening can cause it, so open carefully."],["Short battery life","Replace the battery. A putty knife helps, and the thick battery guide recommends calibrating afterward."]],
  parts:["iPod classic battery 616-0229","iPod classic thick battery 616-0232","iFlash Solo iPod classic","iFlash Quad iPod classic","iPod classic hard drive ribbon"],
  gaps:["Where the battery sits in the stack, and how the dock connector flex runs.","Original drive part numbers.","Whether a codec or op-amp swap exists for the Cirrus parts. We found none documented."],
  src:[["iFixit: iPod Classic Hard Drive Replacement","https://ru.ifixit.com/Guide/iPod+Classic+Hard+Drive+Replacement/564"],["iFixit: iPod Classic Click Wheel Replacement","https://www.ifixit.com/Guide/iPod+Classic+Click+Wheel+Replacement/571"],["iFixit parts: iPod Classic","https://www.ifixit.com/Parts/iPod_Classic"],["iFixit: classic thick battery","https://www.ifixit.com/products/ipod-classic-thick-replacement-battery"],["iFixit answer: classic upgrade limits","https://zh.ifixit.com/Answers/View/397430/What+are+the+upgrade+limits+of+each+generation+of+the+iPod+classic"],["Apple: iPod classic (120GB) specs","https://support.apple.com/en-gb/112321"],["EveryMac: iPod classic","https://everymac.com/systems/apple/ipod/specs/ipod-classic-6th-generation-specs.html"],["The Apple Wiki: iPod classic (6th generation)","https://theapplewiki.com/wiki/IPod_classic_(6th_generation)"],["iFlash Solo","https://iflash.xyz/store/iflash-solo"],["iFlash tips and advice","https://www.iflash.xyz/helpful-tips-and-advice"],["Rockbox: iPod classic port","https://www.rockbox.org/wiki/IpodClassicPort"]]},
 {id:"c7",n:"iPod classic, 2009 (7th generation)",yrs:"2009 to 2014",num:"A1238",blurb:"The last click wheel iPod. Inside it is the same as the 2007 and 2008 classics, in a single 10.5 mm case.",
  facts:[["Model","A1238, EMC 2173. Introduced September 2009, discontinued September 2014"],["Case","Single-platter, 10.5 mm thin"],["Storage","1.8 inch ZIF hard drive, same as the 6th generation"],["Battery","Thin, 650 mAh, iFixit part 616-0229"],["Firmware","Not interchangeable between revisions, even though the drives are electrically the same"],["Ratings","Apple rates it at 36 hours of audio and 6 hours of video"]],
  layers:[
   {k:"back",t:"Metal back",d:"Same 13-clip case as the other classics. Battery and headphone-jack ribbons cross over.",n:1,cable:1},
   {k:"drive",t:"Hard drive",d:"Rubber brackets and foam.",n:2},
   {k:"frame",t:"Front metal framework",d:"",n:3},
   {k:"lcd",t:"Display and its backplate",d:"",n:4,cable:1},
   {k:"logic",t:"Logic board",d:"",n:5,cable:1},
   {k:"wheel",t:"Click wheel assembly",d:"",n:6}],
  open:["Same as the 2007 and 2008 classic: 13 clips, several plastic tools, a metal spudger and a spatula."],
  tools:"Plastic opening tools, metal spudger, metal spatula, putty knife, Phillips screwdriver",
  flash:["iFlash Solo, Dual and Quad list the late 2009 160GB classic as a native fit. iFlash's tips give 256GB to 1TB through the Dual or Quad. iFixit's community answers say about 2TB is the theoretical limit and 512GB a safe one. Treat these as reports, not guarantees."],
  rbx:["Stable","Rockbox's classic port covers the 6th and 7th generation classics."],
  fail:[["Same as the 2007 and 2008 classic.",""]],
  parts:["iPod classic 160GB battery 616-0229","iFlash Solo iPod classic","iFlash Quad iPod classic"],
  gaps:["The exact codec part. Apple Wiki says the classics moved from Wolfson to Cirrus Logic CS42L5x parts.","Whether the motherboards swap between classic years. One iFlash page says so, but we saw no second source."],
  src:[["Apple: iPod classic 160GB specs","https://support.apple.com/en-ca/112601"],["The Apple Wiki: iPod classic (6th generation)","https://theapplewiki.com/wiki/IPod_classic_(6th_generation)"],["iFixit parts: iPod Classic","https://www.ifixit.com/Parts/iPod_Classic"],["iFlash Solo","https://iflash.xyz/store/iflash-solo"],["iFlash and the iPod classic","https://iflash.xyz/apple-ipod-classic-and-iflash"],["Rockbox: iPod classic port","https://www.rockbox.org/wiki/IpodClassicPort"]]}
 ],
 mods:[
  {id:"flash",n:"Flash storage swap",fits:["g3","g4","ph","mn","v5","v55","c6","c7"],d:"Replace the spinning drive with a memory card or an SSD. It is silent, runs cooler and wakes faster. Which board you need depends on the model, so check the model page.",src:[["iFlash","https://www.iflash.xyz/"]]},
  {id:"batt",n:"New battery",fits:["g3","g4","ph","mn","v5","v55","n2","c6","c7"],d:"The cheapest fix for a short day. Match the capacity to your exact model and size, because the 60GB and 80GB video and the thick classic take a thicker battery.",src:[["iFixit parts: iPod batteries","https://www.ifixit.com/Parts/iPod/Batteries"]]},
  {id:"batx",n:"Extended battery and thick back",fits:["v5","v55","c6","c7"],d:"Third-party cells of 1,800 to 3,000 mAh are sold for the video and classic. iFlash notes the real capacity is often 10 to 20 percent below the claim, and the bigger cells need a thick back. A 3,000 mAh cell can foul the headphone-jack assembly.",src:[["iFlash: extended battery guide","https://www.iflash.xyz/3rd-party-extended-battery-guide/"]]},
  {id:"usbc",n:"USB-C, Bluetooth and wireless charging",fits:["v5","v55","c6","c7"],d:"Kits from Moonlit Market and Boxy Pixel add Bluetooth audio and USB-C. Press reports disagree on which iPods the Moonlit Market kit fits (5th generation only, 5th and 5.5, or 5th to 7th). The Boxy Pixel board fits 5th to 7th generation, but only inside Boxy Pixel's own housings, charges only, and spoils the battery indicator.",src:[["Boxy Pixel MKII electronics PCB","https://www.boxypixel.com/products/ipod-mkii-electronics-pcb"],["ifun.de: Classic Connect 2","https://www.ifun.de/classic-connect-2-bluetooth-qi-und-usb-c-fuer-den-ipod-classic-277730/"],["TechEBlog: iPod classic mod kit","https://www.techeblog.com/ipod-classic-mod-kit-modern-upgrade/"]]},
  {id:"amp",n:"Audio capacitor upgrade",fits:["v5","v55"],d:"iFlash sells a kit that swaps the output coupling capacitors for two ELNA Silmic II parts, documented for the Wolfson-codec 5th and 5.5 generation. It needs fine soldering and the vendor takes no returns. We found no documented equivalent for the classic.",src:[["iFlash audio capacitor kit","https://www.iflash.xyz/store/audio-capacitor-bypass-kit/"],["iFlash diyMod write-up","https://www.iflash.xyz/modding-audiophile-meets-ipod-diymod/"]]},
  {id:"jack",n:"New headphone jack and hold switch",fits:["g4","ph","mn","v5","v55"],d:"For a crackly jack or a stuck hold slider. On the video the hold switch's plastic part may need moving to the new jack.",src:[["iFixit guides","https://www.ifixit.com/Device/iPod"]]},
  {id:"wheel",n:"Click wheel replacement",fits:["g4","ph","mn","v5","v55","c6","c7"],d:"For a wheel that skips or goes dead. On the classic it is the last layer of the stack and a long job.",src:[["iFixit: iPod Classic Click Wheel Replacement","https://www.ifixit.com/Guide/iPod+Classic+Click+Wheel+Replacement/571"]]},
  {id:"rock",n:"Rockbox firmware, dual boot",fits:["g3","g4","ph","mn","v5","v55","n2","c6","c7"],d:"Open-source firmware that plays FLAC, Opus and more. The original software stays one boot away. Non-classic models need the iPod formatted as FAT32.",src:[["Rockbox","https://www.rockbox.org/"],["Rockbox install manual (mirror)","https://git.lenord.me/devs/foxbox/src/commit/e86fd3fbdbd973a044b21dcf3ee00061560e923f/manual/getting_started/ipod_install.tex"]]}
 ]
};
