/* pages.js: the one list of everything you can visit in the museum, by section.
   The top menu, the section pages (#/hub/...), the All pages finder (#/more), Search and the C:\> prompt all read this list,
   so adding a page means adding one line here. Tile: [link, name, one-line description, icon, optional search words].
   A "--" row starts a new group of tiles. Web pages that live outside the app (/guides/ and friends) are plain links. */
var SITE=[
 {id:"explore",t:"Explore",d:"Learn your way around 1975 to 2012.",i:[
  ["--","Look at a year"],["#/era/1995","Era mode","Pick a year and the site changes its look.","clock","theme style decade"],["#/walk/1995","Walk through a year","A guided tour of one year: news, hardware, games, the ad.","clock","tour guided"],["#/day","What was happening","Any date: the news, the hardware, the games.","sun","on this day calendar"],["#/zoom","Zoom timeline","Drag across 1975 to 2012 in six lanes.","globe","drag scroll lanes"],["#/tours","Guided tours","Walk the timeline one stop at a time.","flag","story"],
  ["--","Machines and games"],["#/runs","Does it run?","Pick a machine or a game and see what works with what.","chip","compatibility"],["#/rigs","Dream rig","Wire up a PC and fight the IRQ conflicts.","chip","irq build"],["#/bench","Benchmark wall","Real results from the machines, ranked.","trophy","speed score"],["#/explore","Spec Explorer","Filter everything, then compare up to four.","chip","compare filter specs"],
  ["--","The museum in numbers"],["#/maker","Makers","Every company with something in the museum, and what else they built.","gear","companies brands"],["#/stats","Museum stats","The numbers about the whole museum.","bulb","charts counts"],["#/scale","The 640K scale","How much of the 640K every item leaves free.","bulb","score memory"],["#/mem","Memory map","The 1 megabyte memory map, drawn out.","chip","upper memory ram"],["#/report","Collection report","A printable snapshot of the whole collection, for your records.","box","insurance print pdf csv"]]},
 {id:"read",t:"Read",d:"Books, guides and the written word.",i:[
  ["--","Books and guides"],["#/books","The Bookshelf","Books on computer and game history, with where to find a copy.","book","reading audiobook shelf kushner williams koster"],["/guides/","Buyer guides","What gear is worth buying, how to fix a dead vintage computer, how to play old games today.","gear","gear tools soldering repair buy"],["#/manuals","Manuals and references","Every manual and reference the museum links to.","book","pdf documentation"],["#/quotes","Quotes","Things people said about computers, then.","heart","sayings"],
  ["--","Notes from the bench"],["#/journal","Repair journal","What got fixed, what parts it took and how long.","gear","fix log repairs"],
  ["--","On the web, for sharing and searching"],["/history/","Timeline pages","Every timeline entry as its own page, built for sharing.","clock","history static share"],["/museum/","Exhibit pages","Every museum item as its own web page.","box","static share"],["/books/","The Bookshelf, as a web page","The same shelf as a plain page you can share.","book","static share"]]},
 {id:"play",t:"Play",d:"Games, things to make, and things to watch.",i:[
  ["--","Every day"],["#/daily","Daily Dig","A new puzzle every morning.","bulb","streak trivia"],["#/bingo","Retro Bingo","Cross off the squares.","star","card"],
  ["--","Games"],["#/play","All the games","Trivia, Higher or Lower, Timeline Sort, Mystery Photo.","ghost","arcade puzzles"],["#/higher","Higher or Lower","Which launch price was bigger?","coin","price"],["#/sort","Timeline Sort","Put five finds in order, oldest first.","clock","order"],["#/mystery","Mystery Photo","Name the blurry photo before it comes into focus.","camera","guess"],["#/hangman","Disk Error Hangman","Guess the machine.","ghost","word"],["#/build/1996","Rig challenge","Pick a year, spend your points, and run the era\u2019s real games.","chip","build"],["#/maze","The Basement","Staff only. Find your way out.","floppy","maze memory"],
  ["--","Make something"],["#/adlab","Ad Lab","Make a retro tribute ad for any item, with stickers, and download it.","news","poster design png"],
  ["--","Watch and listen"],["#/theater","Retro Theater","A little CRT TV for videos.","tv","video youtube watch"],["#/jukebox","Jukebox","Chiptunes through four kinds of sound card.","speaker","music midi sound"],
  ["--","Show-off screens"],["#/kiosk","Demo kiosk","Attract mode for a spare screen, like a demo station in a toy-store aisle. Scenes and slides are made fresh from the whole museum.","tv","attract mode demo screensaver display fullscreen idle store"],["#/animations","Animation library","Every move Connie and her family can make, and a scene composer for any timeline entry.","star","animate scene composer pixel"]]},
 {id:"connie",t:"Connie",d:"Connie Ventional and her family.",i:[
  ["--","Meet them"],["#/connie","Meet Connie","Her story, her file and the whole family.","heart","mascot family story"],["#/cards","Trading Cards","Every Ventional on a card. Connie is the holofoil.","star","collect"],["#/stickers","Sticker sheet","Print stickers for your laptop.","star","print"],["#/funnies","The Sunday Funnies","Strips and gags about Connie and her family, plus a fresh strip made from the timeline every time.","star","comic cartoon"],
  ["--","Dress up and earn"],["#/closet","Connie\u2019s closet","Pick her look, accessory and color.","heart","outfits dress"],["#/prizes","Prize counter","Trade game tickets for stickers, colors, looks and accessories.","gem","tickets rewards"],["#/memman","Memory Manager","Fit the game into 640K by editing CONFIG.SYS. Earn stars, unlock looks.","chip","config.sys puzzle"],
  ["--","Take her home"],["#/shop","The Mall (under construction)","Stickers, cards, pins, plush and custom iPods. A mock-up for now.","flag","shop store merch buy"]]},
 {id:"stuff",t:"My stuff",d:"Things saved on this device.",i:[
  ["--","My lists"],["#/mine","My collection","Own, want and trade lists, with value.","box","inventory"],["#/wish","Wish list","Circle things in the catalog, write a Dear Santa letter, share a link.","heart","santa"],
  ["--","Progress"],["#/trophies","Trophy room","Your XP, level and badges.","star","achievements"],
  ["--","This device"],["#/backup","Back up my stuff","Save everything to a file, or restore it on another device.","floppy","export import save"],["#/install","Install and offline","Keep the museum on your device, add a daily reminder, print spec sheets.","floppy","app pwa offline"]]},
 {id:"community",t:"Community",d:"Meet the crew, help the museum and follow along.",i:[
  ["#/about","About","Meet Matt and Tony, and why it is called Conventional Memory.","heart","brothers who"],["#/start","Start here","Seven ways in, depending on your mood.","flag","new visitor"],["#/community","Share or fix","Share a memory or report a mistake.","heart","submit correction"],["#/wanted","Wanted","Hardware and software the museum is hunting for. Have one? Tell me.","flag","donate"],["#/follow","Follow","New items and videos on four platforms.","tv","tiktok youtube instagram facebook social"],["#/changes","Recent changes","What was added or corrected, and when.","clock","news updates"],["#/disclosure","Affiliate disclosure","How the links on this site work.","flag","amazon ebay"]]}];
/* the hub "watch" used to be its own menu; it now lives in Play, and the old address still works */
var HUB_ALIAS={watch:"play",theater:"play"};
/* extra pages that are not tiles anywhere else: [link, name, description, search words] */
var PAGE_EXTRA=[["#/catalog","Catalog","Every exhibit: departments, aisles, shelf and search.","catalog items browse wish book aisles"],["#/timeline","Timeline","1975 to 2012, hardware, software, games, books and movies.","timeline history years"],["#/search","Search","Items, hardware, games and pages. Press / anywhere.","find"],["#/more","All pages","Every page and feature, in one list.","site map menu index"],["#/catalog?compare","Compare two items","Open any item and press Compare, or use the Spec Explorer to compare up to four.","versus"]];
/* every page, once: [link, name, description, section id, search text] */
function allPages(){var out=[],seen={};function add(h,t,d,sec,k){if(seen[h])return;seen[h]=1;out.push({h:h,t:t,d:d,s:sec,k:(t+" "+d+" "+(k||"")+" "+sec).toLowerCase()})}
 PAGE_EXTRA.forEach(function(x){if(x[0].indexOf("?")<0)add(x[0],x[1],x[2],"site",x[3])});
 SITE.forEach(function(g){g.i.forEach(function(x){if(x[0]!=="--")add(x[0],x[1],x[2],g.id,x[4])})});return out}
/* the best pages for a typed word or two, best first */
function findPages(q,max){q=String(q||"").toLowerCase().replace(/[^a-z0-9. ]+/g," ").replace(/^\s+|\s+$/g,"");if(!q)return[];var w=q.split(/\s+/),sc=[];
 allPages().forEach(function(p){var s=0,nm=p.t.toLowerCase();if(w.every(function(x){return p.k.indexOf(x)>=0})){s=1;if(nm===q)s+=50;else if(nm.indexOf(q)===0)s+=30;else if(nm.indexOf(q)>=0)s+=20;w.forEach(function(x){if(nm.indexOf(x)>=0)s+=4})}if(s)sc.push([s,p])});
 sc.sort(function(a,b){return b[0]-a[0]});return sc.slice(0,max||8).map(function(x){return x[1]})}
