// Quotes for ConventionalMemory.io. Format: [text, attribution]
// Sections: (1) attributed quotes, (2) error messages and boot text, (3) tech proverbs and folk sayings,
// (4) original lines in the museum's voice, credited to "Conventional Memory".
// Where a famous line is widely attributed but disputed, the attribution says so.
var QUOTES=[
// ---- 1. Attributed quotes ----
["The best way to predict the future is to invent it.","Alan Kay"],
["Premature optimization is the root of all evil.","Donald Knuth"],
["Talk is cheap. Show me the code.","Linus Torvalds"],
["Simplicity is prerequisite for reliability.","Edsger W. Dijkstra"],
["Debugging is twice as hard as writing the code in the first place.","Brian Kernighan"],
["Any sufficiently advanced technology is indistinguishable from magic.","Arthur C. Clarke"],
["Don't Panic.","Douglas Adams"],
["I love deadlines. I love the whooshing noise they make as they go by.","attributed to Douglas Adams (widely quoted, original source unclear)"],
["We are stuck with technology when what we really want is just stuff that works.","Douglas Adams"],
["Technology is a word that describes something that doesn't work yet.","attributed to Douglas Adams"],
["Never trust a computer you can't throw out a window.","Steve Wozniak"],
["Stay hungry. Stay foolish.","Steve Jobs, quoting the Whole Earth Catalog"],
["Design is not just what it looks like and feels like. Design is how it works.","Steve Jobs"],
["The only way to do great work is to love what you do.","Steve Jobs"],
["The most dangerous phrase in the language is 'We've always done it this way.'","Grace Hopper"],
["It's easier to ask forgiveness than it is to get permission.","attributed to Grace Hopper"],
["A ship in port is safe, but that's not what ships are built for.","attributed to Grace Hopper"],
["We can only see a short distance ahead, but we can see plenty there that needs to be done.","Alan Turing"],
["Beware of bugs in the above code; I have only proved it correct, not tried it.","Donald Knuth"],
["Science is what we understand well enough to explain to a computer. Art is everything else we do.","Donald Knuth"],
["Computer science is no more about computers than astronomy is about telescopes.","attributed to Edsger W. Dijkstra, almost certainly not first formulated by him"],
["Program testing can be used to show the presence of bugs, but never to show their absence.","Edsger W. Dijkstra"],
["Measuring programming progress by lines of code is like measuring aircraft building progress by weight.","attributed to Bill Gates"],
["640K ought to be enough for anybody.","attributed to Bill Gates, 1981. He has said he never said it."],
["There is no reason for any individual to have a computer in his home.","Ken Olsen, 1977 (context disputed)"],
["I think there is a world market for maybe five computers.","attributed to Thomas Watson (probably apocryphal)"],
["Everything that can be invented has been invented.","attributed to Charles H. Duell, 1899 (almost certainly apocryphal)"],
["Computers in the future may weigh no more than 1.5 tons.","Popular Mechanics, 1949"],
["There's more than one way to do it.","Larry Wall"],
["Software is getting slower more rapidly than hardware becomes faster.","Niklaus Wirth"],
["It always takes longer than you expect, even when you take into account Hofstadter's Law.","Douglas Hofstadter"],
["Anything that can go wrong will go wrong.","Murphy's Law"],
["Never underestimate the bandwidth of a station wagon full of tapes hurtling down the highway.","Andrew Tanenbaum"],
["The nice thing about standards is that you have so many to choose from.","Andrew Tanenbaum"],
["Those who cannot remember the past are condemned to repeat it.","George Santayana"],
["The past is never dead. It's not even past.","William Faulkner"],
["The past is a foreign country; they do things differently there.","L. P. Hartley"],
["What's past is prologue.","William Shakespeare"],
["There is nothing new under the sun.","Ecclesiastes 1:9"],
["Simplify, simplify.","Henry David Thoreau"],
["Genius is one percent inspiration, ninety-nine percent perspiration.","Thomas Edison"],
["I have not failed. I've just found 10,000 ways that won't work.","attributed to Thomas Edison"],
["The future is already here. It's just not evenly distributed.","William Gibson"],
["The medium is the message.","Marshall McLuhan"],
["A good game is a series of interesting choices.","Sid Meier"],
["A delayed game is eventually good, but a rushed game is forever bad.","Often attributed to Shigeru Miyamoto; a similar line is traced to Siobhan Beeman (GDC 1996)"],
["All the best games are easy to learn and difficult to master.","Nolan Bushnell"],
["Focus is a matter of deciding what things you're not going to do.","John Carmack"],
["Adding manpower to a late software project makes it later.","Fred Brooks"],
["Given enough eyeballs, all bugs are shallow.","Eric S. Raymond"],
["There are only two kinds of languages: the ones people complain about and the ones nobody uses.","Bjarne Stroustrup"],
["A distributed system is one in which the failure of a computer you didn't even know existed can render your own computer unusable.","Leslie Lamport"],
["A complex system that works is invariably found to have evolved from a simple system that worked.","John Gall"],
["A generation which ignores history has no past and no future.","Robert A. Heinlein"],
["Who controls the past controls the future.","George Orwell"],
["The details are not the details. They make the design.","Charles Eames"],
["Good design is as little design as possible.","Dieter Rams"],
["If you were plowing a field, which would you rather use: two strong oxen or 1,024 chickens?","Seymour Cray"],
["A language that doesn't affect the way you think about programming is not worth knowing.","Alan Perlis"],
["Everything should be built top-down, except the first time.","Alan Perlis"],
["When in doubt, use brute force.","Ken Thompson"],
["The first 90 percent of the code accounts for the first 90 percent of the development time. The remaining 10 percent of the code accounts for the other 90 percent of the development time.","Tom Cargill, Bell Labs (the ninety-ninety rule, popularised by Jon Bentley, 1985)"],
["Simplicity is complicated.","Rob Pike"],
["Nothing great was ever achieved without enthusiasm.","Ralph Waldo Emerson"],
["An investment in knowledge pays the best interest.","attributed to Benjamin Franklin"],
["The report of my death was an exaggeration.","Mark Twain"],
["If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.","Gerald Weinberg"],
["The Analytical Engine has no pretensions whatever to originate anything.","Ada Lovelace"],
["Software is eating the world.","Marc Andreessen"],
["Make it work, make it right, make it fast.","attributed to Kent Beck"],
["Any fool can write code that a computer can understand. Good programmers write code that humans can understand.","Martin Fowler"],
["Walking on water and developing software from a specification are easy if both are frozen.","Edward V. Berard"],
["The only way to learn a new programming language is by writing programs in it.","Dennis Ritchie"],
["Computers are useless. They can only give you answers.","attributed to Pablo Picasso"],
["First, solve the problem. Then, write the code.","John Johnson"],
["Some people, when confronted with a problem, think 'I know, I'll use regular expressions.' Now they have two problems.","Jamie Zawinski"],
["The cheapest, fastest, and most reliable components are those that aren't there.","Gordon Bell"],
["The computer was born to solve problems that did not exist before.","attributed to Bill Gates"],
["Quality is more important than quantity. One home run is much better than two doubles.","attributed to Steve Jobs"],
["Innovation distinguishes between a leader and a follower.","attributed to Steve Jobs"],

// ---- 2. Error messages and boot text ----
["Bad command or file name","MS-DOS"],
["Abort, Retry, Fail?","MS-DOS"],
["Press any key to continue . . .","MS-DOS"],
["Insert disk with batch file","MS-DOS"],
["Non-System disk or disk error. Replace and strike any key when ready","MS-DOS boot message"],
["Missing operating system","PC BIOS"],
["Invalid drive specification","MS-DOS"],
["Divide overflow","MS-DOS"],
["Insufficient memory","MS-DOS"],
["Out of environment space","MS-DOS"],
["Program too big to fit in memory","MS-DOS"],
["Packed file is corrupt","MS-DOS"],
["Internal stack overflow, system halted","MS-DOS"],
["Bad or missing Command Interpreter","MS-DOS"],
["Sector not found reading drive C","MS-DOS"],
["General failure reading drive A","MS-DOS"],
["Not ready reading drive A","MS-DOS"],
["Write protect error writing drive A","MS-DOS"],
["Please insert the last disk of the volume set","MS-DOS"],
["Incorrect DOS version","MS-DOS"],
["Too many open files","MS-DOS"],
["Access denied","MS-DOS"],
["File not found","MS-DOS"],
["Path not found","MS-DOS"],
["Enter current date (mm-dd-yy):","MS-DOS"],
["Starting MS-DOS...","MS-DOS 6"],
["Starting Windows 95...","Windows 95"],
["Type EXIT to return to Windows","Windows 95"],
["This program cannot be run in DOS mode.","Windows executable stub"],
["This program requires Microsoft Windows.","Windows 3.x"],
["This program has performed an illegal operation and will be shut down.","Windows 95 and 98"],
["A fatal exception 0E has occurred. The current application will be terminated.","Windows 9x"],
["Windows protection error. You need to restart your computer.","Windows 9x"],
["It is now safe to turn off your computer.","Windows 95 and 98"],
["Keyboard error or no keyboard present. Press F1 to continue.","PC BIOS"],
["Press F1 to continue, DEL to enter SETUP","PC BIOS"],
["640K OK","PC BIOS memory test"],
["Memory allocation error. Cannot load COMMAND, system halted","MS-DOS"],
["Volume in drive C has no label","MS-DOS"],

// ---- 3. Tech proverbs and folk sayings ----
["It works on my machine.","programmer proverb"],
["There's no place like 127.0.0.1.","tech proverb"],
["If it ain't broke, don't fix it.","proverb"],
["Nothing is more permanent than a temporary fix.","tech proverb"],
["Data expands to fill the space available for storage.","Parkinson's Law of Data"],
["Work expands so as to fill the time available for its completion.","C. Northcote Parkinson"],
["The number of transistors on a chip doubles about every two years.","Moore's Law, paraphrased"],
["What Intel giveth, Microsoft taketh away.","Andy and Bill's Law"],
["Fast, cheap, good: pick two.","project management proverb"],
["If at first you don't succeed, blow into the cartridge.","every kid with a Nintendo"],
["When all else fails, read the manual.","tech proverb"],
["Save early. Save often.","gamer's proverb"],
["All your base are belong to us.","Zero Wing, 1991"],
["Be kind, rewind.","video store, 1990s"],
["Don't copy that floppy.","anti-piracy campaign, 1992"],
["There are 10 types of people in the world: those who understand binary and those who don't.","programmer joke"],
["The best thing about a boolean is that even if you are wrong, you are only off by a bit.","programmer joke"],
["There is no cloud. It's just someone else's computer.","tech proverb"],
["Hardware: the part of a computer that you can kick.","tech proverb"],
["Electronics run on magic smoke. Once the smoke escapes, they stop working.","electronics folklore"],
["Weeks of coding can save you hours of planning.","programmer joke"],
["It's not a bug, it's a feature.","tech proverb"],
["In theory, there is no difference between theory and practice. In practice, there is.","engineering proverb"],
["Read the manual. Then read it again, slowly.","tech proverb"],
["Have you tried turning it off and on again? Give it ten seconds first.","tech support proverb"],
["Insert coin to continue.","arcade cabinet"],
["Your mileage may vary.","software license, everywhere"],
["Batteries not included.","toy box, forever"],
["Assembly required.","furniture, and also retro computers"],
["Do not remove the floppy while the light is on.","computer lab sign"],

// ---- 4. In the museum's voice ----
["Every machine in this museum has a story. Some of them even boot.","Conventional Memory"],
["A capacitor is just a tiny bomb with a datasheet.","Conventional Memory"],
["Beige is not a color. It is a decade.","Conventional Memory"],
["The floppy disk: 1.44 megabytes of hope and zero bytes of certainty.","Conventional Memory"],
["Never say a machine is dead. Say it is between owners.","Conventional Memory"],
["If it beeps at boot, it's talking. Listen.","Conventional Memory"],
["Some collectors chase rarity. I chase the sound of a hard drive spinning up.","Conventional Memory"],
["Preservation is procrastination with a better cause.","Conventional Memory"],
["There is no such thing as too many jumper blocks.","Conventional Memory"],
["IRQ 5 is a lie we all agreed to believe.","Conventional Memory"],
["Somewhere out there, a Sound Blaster is fighting your network card for IRQ 5.","Conventional Memory"],
["SET BLASTER=A220 I5 D1 T4 is the most beautiful line ever typed.","Conventional Memory"],
["If you know your IRQ and DMA by heart, you are one of us.","Conventional Memory"],
["The best part of a new-to-me machine is the smell. The second best part is the boot chime.","Conventional Memory"],
["Each dial-up handshake was a tiny miracle set to noise.","Conventional Memory"],
["640K was never enough, but it was always ours.","Conventional Memory"],
["In this house, we load high.","Conventional Memory"],
["Conventional memory: where every kilobyte had a name and a fight.","Conventional Memory"],
["If your CONFIG.SYS is elegant, your soul is in order.","Conventional Memory"],
["AUTOEXEC.BAT is a diary written in commands.","Conventional Memory"],
["Every boot disk is a small act of faith.","Conventional Memory"],
["A screen that flickers is a screen with personality.","Conventional Memory"],
["Turning it off and on again works because it is the oldest spell we know.","Conventional Memory"],
["A shoebox of cables is a museum's most honest archive.","Conventional Memory"],
["The mouse ball was the original cookie: it collected everything.","Conventional Memory"],
["Cleaning a mouse ball is the closest thing computing has to gardening.","Conventional Memory"],
["Somewhere, a 5.25-inch disk is still safe in its sleeve, waiting.","Conventional Memory"],
["Label your disks. Future you has no memory of the last ten years.","Conventional Memory"],
["The sweetest sound in retro computing is a POST beep that means everything is fine.","Conventional Memory"],
["Behind every great collection is a very patient household.","Conventional Memory"],
["A museum is just a hoard with a mission statement.","Conventional Memory"],
["I don't collect old computers. I adopt them.","Conventional Memory"],
["If it has a power supply, it has a story.","Conventional Memory"],
["The best repair tool is patience. The second best is a good magnifier.","Conventional Memory"],
["Recapping: because thirty years is long enough for any electrolytic.","Conventional Memory"],
["Solder fumes and CRT glow: the perfumes of the golden age.","Conventional Memory"],
["Measure twice, desolder once.","Conventional Memory"],
["Tin your iron. Trust your multimeter. Question everything else.","Conventional Memory"],
["Warm up an old CRT the way you would warm up an old engine.","Conventional Memory"],
["A dead battery is a story of neglect. A leaking one is a story of consequences.","Conventional Memory"],
["The CMOS battery has one job. It picks the worst day to quit.","Conventional Memory"],
["Not all heroes wear capes. Some wear anti-static wrist straps.","Conventional Memory"],
["Static electricity: the original data loss event.","Conventional Memory"],
["Compressed air, isopropyl alcohol, and a little hope.","Conventional Memory"],
["Yellowed plastic is just a computer's patina.","Conventional Memory"],
["Every scratch is a day it was used.","Conventional Memory"],
["Retro computing is time travel with a power cord.","Conventional Memory"],
["The internet used to make noise. So did our computers.","Conventional Memory"],
["Before there was a cloud, there was a shoebox of disks.","Conventional Memory"],
["The cloud is someone else's computer. This one is mine, and it's beige.","Conventional Memory"],
["Save early. Save often. Save to the floppy labeled 'important.'","Conventional Memory"],
["Nothing ages a joke like a Y2K reference, and I'm still using it.","Conventional Memory"],
["The Y2K bug was fixed by a thousand tired programmers and a few very loud consultants.","Conventional Memory"],
["Modems taught a generation patience.","Conventional Memory"],
["A 56K modem was rarely 56K, but its ambition was correct.","Conventional Memory"],
["A BBS was a social network with a busy signal.","Conventional Memory"],
["A busy signal was the original 'the server is under load.'","Conventional Memory"],
["Shareware taught us that a free sample can change the world.","Conventional Memory"],
["The first episode was free. The rest cost extra.","Conventional Memory"],
["Registered shareware was the honor system of the digital age.","Conventional Memory"],
["The manual was half the game. The other half was the box.","Conventional Memory"],
["Big boxes were a promise. The disks inside were the fine print.","Conventional Memory"],
["Copy protection was a puzzle you did not order.","Conventional Memory"],
["Code wheels were the original two-factor authentication.","Conventional Memory"],
["Feelies: because a game should have a physical presence.","Conventional Memory"],
["A game manual was a bedtime story with an index.","Conventional Memory"],
["Some games came with maps. Some came with cloth maps. All came with expectations.","Conventional Memory"],
["The joystick port was a gateway drug.","Conventional Memory"],
["ISA slots were the original expansion pack.","Conventional Memory"],
["Plug and Play was a promise. Plug and Pray was the reality.","Conventional Memory"],
["The Sound Blaster made silence embarrassing.","Conventional Memory"],
["The OPL3 chip is still singing after thirty years.","Conventional Memory"],
["MIDI: the language of machines that wanted to play music.","Conventional Memory"],
["General MIDI is a suggestion. The MT-32 is a personality.","Conventional Memory"],
["AdLib existed because the PC speaker was tired of carrying the whole band.","Conventional Memory"],
["The PC speaker was the world's first minimalist orchestra.","Conventional Memory"],
["A tracker file is a song with an assembly line.","Conventional Memory"],
["Chiptune is what happens when constraints fall in love.","Conventional Memory"],
["Constraints are the mother of creativity, and DOS was a strict mother.","Conventional Memory"],
["DOS is still the shortest path between you and your files.","Conventional Memory"],
["There's beauty in a blinking cursor.","Conventional Memory"],
["A blinking cursor is a question the machine never stops asking.","Conventional Memory"],
["C:\\> is the most honest greeting in computing.","Conventional Memory"],
["Every directory listing is a tiny archaeological dig.","Conventional Memory"],
["DIR was the original search engine.","Conventional Memory"],
["CHKDSK: the doctor's visit nobody wanted and everybody needed.","Conventional Memory"],
["ScanDisk found errors. ScanDisk always found errors.","Conventional Memory"],
["Watching defrag squares move was the original meditation app.","Conventional Memory"],
["Screensavers were art installations for the desk.","Conventional Memory"],
["Flying toasters existed because monitors were fragile and imaginations were not.","Conventional Memory"],
["CRT burn-in: a museum plaque you didn't mean to make.","Conventional Memory"],
["A CRT is a tiny thunderstorm you sit in front of.","Conventional Memory"],
["The degauss thunk is one of the most satisfying sounds in the world.","Conventional Memory"],
["Scanlines aren't a flaw. They're a feature you didn't know you needed.","Conventional Memory"],
["Pixel art was a workaround that turned into a style.","Conventional Memory"],
["VGA: 256 colors and infinite possibility.","Conventional Memory"],
["EGA: sixteen colors, all of them dramatic.","Conventional Memory"],
["CGA: cyan, magenta, white, and pure commitment.","Conventional Memory"],
["Monochrome monitors were the original dark mode.","Conventional Memory"],
["Green phosphor is a lifestyle.","Conventional Memory"],
["Amber phosphor is for those who like their nostalgia warm.","Conventional Memory"],
["The best thing about an old keyboard is the sound. The second best is the weight.","Conventional Memory"],
["Buckling springs: the sound of typing with intent.","Conventional Memory"],
["A keyboard can outlive three computers and two owners.","Conventional Memory"],
["The Enter key on a Model M has all the confidence of a doorbell.","Conventional Memory"],
["Every keyboard is a conversation with a machine.","Conventional Memory"],
["Mouse pads had ads because someone believed in the future of the desk.","Conventional Memory"],
["Beige boxes were not boring. They were unbranded potential.","Conventional Memory"],
["The tower case: a monolith of possibility.","Conventional Memory"],
["The turbo button didn't do what you thought, and yet we pressed it anyway.","Conventional Memory"],
["The turbo button was a placebo with an LED.","Conventional Memory"],
["Every LED on a case was a tiny status report you didn't ask for.","Conventional Memory"],
["The hard drive light was the world's first anxiety indicator.","Conventional Memory"],
["A spinning disk is a small orchestra of tiny machines.","Conventional Memory"],
["The click of death is a hard drive's last words.","Conventional Memory"],
["RAM was measured in kilobytes and dreams in megabytes.","Conventional Memory"],
["Upgrade your RAM before you upgrade your patience.","Conventional Memory"],
["Memory upgrades were the original cosmetic surgery.","Conventional Memory"],
["A math coprocessor was the original GPU: optional, expensive, and worth it.","Conventional Memory"],
["Overclocking in 1995 meant moving a jumper and hoping.","Conventional Memory"],
["A jumper is a tiny switch you cannot see and cannot live without.","Conventional Memory"],
["Read the motherboard silkscreen like scripture.","Conventional Memory"],
["The BIOS screen is a machine's birth certificate.","Conventional Memory"],
["POST is the machine's daily affirmation.","Conventional Memory"],
["Booting is just a machine remembering who it is.","Conventional Memory"],
["The first boot after decades is a small miracle.","Conventional Memory"],
["When it powers on after thirty years, that's a resurrection.","Conventional Memory"],
["Never power up a mystery machine without a look at the caps.","Conventional Memory"],
["Any old machine can teach you something new.","Conventional Memory"],
["A machine that has been modified is a machine that has been loved.","Conventional Memory"],
["Documentation is a love letter to future you.","Conventional Memory"],
["If you didn't log the change, did it even happen?","Conventional Memory"],
["The changelog is the only version of history that gets more useful with age.","Conventional Memory"],
["Keep a changelog. Future you will thank you and also blame you.","Conventional Memory"],
["A good repair note is a gift to the next owner.","Conventional Memory"],
["Every catalog entry is a promise that this item mattered.","Conventional Memory"],
["An unlabeled cable is a mystery waiting to happen.","Conventional Memory"],
["Label everything. Then label the labels.","Conventional Memory"],
["The accessories are half the machine.","Conventional Memory"],
["A missing original charger is the collector's version of a missing sock.","Conventional Memory"],
["Every complete set is a small victory.","Conventional Memory"],
["'Complete in box' are the three most beautiful words in collecting.","Conventional Memory"],
["The box is half the value and all of the smell.","Conventional Memory"],
["Manuals: because someone had to write down what the machine was thinking.","Conventional Memory"],
["The manual you never read is the one you'll need.","Conventional Memory"],
["A driver disk is a time capsule for one version of one operating system.","Conventional Memory"],
["The disk labeled 'Drivers' is never the drivers.","Conventional Memory"],
["Every Windows 98 install is a small archaeological expedition.","Conventional Memory"],
["Windows 98 was the last operating system that trusted you with your own hardware.","Conventional Memory"],
["The Windows 95 startup chime is the sound of a generation logging on.","Conventional Memory"],
["The Start button was a promise: everything is one click away. It was almost true.","Conventional Memory"],
["Solitaire was Microsoft's best mouse training program.","Conventional Memory"],
["Minesweeper is a math test wearing a costume.","Conventional Memory"],
["The desktop background was the only art many of us owned.","Conventional Memory"],
["Clippy was the first AI assistant to wear out its welcome.","Conventional Memory"],
["Every error message is a museum piece if you look at it right.","Conventional Memory"],
["A blue screen was a cry for help in a font we could read.","Conventional Memory"],
["The general protection fault taught us humility.","Conventional Memory"],
["Ctrl+Alt+Del: the only prayer with a keyboard shortcut.","Conventional Memory"],
["There's no shame in a hard reset.","Conventional Memory"],
["The reset button was the original undo.","Conventional Memory"],
["A backup is the only time-travel technology that actually works.","Conventional Memory"],
["Image a drive before you touch it. It's the closest thing to a seatbelt.","Conventional Memory"],
["Write-protect your originals. Then thank your past self.","Conventional Memory"],
["Disk swapping was the original multitasking.","Conventional Memory"],
["Disk 1 of 15: the ultimate test of character.","Conventional Memory"],
["Installing from fifteen floppies was an act of devotion.","Conventional Memory"],
["The CD tray always fails at the most dramatic moment.","Conventional Memory"],
["Multimedia meant a video the size of a postage stamp, and we cheered.","Conventional Memory"],
["Full-motion video: because we needed to see people acting badly in low resolution.","Conventional Memory"],
["Every pixel was earned.","Conventional Memory"],
["Sprites were the original emoji.","Conventional Memory"],
["Loading screens were the original mindfulness practice.","Conventional Memory"],
["A loading bar was the first honest lie of the computing age.","Conventional Memory"],
["'Loading...' is the most optimistic word in computing.","Conventional Memory"],
["In the days of dial-up, we knew exactly what a megabyte cost.","Conventional Memory"],
["Downloading a song in 1999 was an overnight decision.","Conventional Memory"],
["The internet was a place you visited, and it had a sound.","Conventional Memory"],
["A GeoCities page had more personality in one visitor counter than most sites have today.","Conventional Memory"],
["Every 'under construction' sign was a promise to come back.","Conventional Memory"],
["The visitor counter was a small monument to hope.","Conventional Memory"],
["Web rings were social networks for people who preferred hyperlinks.","Conventional Memory"],
["Every guestbook was a small town square.","Conventional Memory"],
["View Source was the original open-source movement.","Conventional Memory"],
["Best viewed at 800x600 was our era's way of saying please don't judge me.","Conventional Memory"],
["Museum content is just show-and-tell with better lighting.","Conventional Memory"],
["The best videos start with 'I found this in a box.'","Conventional Memory"],
["Every unboxing is a tiny museum opening.","Conventional Memory"],
["When you press record, every machine becomes a character.","Conventional Memory"],
["The best content comes from curiosity, not algorithms.","Conventional Memory"],
["Show the weird machines. Explain the weird machines. Love the weird machines.","Conventional Memory"],
["Every video is a guided tour. Every comment is a guestbook signature.","Conventional Memory"],
["A channel is just a museum with a subscribe button.","Conventional Memory"],
["The camera loves a warm CRT.","Conventional Memory"],
["Film the boot sequence. It's the best part.","Conventional Memory"],
["Story first. Specs second. Hype never.","Conventional Memory"],
["Every item deserves a photo, a date, and a story.","Conventional Memory"],
["Provenance matters: where did it come from, and what did it see?","Conventional Memory"],
["A collection without notes is just a pile.","Conventional Memory"],
["A catalog is a museum's memory.","Conventional Memory"],
["The score is arbitrary. The love is not.","Conventional Memory"],
["A perfect score would leave no memory free for surprises.","Conventional Memory"],
["Every item earns its K.","Conventional Memory"],
["Loads high: the ultimate compliment.","Conventional Memory"],
["The 640K scale exists because 'nice' is not a measurement.","Conventional Memory"],
["Even a low score can have a great story.","Conventional Memory"],
["'Divide overflow' is not an insult. It's a diagnosis.","Conventional Memory"],
["Some machines score zero and still win hearts.","Conventional Memory"],
["If it runs Doom, it earns its place in the museum.","Conventional Memory"],
["Everything eventually runs Doom. Some things just took longer.","Conventional Memory"],
["The best part of a museum is the thing you weren't looking for.","Conventional Memory"],
["Curators don't collect things. They collect questions.","Conventional Memory"],
["Small computers make big memories.","Conventional Memory"],
["A tiny keyboard is a challenge dressed as a feature.","Conventional Memory"],
["A CompactFlash card is the fountain of youth for a tired hard drive.","Conventional Memory"],
["Swap the spinning disk for solid state and hear the silence of progress.","Conventional Memory"],
["Half the fun of a handheld is admitting you can't type on it.","Conventional Memory"],
["A pointing stick is a keyboard's tiny joystick.","Conventional Memory"],
["Subnotebooks prove that big ideas fit in small cases.","Conventional Memory"],
["Every handheld is a pocketful of what-ifs.","Conventional Memory"],
["Every DOS game begins with a menu of hope: 1. Play 2. Setup 3. Quit.","Conventional Memory"],
["Setup is where you set your IRQ and your expectations.","Conventional Memory"],
["The Sound Blaster config screen was the first boss.","Conventional Memory"],
["The best thing about DOS games is that they start instantly.","Conventional Memory"],
["A game that fits on one floppy is a game with nothing to hide.","Conventional Memory"],
["Every retro machine has a favorite game, and it's usually the one that hasn't loaded yet.","Conventional Memory"],
["A high score is a message to the next player. A changelog is a message to the next owner.","Conventional Memory"],
["The best upgrade is the one you can undo.","Conventional Memory"],
["Stock is a state of mind. Upgraded is a state of grace.","Conventional Memory"],
["A hardware mod is a conversation with the engineer who never got to finish.","Conventional Memory"],
["Tinkering is just curiosity with a screwdriver.","Conventional Memory"],
["If the screws are stripped, the story is just getting started.","Conventional Memory"],
["The last screw is always the shortest one, and the one you'll lose.","Conventional Memory"],
["Keep your screws in a magnetic tray and your patience in a cool, dry place.","Conventional Memory"],
["A good photo of the inside before disassembly is worth a thousand regrets.","Conventional Memory"],
["Take a photo before you unplug anything. You'll thank yourself at reassembly.","Conventional Memory"],
["Ribbon cables have opinions about which way they face.","Conventional Memory"],
["There's no such thing as a spare screw. There's only a screw you haven't needed yet.","Conventional Memory"],
["A soldering iron is a time machine with a very small tip.","Conventional Memory"],
["The pin 1 stripe on a cable is a promise of order in a chaotic universe.","Conventional Memory"],
["Every time you seat a card properly, an angel gets its wings.","Conventional Memory"],
["An ISA card that slides in smoothly is a small joy. One that doesn't is a story.","Conventional Memory"],
["The internet remembers everything except the driver you need.","Conventional Memory"],
["If you find the original driver disk, buy a lottery ticket.","Conventional Memory"],
["The Wayback Machine is the museum's best friend.","Conventional Memory"],
["An old forum thread is a better manual than the manual.","Conventional Memory"],
["The best documentation was written by strangers in 2003, one forum post at a time.","Conventional Memory"],
["Retro computing is a friendly place: everyone remembers being stuck.","Conventional Memory"],
["A good community is a museum with more curators.","Conventional Memory"],
["Every collector was a beginner once, holding a mystery cable.","Conventional Memory"],
["The hobby is never finished. That's the whole point.","Conventional Memory"],
["A museum is a place where broken things are treated with respect.","Conventional Memory"],
["Nostalgia is not a reason to keep it. Joy is.","Conventional Memory"],
["Preserve the machine, the manual, the box, and the memory.","Conventional Memory"],
["Old computers don't need to be useful. They need to be understood.","Conventional Memory"],
["The past is not gone. It's just stored on a disk somewhere, waiting for a drive.","Conventional Memory"],
["The future will be nostalgic for something we're throwing away right now.","Conventional Memory"],
["Every generation's junk is the next generation's museum piece.","Conventional Memory"],
["Somewhere, in a closet, a beige box is waiting to be found.","Conventional Memory"],
["Today's slow is tomorrow's charming.","Conventional Memory"],
["Retro isn't about the old. It's about the way it felt.","Conventional Memory"],
["A computer you can understand end to end is a rare and beautiful thing.","Conventional Memory"],
["There was a time when you could read every line of code your computer ran. That's the museum's real exhibit.","Conventional Memory"],
["Every machine here was somebody's whole world once.","Conventional Memory"],
["Remember: someone's first computer is on that shelf.","Conventional Memory"],
["Save everything. Sort it later. Label it now.","Conventional Memory"],
["Welcome to the museum. Please touch everything, gently.","Conventional Memory"],
["Thanks for visiting. Please rewind the tape.","Conventional Memory"],
["Come for the specs. Stay for the story.","Conventional Memory"],
["Press any key to enter the museum.","Conventional Memory"],
["Boot. Explore. Repeat.","Conventional Memory"],
["Compatible with your curiosity.","Conventional Memory"],
["Powered by 640K and a lot of coffee.","Conventional Memory"],
["No user-serviceable parts inside, except all of them.","Conventional Memory"],
["The warranty expired in 1996. The enthusiasm did not.","Conventional Memory"],
["Made in the last century, running strong.","Conventional Memory"],
["Vintage means it survived. Retro means it's remembered.","Conventional Memory"],
["Original parts, original problems.","Conventional Memory"],
["A well-kept machine is a conversation between decades.","Conventional Memory"],
["Every item has a date. Every date has a memory.","Conventional Memory"],
["The catalog never ends. That's the joy of it.","Conventional Memory"],
["Add one more item. Just one more. That's what you said last time.","Conventional Memory"],
["The shelf is full. Make another shelf.","Conventional Memory"],
["A collector's favorite number is one more.","Conventional Memory"],
["If you can't find it, you probably have three of it.","Conventional Memory"],
["The one thing you need is in the box you haven't opened yet.","Conventional Memory"],
["Every collection begins with a single 'I'll just take a look.'","Conventional Memory"]
];
