/* Toy-store features, loaded on demand: #/wish (wish list, Dear Santa letter, shareable list), #/kiosk (demo kiosk),
   #/prizes (prize counter) and #/backup (save and restore everything kept on this device).
   Everything here lives in the browser; nothing is sent anywhere. */
var CMToys=(function(){
 var app,KS={t:0,idle:0,el:null,kh:null,mode:"attract",n:0};
 function E(s){return esc(s==null?"":String(s))}
 function $(s){return app.querySelector(s)}
 function $$(s){return[].slice.call(app.querySelectorAll(s))}
 function ld(k,d){try{var v=JSON.parse(localStorage.getItem(k));return v==null?d:v}catch(e){return d}}
 function sv(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
 function glyph(n,z){return typeof px==="function"?px(n,z||18):""}
 function tlHref(r){return"#/timeline/"+String(r[0]).slice(0,4)+"/"+encodeURIComponent(r[2])}
 function motionOn(){return document.documentElement.getAttribute("data-motion")!=="off"}
 function ebay(q){return"https://www.ebay.com/sch/i.html?_nkw="+encodeURIComponent(q)+"&LH_Sold=0"}
 function sgw(q){return"https://shopgoodwill.com/categories/listing?st="+encodeURIComponent(q)}
 function copy(t,done,fail){if(navigator.clipboard)navigator.clipboard.writeText(t).then(done,fail);else fail()}
 function dl(name,text,type){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:type||"text/plain"}));a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},500)}

 /* ------------------------------------------------------------------ Wish list */
 function itemById(id){return ALLITEMS.filter(function(i){return i.id===id})[0]}
 function nameOf(k){var v=k.slice(2),r;
  if(k.indexOf("i:")===0){var it=itemById(v);return{n:it?it.name:v,href:it&&!it.draft?"#/item/"+it.id:"",tag:it?"in the museum":""}}
  if(k.indexOf("t:")===0){r=TL.filter(function(z){return z[2]===v})[0];return{n:v,href:r?tlHref(r):"",tag:r?"timeline":""}}
  if(/^[cxw]:/.test(k))return{n:v,href:"",tag:k.charAt(0)==="x"?"accessory":k.charAt(0)==="w"?"museum wanted list":""};
  var g=window.CMLabGap&&CMLabGap(k);return{n:g||"Milestone: "+k,href:"",tag:"milestone"}}
 function rows(){var R={},order=[];function add(k,src,x){if(!k||typeof k!=="string"||k.length>90)return;var r=R[k];if(!r){r=R[k]={k:k,src:[],max:""};order.push(k)}if(r.src.indexOf(src)<0)r.src.push(src);if(x&&x.max)r.max=x.max}
  wishLoad().forEach(function(w){add(w.k,"wish list",w)});
  var M=ld("cm-mine",{});Object.keys(M).forEach(function(k){if(M[k]&&M[k].s==="want")add(k,"my collection")});
  var H=ld("cm-hunt",{want:[],ceil:{}});(H.want||[]).forEach(function(k){add(k,"swap-meet list",{max:(H.ceil||{})[k]})});
  return order.map(function(k){return R[k]})}
 function removeEverywhere(k){wishSave(wishLoad().filter(function(w){return w.k!==k}));var M=ld("cm-mine",{});if(M[k]&&M[k].s==="want"){delete M[k];sv("cm-mine",M)}var H=ld("cm-hunt",{want:[],ceil:{}});H.want=(H.want||[]).filter(function(x){return x!==k});if(H.ceil)delete H.ceil[k];sv("cm-hunt",H)}
 function setMax(k,v){var w=wishLoad(),f=false;w.forEach(function(x){if(x.k===k){x.max=v;f=true}});if(!f)w.push({k:k,t:Date.now(),max:v});wishSave(w)}
 function b64(s){return btoa(unescape(encodeURIComponent(s))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
 function unb64(s){s=String(s).replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return decodeURIComponent(escape(atob(s)))}
 function shareCode(keys){return b64(JSON.stringify(keys.slice(0,40).map(function(k){return String(k).slice(0,80)})))}
 function readCode(c){try{var a=JSON.parse(unb64(c));return Array.isArray(a)?a.filter(function(k){return typeof k==="string"&&k.length<=80&&/^[a-z]?:?/.test(k)}).slice(0,40):null}catch(e){return null}}
 function buyLinks(n){return'<a href="'+E(ebay(n))+'" target="_blank" rel="noopener noreferrer">eBay</a> &middot; <a href="'+E(sgw(n))+'" target="_blank" rel="noopener noreferrer">ShopGoodwill</a>'}
 function finder(q){q=q.toLowerCase().trim();if(q.length<2)return[];var w=q.split(/\s+/),out=[];
  ALLITEMS.forEach(function(it){var h=(it.name+" "+(it.maker||"")).toLowerCase();if(w.every(function(x){return h.indexOf(x)>=0}))out.push({k:"i:"+it.id,n:it.name,s:(it.maker||"")+(it.year?" "+it.year:"")})});
  var seen={};TL.forEach(function(r){if(!/^(hw|sw|gt|pe|gn|gc)$/.test(r[1])||seen[r[2]])return;var h=r[2].toLowerCase();if(w.every(function(x){return h.indexOf(x)>=0})){seen[r[2]]=1;out.push({k:"t:"+r[2],n:r[2],s:String(r[0]).slice(0,4)+" timeline"})}});
  return out.slice(0,8)}
 function wish(code){var shared=code?readCode(code):null,mine=!code;
  if(code&&!shared){app.innerHTML='<section><h2>Wish list</h2><p class="empty">That shared list link looks damaged. Ask for a fresh one.</p><p><a class="btn" href="#/wish">My wish list</a></p></section>';return}
  var list=shared?shared.map(function(k){return{k:k,src:[],max:""}}):rows();
  var h='<section class="wsh"><h2>'+(shared?"A wish list from a friend":"My wish list")+'</h2>';
  if(shared)h+='<p>Someone sent you their list. Each item has quick search links, so you can see what is out there. Nothing is bought or tracked from here.</p>';
  else h+='<p>One list for everything you want: circled items from the Wish Book, "Want" marks in My collection, and your swap-meet list. It stays on this device. Circle things in the <a href="#/catalog">mail-order catalog</a>, press <b>Add to wish list</b> on any exhibit, or add one below.</p>';
  if(!mine)h+='<p><button class="btn pri" id="wcopyall" type="button">Copy these to my own list</button> <a class="btn" href="#/wish">My wish list</a></p>';
  if(mine)h+='<div class="wsh-add noprint"><label for="wq">Add something</label> <input id="wq" type="search" placeholder="Sound Blaster, Game Boy, Libretto..." autocomplete="off"><div id="wres" class="wsh-res"></div></div>';
  h+='<div id="wlist">'+listHtml(list,mine)+'</div>';
  if(mine){h+='<div class="wsh-act noprint"><button class="btn pri" id="wlink" type="button">Copy a link to share my list</button> <button class="btn" id="wsan" type="button">Write my Dear Santa letter</button> <button class="btn" id="wprint" type="button">Print</button></div><p id="wmsg" class="tn" role="status"></p><div id="wsanta"></div>'}
  app.innerHTML=h+'</section>';wire(list,mine,shared)}
 function listHtml(list,mine){if(!list.length)return conW('<p class="empty">Nothing on the list yet. '+(mine?"Search above, or circle something in the catalog.":"")+'</p>','wow');
  return'<ol class="wsh-l">'+list.map(function(r){var n=nameOf(r.k);return'<li><span class="wsh-n">'+(n.href?'<a href="'+E(n.href)+'">'+E(n.n)+'</a>':E(n.n))+(n.tag?' <small class="tn">'+E(n.tag)+'</small>':"")+'</span>'+(mine&&r.src.length?'<small class="tn wsh-s">'+E(r.src.join(", "))+'</small>':"")+'<span class="wsh-b noprint">'+buyLinks(n.n)+'</span>'+(mine?'<label class="wsh-m noprint">Max $ <input data-max="'+E(r.k)+'" inputmode="decimal" value="'+E(r.max||"")+'" size="5" aria-label="Most I would pay for '+E(n.n)+'"></label><button class="btn noprint" data-rm="'+E(r.k)+'" type="button" aria-label="Remove '+E(n.n)+'">&times;</button>':"")+'</li>'}).join("")+'</ol>'}
 function wire(list,mine,shared){
  if(!mine){var c=$("#wcopyall");if(c)c.onclick=function(){var w=wishLoad(),n=0;shared.forEach(function(k){if(!w.some(function(x){return x.k===k})){w.push({k:k,t:Date.now()});n++}});wishSave(w);c.textContent="Copied "+n+" to my list";c.disabled=true};return}
  function redraw(){$("#wlist").innerHTML=listHtml(rows(),true);bindList()}
  function bindList(){$$("[data-rm]").forEach(function(b){b.onclick=function(){removeEverywhere(b.dataset.rm);redraw()}});
   $$("[data-max]").forEach(function(i){i.onchange=function(){var k=i.dataset.max,v=i.value.replace(/[^0-9.]/g,"");i.value=v;setMax(k,v);var H=ld("cm-hunt",{want:[],ceil:{}});if((H.want||[]).indexOf(k)>=0){H.ceil=H.ceil||{};if(v)H.ceil[k]=v;else delete H.ceil[k];sv("cm-hunt",H)}}})}
  bindList();
  var q=$("#wq"),res=$("#wres");q.oninput=function(){var r=finder(q.value),t=q.value.trim();res.innerHTML=(r.length?r.map(function(x){return'<button type="button" class="btn" data-add="'+E(x.k)+'">+ '+E(x.n)+' <small>'+E(x.s)+'</small></button>'}).join(" "):"")+(t.length>=2?' <button type="button" class="btn" data-add="'+E("c:"+t.slice(0,80))+'">+ Add "'+E(t.slice(0,40))+'" as typed</button>':"")};
  res.onclick=function(e){var b=e.target.closest("[data-add]");if(!b)return;var k=b.dataset.add;if(!wishHas(k))wishToggle(k);q.value="";res.innerHTML="";redraw()};
  $("#wlink").onclick=function(){var keys=rows().map(function(r){return r.k});if(!keys.length){$("#wmsg").textContent="Add something first.";return}var u=location.origin+location.pathname+"#/wish/"+shareCode(keys);copy(u,function(){$("#wmsg").textContent="Link copied. Anyone who opens it sees your list (up to 40 items). It does not update if you change the list later."},function(){$("#wmsg").innerHTML="Copy this link: <input readonly value=\""+E(u)+"\" size=\"40\" onfocus=\"this.select()\">"})};
  $("#wprint").onclick=function(){window.print()};
  $("#wsan").onclick=function(){var l=rows();if(!l.length){$("#wmsg").textContent="Add a few things first, then write the letter.";return}
   $("#wsanta").innerHTML='<div class="santa"><p class="noprint"><label for="wnm">Your name</label> <input id="wnm" maxlength="40" value="'+E(ld("cm-wish-name",""))+'"></p><div id="wlet"></div></div>';
   function draw(){var nm=$("#wnm").value.trim();sv("cm-wish-name",nm);$("#wlet").innerHTML='<p>Dear Santa,</p><p>This year I was good (mostly). I fixed more than I broke. For my collection, I would like:</p><ol>'+rows().slice(0,25).map(function(r){return'<li>'+E(nameOf(r.k).n)+(r.max?' <small>(anything up to $'+E(r.max)+' is fair)</small>':"")+'</li>'}).join("")+'</ol><p>I will leave out a cookie and a fresh CR2032.</p><p>Love,<br><b>'+E(nm||"A fellow collector")+'</b></p>'}
   $("#wnm").oninput=draw;draw();$("#wsanta").scrollIntoView({block:"nearest"})}}

 /* ------------------------------------------------------------------ Prize counter */
 var PRIZES=[["st-star","Gold star sticker","sticker","star",3],["st-heart","Heart sticker","sticker","heart",3],["st-ghost","Ghost sticker","sticker","ghost",5],["st-rocket","Rocket sticker","sticker","rocket",8],["st-dino","Dino sticker","sticker","dino",8],["st-ufo","UFO sticker","sticker","ufo",10],["st-gem","Gem sticker","sticker","gem",15],["st-crown","Crown sticker","sticker","crown",25],["st-trophy","Tiny trophy","sticker","trophy",30],
  ["sk-blue","Connie in blue","skin","blue",15],["sk-pink","Connie in pink","skin","pink",15],["sk-red","Connie in red","skin","red",20],["sk-purple","Connie in purple","skin","purple",20],["sk-black","Connie in black","skin","black",25],["sk-gold","Connie in gold","skin","gold",40],
  ["lk-plaid","Look: Plaid punk","look","plaid",12],["lk-check","Look: Racer","look","check",12],["lk-cyber","Look: Cyber","look","cyber",20],["lk-prom","Look: Prom night","look","prom",30],
  ["ac-joy","Joystick hat","acc","joy",10],["ac-shades","80s shades","acc","shades",10],["ac-prop","Propeller beanie","acc","prop",15],["ac-crown","Little crown","acc","crown",40],
  ["gold-floppy","The Golden Floppy","grand","floppy",100]];
 var PKIND={sticker:"Sticker",skin:"Mascot color",look:"Connie look",acc:"Connie accessory",grand:"Grand prize"};
 function pzMas(x,n){var k=x[2],o=k==="look"?{look:x[3],acc:"none"}:k==="acc"?{acc:x[3]}:{};return mascot(n,"happy",k==="skin"?x[3]:undefined,false,o)}
 function pzWorn(x){var c=CMCast.cur();return x[2]==="skin"?c.skin===x[3]:x[2]==="look"?c.look===x[3]:c.acc===x[3]}
 function prizeState(){var p=ld("cm-prizes",{});p.own=Array.isArray(p.own)?p.own:[];p.spent=+p.spent||0;p.bonus=+p.bonus||0;return p}
 function ticketsOf(p){var xp=(ld("cm-play",{xp:0}).xp)||0;return Math.max(0,Math.floor(xp/3)+p.bonus-p.spent)}
 function todayKey(){var d=new Date();return d.getFullYear()+"-"+(d.getMonth()+1)+"-"+d.getDate()}
 function prizes(){var p=prizeState(),t=ticketsOf(p),claimed=p.day===todayKey(),skin=p.skin||"green";
  var h='<section class="pz"><h2>Prize counter</h2><div class="pz-top"><div class="pz-m">'+mascot(112,"happy",skin,true)+'<p class="pz-say">'+(t>=3?"You have tickets to spend!":"Play a game to earn tickets.")+'</p></div><div class="pz-t"><b>'+t+'</b><span>tickets</span></div></div>'
   +'<p>Every 3 XP you earn in the <a href="#/play">games</a> is a ticket, and there is one free ticket a day. Spend them on stickers, new colors, outfits and accessories for Connie, or the grand prize. Some looks cannot be bought at all: you earn those by playing. Prizes stay on this device. <a href="#/closet">Open Connie\'s closet</a>.</p>'
   +'<p>'+(claimed?'<button class="btn" disabled>Today\'s free ticket is claimed</button>':'<button class="btn pri" id="pzfree" type="button">Claim today\'s free ticket</button>')+'</p>';
  var own=PRIZES.filter(function(x){return p.own.indexOf(x[0])>=0});
  h+='<h3 class="sub">My shelf</h3>'+(own.length?'<div class="pz-shelf">'+own.map(function(x){return'<div class="pz-o">'+(/^(skin|look|acc)$/.test(x[2])?pzMas(x,48):'<span class="pz-gl'+(x[2]==="grand"?" gold":"")+'">'+px(x[3],44)+'</span>')+'<small>'+E(x[1])+'</small>'+(/^(skin|look|acc)$/.test(x[2])?'<button class="btn" data-wear="'+x[0]+'" type="button"'+(pzWorn(x)?" disabled":"")+'>'+(pzWorn(x)?"Wearing":"Use")+'</button>':"")+'</div>'}).join("")+(skin!=="green"?'<div class="pz-o">'+mascot(48,"happy","green")+'<small>Connie in green</small><button class="btn" data-wear="green" type="button">Use</button></div>':"")+'</div>':'<p class="empty">The shelf is empty. Pick something below.</p>');
  h+='<h3 class="sub">The counter</h3><div class="pz-grid">'+PRIZES.filter(function(x){return p.own.indexOf(x[0])<0}).map(function(x){var can=t>=x[4];return'<div class="pz-c"><span class="pz-gl'+(x[2]==="grand"?" gold":"")+'">'+(/^(skin|look|acc)$/.test(x[2])?pzMas(x,44):px(x[3],40))+'</span><b>'+E(x[1])+'</b><small>'+(PKIND[x[2]]||"Sticker")+'</small><button class="btn'+(can?" pri":"")+'" data-buy="'+x[0]+'" type="button"'+(can?"":" disabled")+'>'+x[4]+' tickets'+(can?"":" ("+(x[4]-t)+" more)")+'</button></div>'}).join("")+'</div>'
   +'<p class="tn">Connie Ventional (Connie for short) is the museum\'s mascot, an original character. Colors you earn show up on the not-found page, the kiosk and here.</p></section>';
  app.innerHTML=h;
  var f=$("#pzfree");if(f)f.onclick=function(){var q=prizeState();if(q.day===todayKey())return;q.day=todayKey();q.bonus+=1;sv("cm-prizes",q);prizes()};
  $$("[data-buy]").forEach(function(b){b.onclick=function(){var q=prizeState(),x=PRIZES.filter(function(z){return z[0]===b.dataset.buy})[0];if(!x||q.own.indexOf(x[0])>=0||ticketsOf(q)<x[4])return;q.spent+=x[4];q.own.push(x[0]);if(x[2]==="skin")q.skin=x[3];sv("cm-prizes",q);if(x[2]==="look")CMCast.save({look:x[3]});if(x[2]==="acc")CMCast.save({acc:x[3]});prizes()}});
  $$("[data-wear]").forEach(function(b){b.onclick=function(){var x=PRIZES.filter(function(z){return z[0]===b.dataset.wear})[0];if(!x){CMCast.save({skin:"green"});prizes();return}CMCast.save(x[2]==="skin"?{skin:x[3]}:x[2]==="look"?{look:x[3]}:{acc:x[3]});prizes()}})}

 /* ------------------------------------------------------------------ Backup and restore */
 var ALLOW=["cm-mine","cm-hunt","cm-wish","cm-wish-name","cm-rigs","cm-rig","cm-play","cm-higher","cm-daily","cm-bingo","cm-tours","cm-trail","cm-photo","cm-boot","cm-ads","cm-adx","cm-theater","cm-fig","cm-credit","cm-prizes","cm-connie","cm-theme","cm-sfx","cm-motion","cm-crt","cm-catmode","cm-booksnd","cm-bkmark","cm-maze-code","cm-labelset","cm-labelall","cm-inv","cm-invmode"];
 var LABEL={"cm-mine":"My collection","cm-hunt":"Swap-meet list","cm-wish":"Wish list","cm-wish-name":"Name on the wish letter","cm-rigs":"Saved dream rigs","cm-rig":"Rig game","cm-play":"Game progress and badges","cm-higher":"Higher or Lower","cm-daily":"Daily Dig","cm-bingo":"Bingo","cm-tours":"Tours","cm-trail":"Cursor trail","cm-photo":"Mystery Photo","cm-boot":"Boot screen","cm-ads":"Ad Lab","cm-adx":"Ad Lab extras","cm-theater":"Theater queue","cm-fig":"Figures","cm-credit":"Credits","cm-prizes":"Prizes and tickets","cm-connie":"Connie's closet and Funnies progress","cm-theme":"Theme","cm-sfx":"Sound effects","cm-motion":"Motion setting","cm-crt":"Screen effect","cm-catmode":"Catalog style","cm-booksnd":"Page-turn sound","cm-bkmark":"Catalog bookmark","cm-maze-code":"Basement code"};
 function present(){var o={};ALLOW.forEach(function(k){try{var v=localStorage.getItem(k);if(v!=null)o[k]=v}catch(e){}});return o}
 function validate(txt){var j;try{j=JSON.parse(txt)}catch(e){return{err:"That file is not a backup (it could not be read)."}}
  if(!j||j.app!=="conventionalmemory"||typeof j.data!=="object"||j.data===null)return{err:"That file is not a Conventional Memory backup."};
  var ok={},skipped=0,total=0;Object.keys(j.data).forEach(function(k){var v=j.data[k];if(ALLOW.indexOf(k)<0||typeof v!=="string"||v.length>200000){skipped++;return}v=clean(k,v);if(v==null){skipped++;return}total+=v.length;if(total>1500000){skipped++;return}ok[k]=v});
  return Object.keys(ok).length?{ok:ok,skipped:skipped,date:j.date}:{err:"Nothing in that file can be restored."}}
 /* Values from a backup file are untrusted: keep only the shapes the site itself writes. */
 function clean(k,v){var o;if(k==="cm-labelset"||k==="cm-play"||k==="cm-daily"||k==="cm-theater"){try{o=JSON.parse(v)}catch(e){return null}if(!o||typeof o!=="object"||Array.isArray(o))return null}
  var nz=function(x){x=Math.floor(+x);return isFinite(x)&&x>0?Math.min(x,1e9):0};
  if(k==="cm-labelset"){delete o.base;return JSON.stringify(o)}
  if(k==="cm-play"){o.xp=nz(o.xp);return JSON.stringify(o)}
  if(k==="cm-daily"){["streak","best","total","shield","perfect","saved"].forEach(function(f){o[f]=nz(o[f])});return JSON.stringify(o)}
  if(k==="cm-theater"){o.l=(Array.isArray(o.l)?o.l:[]).filter(function(x){return x&&/^[\w-]{11}$/.test(x.id||"")}).slice(0,200).map(function(x){return{id:x.id,t:String(x.t||"").slice(0,120)}});return JSON.stringify(o)}
  return v}
 function backup(){var cur=present(),ks=Object.keys(cur);
  app.innerHTML='<section class="bkp"><h2>Back up my stuff</h2><p>Everything you do here (collection, wish list, game progress, saved rigs, settings) lives only in this browser. Save it to a file to move it to another device or keep a copy. Nothing is uploaded anywhere. Admin passphrases and tokens are never included.</p>'
   +'<p><button class="btn pri" id="bsave" type="button"'+(ks.length?"":" disabled")+'>Save a backup file ('+ks.length+' items)</button></p>'
   +(ks.length?'<details><summary>What is in it</summary><ul>'+ks.map(function(k){return'<li>'+E(LABEL[k]||k)+' <small class="tn">'+Math.ceil(cur[k].length/1024)+' KB</small></li>'}).join("")+'</ul></details>':'<p class="empty">Nothing saved on this device yet.</p>')
   +'<h3 class="sub">Restore</h3><p><label for="bfile">Choose a backup file</label> <input id="bfile" type="file" accept=".json,application/json"></p><div id="bprev" aria-live="polite"></div>'
   +'<h3 class="sub">Start over</h3><p class="tn">Removes everything listed above from this browser. Your backup file is not affected.</p><p><button class="btn" id="bwipe" type="button">Erase this device\'s saved stuff</button></p><p id="bmsg" class="tn" role="status"></p></section>';
  $("#bsave").onclick=function(){var d=new Date(),n=d.getFullYear()+("0"+(d.getMonth()+1)).slice(-2)+("0"+d.getDate()).slice(-2);dl("conventional-memory-backup-"+n+".json",JSON.stringify({app:"conventionalmemory",v:1,date:d.toISOString(),data:present()},null,1),"application/json");$("#bmsg").textContent="Saved. Keep the file somewhere safe."};
  $("#bfile").onchange=function(){var f=this.files&&this.files[0],pv=$("#bprev");if(!f)return;if(f.size>2000000){pv.innerHTML='<div class="msg err">That file is too large to be a backup.</div>';return}
   var rd=new FileReader();rd.onload=function(){var v=validate(String(rd.result));if(v.err){pv.innerHTML='<div class="msg err">'+E(v.err)+'</div>';return}
    pv.innerHTML='<div class="msg ok"><b>'+Object.keys(v.ok).length+' items found</b>'+(v.date?' from '+E(String(v.date).slice(0,10)):"")+(v.skipped?', '+v.skipped+' skipped (not allowed)':"")+'.<ul>'+Object.keys(v.ok).map(function(k){return'<li>'+E(LABEL[k]||k)+'</li>'}).join("")+'</ul>Restoring replaces what is on this device for these items.</div><p><button class="btn pri" id="brestore" type="button">Restore these</button></p>';
    $("#brestore").onclick=function(){Object.keys(v.ok).forEach(function(k){try{localStorage.setItem(k,v.ok[k])}catch(e){}});$("#bmsg").textContent="Restored. Reloading...";setTimeout(function(){location.reload()},600)}};
   rd.onerror=function(){pv.innerHTML='<div class="msg err">That file could not be read.</div>'};rd.readAsText(f)};
  var w=$("#bwipe");w.onclick=function(){if(w.dataset.sure!=="1"){w.dataset.sure="1";w.textContent="Press again to erase";setTimeout(function(){w.dataset.sure="";w.textContent="Erase this device's saved stuff"},4000);return}ALLOW.forEach(function(k){try{localStorage.removeItem(k)}catch(e){}});try{sessionStorage.removeItem("cm-era")}catch(e){}$("#bmsg").textContent="Erased. Reloading...";setTimeout(function(){location.reload()},600)}}

 /* ------------------------------------------------------------------ Demo kiosk */
 function kStop(){clearInterval(KS.t);clearTimeout(KS.idle);KS.t=0;if(KS.kh)document.removeEventListener("keydown",KS.kh,true);KS.kh=null;if(KS.el){KS.el.remove();KS.el=null}document.documentElement.classList.remove("kiosk-on");try{if(document.fullscreenElement)document.exitFullscreen()}catch(e){}}
 function slides(){var S=[],pool=ITEMS.length?ITEMS:ALLITEMS,i;
  pool.forEach(function(it){S.push(function(){var t=it.score!=null?tier(it.score):null;return'<div class="k-sl k-it"><div class="k-ph">'+pic(it)+'</div><div class="k-tx"><small>FROM THE COLLECTION</small><h3>'+E(it.name)+'</h3><p>'+E((it.maker||"")+(it.year?", "+it.year:""))+'</p>'+(t?'<p class="k-sc" style="background:'+t.c+';color:'+inkOn(t.c)+'">'+it.score+'K '+E(t.l)+'</p>':"")+'<p>'+E(String(it.text||"").replace(/\s+/g," ").slice(0,170))+'</p></div></div>'})});
  var hw=TL.filter(function(r){return/^(hw|pe)$/.test(r[1])&&r[3]&&r[4]});for(i=0;i<8&&hw.length;i++){(function(r){S.push(function(){return'<div class="k-sl"><small>'+E(String(r[0]).slice(0,4))+' ON THE SHELF</small><h3>'+E(r[2])+'</h3><p class="k-p">'+E(String(r[3]).replace(/\*$/," (est.)"))+'</p><p>'+E(String(r[4]).slice(0,200))+'</p></div>'})})(hw[Math.floor(Math.random()*hw.length)])}
  var gm=TL.filter(function(r){return r[1]==="gt"||r[1]==="sw"});for(i=0;i<6&&gm.length;i++){(function(r){S.push(function(){return'<div class="k-sl"><small>NOW PLAYING, '+E(String(r[0]).slice(0,4))+'</small><h3>'+E(r[2])+'</h3><p>'+E(String(r[4]||"").slice(0,200))+'</p></div>'})})(gm[Math.floor(Math.random()*gm.length)])}
  if(typeof QUOTES!=="undefined")for(i=0;i<4;i++){(function(q){S.push(function(){return'<div class="k-sl"><small>OVERHEARD AT THE MUSEUM</small><h3 class="k-q">&ldquo;'+E(q[0])+'&rdquo;</h3><p>'+E(q[1])+'</p></div>'})})(QUOTES[Math.floor(Math.random()*QUOTES.length)])}
  S.push(function(){return'<div class="k-sl"><small>DID YOU KNOW</small><h3>The 640K barrier</h3><p>DOS programs had 640 kilobytes of conventional memory to work with. The museum is named for it.</p></div>'});
  return S}
 function kiosk(auto){
  app.innerHTML='<section><h2>Demo kiosk</h2><div class="k-intro">'+mascot(96,"wow",undefined,true)+'<div><p>Attract mode for a spare screen, like the demo station in a toy-store aisle: slides of exhibits, old prices and quotes cycle on their own. Touch or press any key and a big-button menu appears. It goes back to the slides after 45 idle seconds.</p><p><button class="btn pri" id="kgo" type="button">Start the kiosk</button> <button class="btn" id="kfs" type="button">Start full screen</button></p><p class="tn">Press Escape to leave.</p></div></div></section>';
  $("#kgo").onclick=function(){start(false)};$("#kfs").onclick=function(){start(true)};if(auto===true)start(false);
  function start(fs){kStop();var S=slides(),n=Math.floor(Math.random()*S.length),el=document.createElement("div");el.id="kiosk";el.className="kiosk";el.setAttribute("role","dialog");el.setAttribute("aria-label","Demo kiosk");KS.el=el;
   el.innerHTML='<button type="button" class="kx" id="kexit">Exit kiosk (Esc)</button><div class="k-top">'+mascot(56,"happy")+'<b>CONVENTIONAL MEMORY</b></div><div id="kscr" class="k-scr" aria-live="off"></div><div id="kbar" class="k-bar"></div>';document.body.appendChild(el);document.documentElement.classList.add("kiosk-on");
   if(fs&&el.requestFullscreen)try{el.requestFullscreen()}catch(e){}
   var scr=el.querySelector("#kscr"),bar=el.querySelector("#kbar");KS.mode="attract";
   function show(){if(KS.mode!=="attract")return;scr.className="k-scr"+(motionOn()?" k-in":"");scr.innerHTML=S[n%S.length]();n++;bar.innerHTML='<span class="k-start">PRESS START</span>'}
   function menu(){KS.mode="menu";clearTimeout(KS.idle);scr.className="k-scr";scr.innerHTML='<h3 class="k-h">What would you like to do?</h3><div class="k-menu"><a href="#/catalog" data-book="1">Open the Wish Book</a><a href="#/catalog">Browse the exhibits</a><a href="#/daily">Play the Daily Dig</a><a href="#/walk/1995">Walk through 1995</a><a href="#/rigs">Build a dream rig</a><a href="#/runs">Does it run?</a></div>';bar.innerHTML='<span class="tn">Touch a button. Idle for 45 seconds returns to the slides.</span>';KS.idle=setTimeout(function(){KS.mode="attract";show()},45000)}
   el.addEventListener("click",function(e){if(e.target.closest("#kexit")){location.hash="#/kiosk";kStop();kiosk();return}var a=e.target.closest("a[data-book]");if(a){try{localStorage.setItem("cm-catmode","book")}catch(x){}kStop();return}if(e.target.closest(".k-menu a")){kStop();return}if(KS.mode==="attract")menu();else{clearTimeout(KS.idle);KS.idle=setTimeout(function(){KS.mode="attract";show()},45000)}});
   KS.kh=function(e){if(e.key==="Escape"){kStop();kiosk();return}if(KS.mode==="attract"&&!/^(Shift|Control|Alt|Meta)$/.test(e.key)){e.preventDefault();menu()}};document.addEventListener("keydown",KS.kh,true);
   show();KS.t=setInterval(function(){if(!document.getElementById("kiosk")){kStop();return}show()},7000)}}

 /* ------------------------------------------------------------------ Makers, manuals, labels, start here */
 function makers(){var m={};ALLITEMS.forEach(function(i){if(i.maker&&i.maker!=="Unknown"&&!i.draft){var o=m[i.maker]||(m[i.maker]={n:i.maker,items:[],tl:0});o.items.push(i)}});
  if(typeof TLX!=="undefined")TL.forEach(function(r){var x=TLX[r[2]];if(x&&x.maker&&/^(hw|pe)$/.test(r[1])){var o=m[x.maker]||(m[x.maker]={n:x.maker,items:[],tl:0});o.tl++}});return m}
 function maker(name){var M=makers();
  if(!name){var ks=Object.keys(M).sort(function(a,b){return M[b].items.length-M[a].items.length||M[b].tl-M[a].tl||a.localeCompare(b)});
   app.innerHTML='<section><h2>Makers</h2><p>Every company with something in the museum, and how many machines they made on the timeline. Pick one to see what is here.</p><div class="chips">'+ks.map(function(k){return'<a class="btn'+(M[k].items.length?" pri":"")+'" href="#/maker/'+encodeURIComponent(k)+'">'+E(k)+' <small>'+M[k].items.length+(M[k].tl?" / "+M[k].tl:"")+'</small></a>'}).join(" ")+'</div><p class="tn">First number: exhibits in the museum. Second: hardware entries on the timeline.</p></section>';return}
  var o=M[name];if(!o){app.innerHTML='<section><h2>Makers</h2><p class="empty">No maker called '+E(name)+' on file.</p><p><a class="btn" href="#/maker">All makers</a></p></section>';return}
  var tl=typeof TLX!=="undefined"?TL.filter(function(r){var x=TLX[r[2]];return x&&x.maker===name&&/^(hw|pe)$/.test(r[1])}).sort(function(a,b){return a[0]<b[0]?-1:1}):[];
  var own=function(t){return ITEMS.some(function(i){return i.name===t||(typeof tlOwn==="function"&&tlOwn(t)&&tlOwn(t).id===i.id)})};
  app.innerHTML='<section><h2>'+E(name)+'</h2><p><a href="#/maker">All makers</a></p><h3 class="sub">In the museum ('+o.items.length+')</h3>'+(o.items.length?'<div class="grid">'+o.items.map(card).join("")+'</div>':'<p class="empty">Nothing from '+E(name)+' yet.</p>')
   +(tl.length?'<h3 class="sub">On the timeline ('+tl.length+')</h3><ul class="pl-sr">'+tl.slice(0,60).map(function(r){return'<li><span class="tn">'+E(String(r[0]).slice(0,4))+'</span> <a href="'+tlHref(r)+'">'+E(r[2])+'</a>'+(typeof tlOwn==="function"&&tlOwn(r[2])?' <span class="tag">in the museum</span>':'')+(r[3]?' <small class="tn">'+E(String(r[3]).replace(/\*$/,""))+'</small>':"")+'</li>'}).join("")+'</ul>':"")+'</section>'}
 function manuals(){var L=[];ITEMS.forEach(function(it){(it.links||[]).forEach(function(l){var u=safeUrl(l.u,"link");if(u)L.push({it:it,t:l.t,u:u})});(it.refs||[]).forEach(function(l){var u=safeUrl(l.u,"link");if(u)L.push({it:it,t:l.t,u:u,ref:1})})});
  var by={};L.forEach(function(x){(by[x.it.id]=by[x.it.id]||{it:x.it,l:[]}).l.push(x)});var ks=Object.keys(by).sort(function(a,b){return by[a].it.name.localeCompare(by[b].it.name)});
  app.innerHTML='<section><h2>Manuals and references</h2><p>Every manual, driver page and reference the museum links to, by exhibit. Manuals are added in Admin under Links.</p>'+(ks.length?ks.map(function(k){var g=by[k];return'<h3 class="sub"><a href="#/item/'+E(g.it.id)+'">'+E(g.it.name)+'</a></h3><ul>'+g.l.map(function(x){return'<li><a href="'+E(x.u)+'" target="_blank" rel="noopener noreferrer">'+E(x.t)+'</a>'+(x.ref?' <small class="tn">source</small>':"")+'</li>'}).join("")+'</ul>'}).join(""):'<p class="empty">No manuals or references linked yet.</p>')+'</section>'}
 function needs(list,cb){var i=0;(function nx(){if(i>=list.length){cb();return}var f=list[i++];if(document.querySelector('script[data-lbl="'+f+'"]')&&window[{"qr.js":"CMCode","labelprint.js":"CMLabel","labelui.js":"CMLabelUI"}[f]]){nx();return}
   var sc=document.createElement("script");sc.src=f;sc.setAttribute("data-lbl",f);sc.onload=nx;sc.onerror=function(){app.innerHTML='<section><h2>Oops</h2><p class="empty">The label tools could not be loaded. Try again in a moment.</p></section>'};document.head.appendChild(sc)})()}
 function labels(arg){var el=app;app.innerHTML='<section><h2>Print labels</h2><p>Loading the label tools...</p></section>';needs(["qr.js","labelprint.js","labelui.js"],function(){if(app===el&&/^#\/labels/.test(location.hash))CMLabelUI.labels(el,arg)})}
 function scan(){var el=app;app.innerHTML='<section><h2>Scan a label</h2><p>Loading...</p></section>';needs(["qr.js","labelprint.js","labelui.js"],function(){if(app===el&&/^#\/scan/.test(location.hash))CMLabelUI.scan(el)})}

 /* ------------------------------------------------------------------ About */
 /* Edit the crew here. Portraits are pixel art in /portraits. Everything below is plain text. */
 var CREW=[
  {k:"matt",n:"Matt",role:"Creator and curator",tag:"PLAYER 1",img:"portraits/matt.png",w:543,h:724,pix:0,art:"Rendered in the style of The Colonel's Bequest (1989)",alt:"Portrait of Matt in a backwards white cap, in a Colonel's Bequest style mansion with a fireplace and a framed portrait",
   bio:"Matt has been taking computers apart and writing games since he was a little kid, and he has worked in technology his whole life. He built levels for Doom, obsessed over and built levels for Duke Nukem 3D, and wrote games in Visual Basic, then later in XNA, Unity, Godot and more. Today he leads a large team of technology professionals. He is also an EMT and works in an emergency room in his spare time, for fun, because he likes helping people, wants to make a real difference when someone is having the worst day of their life, and is a lifelong learner who cannot sit still. He started the museum, wrote the code and owns the soldering iron. He also has three young boys, who will someday inherit a museum of technical history and a cable for every situation they will not be interested in. He hopes they will be interested. He hopes very hard.",
   stats:[["Years in technology","HIS WHOLE LIFE"],["Day job","LEADS A LARGE TECH TEAM"],["Spare time","EMT, WORKS IN AN ER TO HELP PEOPLE"],["Game engines","VB, XNA, UNITY, GODOT AND MORE"],["Sitting still","NEVER"],["Robotic programming","VERY GOOD"],["Patience with IRQ conflicts","LOW"],["Cables in the drawer","INFINITE"],["Backwards cap","EQUIPPED"],["Inventory","FULL OF WORTHLESS STUFF"],["Will never let go of","ANYTHING"],["Heirs","3 YOUNG BOYS (INTEREST PENDING)"]],
   quips:["It works on my machine. It is also my only machine.","I swear it booted yesterday.","One more exhibit. Then I will stop. (I will not stop.)","Did you try the Konami code?","That is not junk. That is a rare item.","I might need that later.","Someday, boys, all of this will be yours.","There is a cable for that. There is a cable for everything."]},
  {k:"tony",n:"Tony",role:"Maker and merchant of many trades",tag:"PLAYER 2",img:"portraits/tony.png",w:561,h:701,pix:0,art:"Painted in the style of Torin's Passage (1995)",alt:"Painted cartoon portrait of Tony in a red, green and blue jester hat",
   bio:"Tony is Matt's brother and his Player 2 for life. Today he is a sales manager, which is the grown-up version of the kid who ran a black market out of his school locker. His inventory back then was candy, yo-yos and beef jerky, sold to students and teachers alike, with no shortage of repeat customers. After hours he makes leather goods and costumes, some of which have appeared in films. He is also a puppet maker, stained glass artist, iPod modder and 3D modeler, because once he feels competent at a skill he moves on to the next one, like a player who has to max out every category before the credits roll. It all started with MegaZeux, where he happily spent hours on the art and level design and just as happily left the programming to Matt. He loves a good RPG, especially the kind with simple rules and deep systems, owns a jester hat, and has an unmatched talent for accidentally axing the one NPC the quest depended on. He also has three kids who are into soldering and programming.",
   stats:[["Day job","SALES MANAGER"],["Selling anything","SKILL MAXED"],["Side quest","LEATHER, COSTUMES AND FILM PROPS"],["Studios served","4 MOVIE STUDIOS (AND COUNTING)"],["Skill tree","LEATHER, PUPPETS, IPOD MODDING, MAKING, MAKING, MAKING..."],["Skill categories maxed out","ONE AT A TIME"],["Building worlds","SINCE MEGAZEUX"],["Programming in MegaZeux","SKIPPED THE TUTORIAL"],["Co-op player","MY BROTHER, FOR LIFE"],["Brother status","CONFIRMED"],["Jester hat","EQUIPPED"],["Quest-giving NPCs axed","ALL OF THEM"],["Axe control near an important NPC","SUSPICIOUSLY TWITCHY"],["Will never admit","IT WAS AN ACCIDENT"],["Equipped","QUALITY PEN, NOTEBOOK, POCKET KNIFE"],["Will never throw away","ANYTHING USEFUL"],["Inventory","SUSPICIOUSLY FULL OF \"USEFUL\" MATERIAL"],["Heirs","3 KIDS (SOLDERING: YES, ART: PENDING)"]],
   quips:["Player 2 has entered the game.","Where is the any key?","I was told there would be snacks.","Both thumbs up. Ship it.","The quest giver was in the way.","Was that guy important?","I can make that.","What is that worth? I can move it.","I will take the beef jerky and the yo-yos. You can keep the candy."]}];

 /* The workstation picture: every hotspot is a button with a text-adventure answer. Positions are percentages of the picture. */
 var ROOM=[
  ["Duke poster",24.2,12.4,11.4,25.8,"A poster of Duke. He looks like he is out of gum."],
  ["Star Wars poster",83.6,9.2,16.4,46,"A long time ago, in a galaxy far, far away, but also on the wall right here."],
  ["Lava lamp",15.5,29,5.5,31,"It blorps. You are not sure it is on, and you are afraid to ask."],
  ["Plush creature",16.9,56.4,5.2,7.2,"It is looking at you. It has been looking at you the whole time."],
  ["Left speaker",26.6,44.7,8.6,14.3,"A Roland speaker. It was built for one job: making MIDI sound important."],
  ["Right speaker",65.3,44.7,8.6,14.3,"The other Roland speaker. Stereo is a team sport."],
  ["Monitor",35.9,24.1,28.7,30.2,"A big blue CRT, switched off. It hums when it is on. You can feel it in your teeth."],
  ["Wall phone",72.2,21.2,4.5,22,"A beige wall phone. You pick it up and hear a modem. Nobody can use the phone while the internet is on."],
  ["Cap",74.2,52.3,8.3,11.2,"A cap. Whether it is on backwards is between you and the cap."],
  ["Doritos",25.7,58.9,10.2,19.3,"A bag of Doritos. Opening it is not an action in this game. It is a lifestyle."],
  ["Surge",84.6,60.8,5.9,12.9,"A can of Surge. It glows slightly. You decide not to ask what is in it."],
  ["Keyboard",23.1,80.6,46,15.2,"A clicky beige keyboard. Press any key. No, not that one. The other any key."],
  ["PC Gamer",36.6,72.9,22.5,7.2,"A real PC Gamer from the 90s, with Duke Nukem Forever on the cover story. It was coming soon then. It is coming soon now. Some things are timeless."],
  ["Pager",63,73.2,6.8,4.3,"A real pager. It goes beep. Somebody, somewhere, wanted you to call them back from a land line."],
  ["Tamagotchi",39.5,56.3,4.7,4.2,"A real Tamagotchi. Please do not ask how long it has been since it ate."],
  ["Blockbuster card",55.3,57.7,6.2,3.8,"A real Blockbuster card. Be kind, rewind. You are somehow still not late on your fees."],
  ["Mouse and pad",69.4,81,22.4,14.7,"A mouse on a Duke mouse pad. It has a ball inside. Please do not ask where the ball goes."]];
 var LOG=[
  ["Chapter 1 · 1989 to 1995","Adventure games","Always, but not always together. Each of us was off solving our own mysteries, and then comparing notes like detectives who had both been in the same mansion. Nobody ever knew what to do with the rubber chicken, but we were all very serious about it. Favorites: Matt says The Colonel's Bequest. Tony says Torin's Passage."],
  ["Chapter 2 · 1990","Final Fantasy","Many, many playthroughs of Final Fantasy 1, and this one was a team sport with jobs. Tony drove: he held the controller and made the decisions. Matt ran mapping and the guides, with graph paper, a pencil and a firm opinion about which door you missed. And for some reason there was always a Zack in the party too. Nobody remembers voting. We saved the world so many times it should be getting paid."],
  ["Chapter 3 · the 90s on","More RPGs","Once you finish one RPG, you need another. And another. Level grinding is a lot more fun with someone next to you saying just one more fight."],
  ["Chapter 4 · 1994 to 1998","Warcraft and StarCraft","Zug zug first, then build more pylons. Work work. Many an afternoon went to bases, armies and the sad feeling of a rush that arrived one minute too early."],
  ["Chapter 5 · December 1994 on","MegaZeux","Then came MegaZeux, a 1994 game maker built out of text characters, and we stopped just playing games and started making them. Tony was really, really good at the art. He took a handful of tiny characters and turned them into heroes, monsters, castles and whole worlds, way more than they had any right to be. He drew all the custom stuff: the character sets, the colors, every tile and creature. Matt programmed, and he was very good at it too, with robots that ran the enemies, shops and cutscenes. We built all kinds of games. Every one of them is now lost on an old hard drive in a drawer, a landfill or a lake. We did not know those files would matter. Nobody warns you."],
  ["Chapter 6 · 1999 on, probably","Star Wars: Rise in Power","Text only. No graphics. Somehow the best graphics anyway. We played a few Star Wars MUDs, but the one we played most, together, was Star Wars: Rise in Power (SWRiP). Matt and Tony ran engineering empires and controlled the game economies. Prices were set. Markets were cornered. Nobody is saying it was a monopoly, but nobody is saying it wasn't. The Empire had the Death Star. We had the supply chain."],
  ["Chapter 7 · 2000","Diablo II","Hours and hours and hours of Diablo II. We stayed a while, and listened, and then stayed a lot longer. There was no cow level, of course. There was absolutely not a secret cow level. We went there constantly. And if an item happened to appear twice in the stash, that was just the game being generous, and we were simply being polite by accepting both. Duping was a bug, and we exploited it with great respect and zero remorse."],
  ["Chapter 8 · now","Finnish Cottage Simulator","The most recent save file. Matt is hoarding everything in the cottage, no matter how worthless, and has opinions about shelves. Tony pushed the wrong button on a permadeath run and violently killed the one NPC the whole game needed. There is no reload. There is no undo. There is only the cottage, a lot of worthless stuff, and a very quiet Tony."],
  ["Bonus level · since the 90s","The movie studio","Since the 90s, when we were little kids, we have been making short, goofy films with whatever camera was around. Budget: snacks. Special effects: whatever was in the house. Stars: us."]];
 function about(){var items=ITEMS.length,tl=typeof TL!=="undefined"?TL.length:0;
  app.innerHTML='<section class="ab"><h2>About</h2><div class="k-intro">'+mascot(96,"happy",undefined,true)+'<div><p class="ab-lead"><b>Conventional Memory</b> is where Matt chronicles his love of vintage technology: the collection, the obsession, and the repairs.</p><p>He fixes broken computers, preserves their history, and builds a collection of it, one beige box at a time. He roped his brother Tony into this one too: Player 2 since the crib (and brother for life), maker of leather goods, costumes and film props, and a man with an unmatched talent for axing the one NPC the quest depended on. It is another adventure just like the countless others they have been on before.</p><p>Matt still loves technology today. But he misses a simpler time, when everything meant something:</p><blockquote class="ab-quote">You did not rent compute power, you built it. You did not rent games, you owned them. You collected, you built, you designed, you created, and you learned.</blockquote><p class="tn">The name is the first 640K of DOS memory, where every program had to squeeze in. This place is a tribute to that era.</p></div></div>'
  +'<h3 class="sub">Character select</h3><div class="ab-crew">'+CREW.map(function(c){return'<article class="ab-card" data-k="'+E(c.k)+'"><p class="ab-tag">'+E(c.tag)+'</p><div class="ab-pt"><img class="'+(c.pix?"pix":"smooth")+'" src="'+E(c.img)+'" width="'+c.w+'" height="'+c.h+'" alt="'+E(c.alt)+'"></div><p class="ab-art">'+E(c.art)+'</p><h3>'+E(c.n)+'</h3><p class="ab-role">'+E(c.role)+'</p><p>'+E(c.bio)+'</p><dl class="ab-st">'+c.stats.map(function(s){return'<dt>'+E(s[0])+'</dt><dd>'+E(s[1])+'</dd>'}).join("")+'</dl><p class="ab-q" role="status" aria-live="polite"></p><button class="btn" type="button" data-talk="'+E(c.k)+'">Press START to talk</button></article>'}).join("")+'</div>'
  +'<h3 class="sub">The workstation</h3><p class="tn">This is where Conventional Memory happens. Click on things. Everything is clickable, and the room will tell you what you see.</p><div class="ab-room"><div class="ab-rp"><img src="portraits/workstation.png" width="1024" height="768" alt="Pixel-art illustration of the Conventional Memory workstation: a blue CRT monitor between two Roland speakers, a beige keyboard, a lava lamp, a Doritos bag, a can of Surge, posters of Duke and Star Wars, and a beige wall phone">'+ROOM.map(function(r,i){return'<button type="button" class="ab-hot" data-room="'+i+'" aria-label="Look at '+E(r[0])+'" style="left:'+r[1]+'%;top:'+r[2]+'%;width:'+r[3]+'%;height:'+r[4]+'%"></button>'}).join("")+'</div><p class="ab-say" id="abs" role="status" aria-live="polite"><span>&gt; LOOK</span> You are at a workstation. There is a lot of stuff. Everything is slightly purple.</p></div>'
  +'<h3 class="sub">The save file</h3><p class="ab-save">SAVE FILE FOUND: <b>BROTHERS.SAV</b> &nbsp; PLAYERS: 2 &nbsp; PLAYTIME: <b>SINCE FOREVER</b></p><p>Matt and Tony have played games together their whole lives. Here are the chapters so far, in the order the games came out.</p><ol class="ab-log">'+LOG.map(function(l){return'<li><span class="ab-ch">'+E(l[0])+'</span><h4>'+E(l[1])+'</h4><p>'+E(l[2])+'</p></li>'}).join("")+'</ol>'
  +'<dl class="ab-st ab-ach"><dt>Player 2 (my brother)</dt><dd>ALWAYS</dd><dt>Final Fantasy 1 clears</dt><dd>LOST COUNT</dd><dt>Zack</dt><dd>ALWAYS IN THE PARTY</dd><dt>MegaZeux games completed</dt><dd>MANY</dd><dt>Robots programmed (Matt)</dt><dd>MORE THAN WERE NEEDED</dd><dt>Custom characters drawn (Tony)</dt><dd>ALL OF THEM</dd><dt>MegaZeux games still on disk</dt><dd>0 (SEE: OLD HARD DRIVES)</dd><dt>Game economies controlled</dt><dd>MORE THAN ONE</dd><dt>Hours of Diablo II</dt><dd>HOURS AND HOURS</dd><dt>Items hoarded (Matt)</dt><dd>ALL OF THEM</dd><dt>Critical NPCs axed (Tony)</dt><dd>ALSO ALL OF THEM, EVEN ON PERMADEATH</dd><dt>School locker black market (Tony)</dt><dd>CANDY, YO-YOS, BEEF JERKY, REPEAT CUSTOMERS</dd><dt>Trades learned (Tony)</dt><dd>ONE AT A TIME, ALL THE WAY TO MAX</dd><dt>Movie studios supplied (Tony)</dt><dd>4 AND COUNTING</dd><dt>Kids soldering (Tony)</dt><dd>3</dd><dt>Films made</dt><dd>MANY, ALL GOOFY</dd><dt>Players still on the same team</dt><dd>2</dd></dl>'
  +'<p class="tn">Dig deeper on the timeline: <a href="#/timeline/1991/ZZT">ZZT</a>, <a href="#/timeline/1994/MegaZeux">MegaZeux</a>, <a href="#/timeline/1996/SMAUG">SMAUG</a>, <a href="#/timeline/1997/'+encodeURIComponent("Star Wars Reality (SWR) 1.0")+'">Star Wars Reality</a> and <a href="#/timeline/1999/'+encodeURIComponent("Star Wars: Rise in Power")+'">Star Wars: Rise in Power</a>. If you still have a MegaZeux world from the 90s, the museum would very much like to see it.</p>'
  +'<p>Which brings us back to the beige boxes. These games came on these machines, and the machines are getting harder to find. Matt fixes them, Tony gets roped in, and every box in the catalog is somebody else\'s Saturday afternoon too.</p>'
  +'<h3 class="sub">Meet Connie</h3><div class="k-intro">'+mascot(96,"wink",undefined,false)+'<div><p>Connie is the museum\'s memory chip, born in 1981 on the first IBM PC with a 640K ceiling and a lot of family to fit under it. Her sister Emma 386 Ventional, her little brother Hiram &ldquo;Himmy&rdquo; Ventional and the rest of the family took years to arrive and tidy things up. She has her own <a href="#/connie">story</a>, a Sunday <a href="#/funnies">Funnies</a> page, a <a href="#/memman">Memory Manager</a> game, a <a href="#/closet">closet</a> of outfits (some only unlock by playing) and <a href="#/stickers">stickers</a> for your laptop.</p></div></div>'
  +'<h3 class="sub">Say hello</h3><p>Got a vintage machine, a repair story, a correction or a good joke? Matt and Tony read everything: <a href="mailto:'+EMAIL+'">'+EMAIL+'</a>. You can also write from the mailbox on the <a href="#/follow">Follow page</a>.</p>'
  +'<h3 class="sub">What is in here</h3><div class="pl-grid">'
  +'<a class="hm-tile" href="#/catalog"><i class="hm-ic">'+glyph("tower",28)+'</i><b>'+items+' exhibits</b><span>Each with a permanent label number and a QR code on the shelf.</span></a>'
  +'<a class="hm-tile" href="#/timeline"><i class="hm-ic">'+glyph("clock",28)+'</i><b>'+tl+' timeline entries</b><span>From the first microprocessors to today: hardware, games, and the news around them.</span></a>'
  +'<a class="hm-tile" href="#/hub/play"><i class="hm-ic">'+glyph("joystick",28)+'</i><b>Games and puzzles</b><span>Daily questions, Higher or Lower, a trivia maze, and a prize counter.</span></a>'
  +'<a class="hm-tile" href="#/start"><i class="hm-ic">'+glyph("flag",28)+'</i><b>New here?</b><span>Seven ways in, depending on your mood.</span></a></div>'
  +'<h3 class="sub">Good to know</h3><ul><li>Your lists, scores and prizes stay in your browser. Nothing is sent anywhere. <a href="#/backup">Back them up</a> if they matter to you.</li><li>Type <b>help</b> at the C:\\&gt; prompt in the footer. There are secrets. The Konami code is only the first one.</li><li>New things show up on <a href="#/follow">TikTok, YouTube, Instagram and Facebook</a> first, and here once they have a proper page.</li><li>Found a mistake, or have something the museum should hunt for? <a href="#/community">Tell us</a>.</li><li>The crew portraits were redrawn from real photos in two old-school adventure-game styles, and the workstation picture is in the same spirit. The ads, logos and illustrations are all drawn in code.</li></ul>'
  +'<pre class="ab-dos" aria-label="README.TXT">C:\\&gt;TYPE README.TXT\n\nConventional Memory LLC\nOne museum. Two brothers. 640K of conventional memory.\nThree heirs, interest pending.\n\nPress any key to continue . . .</pre></section>';
  if(typeof mascotGreet==="function")mascotGreet(app);
  $$("[data-room]").forEach(function(b){b.onclick=function(){var r=ROOM[+b.dataset.room],o=$("#abs");if(!r||!o)return;o.innerHTML="";var sp=document.createElement("span");sp.textContent="> LOOK AT "+r[0].toUpperCase();o.appendChild(sp);o.appendChild(document.createTextNode(" "+r[5]))}});
  var seen={};$$("[data-talk]").forEach(function(b){b.onclick=function(){var c=CREW.filter(function(x){return x.k===b.dataset.talk})[0],i=(seen[c.k]=((seen[c.k]==null?-1:seen[c.k])+1)%c.quips.length);var q=b.parentNode.querySelector(".ab-q");q.textContent="\u201c"+c.quips[i]+"\u201d";b.textContent="Again";b.parentNode.classList.remove("talk");void b.parentNode.offsetWidth;b.parentNode.classList.add("talk")}})}
 function start(){app.innerHTML='<section class="st"><h2>Start here</h2><div class="k-intro">'+mascot(96,"happy",undefined,true)+'<div><p>Hi, I am Connie Ventional, but Connie is fine. Conventional Memory chronicles Matt\'s collection of vintage computers: the repairs, the restorations, the history, and the games and ads that went with them. There is no wrong way in. Pick how you feel:</p></div></div>'
   +'<div class="pl-grid"><a class="hm-tile" href="#/catalog"><i class="hm-ic">'+glyph("tower",28)+'</i><b>I like looking at stuff</b><span>Browse the exhibits: departments, a mail-order catalog and a shelf.</span></a>'
   +'<a class="hm-tile" href="#/walk/1995"><i class="hm-ic">'+glyph("clock",28)+'</i><b>I want to remember</b><span>Walk through a year: the news, the hardware, the games, the ad.</span></a>'
   +'<a class="hm-tile" href="#/daily"><i class="hm-ic">'+glyph("bulb",28)+'</i><b>I want a challenge</b><span>Three timeline questions a day, then the rest of the games.</span></a>'
   +'<a class="hm-tile" href="#/runs"><i class="hm-ic">'+glyph("chip",28)+'</i><b>I tinker</b><span>Does it run? Dream rigs, IRQ conflicts and benchmarks.</span></a>'
   +'<a class="hm-tile" href="#/wish"><i class="hm-ic">'+glyph("heart",28)+'</i><b>I am shopping</b><span>A wish list you can circle things for and share.</span></a>'
   +'<a class="hm-tile" href="#/theater"><i class="hm-ic">'+glyph("tv",28)+'</i><b>I just want to watch</b><span>The little CRT theater and the jukebox.</span></a>'
   +'<a class="hm-tile" href="#/connie"><i class="hm-ic">'+glyph("heart",28)+'</i><b>I want to meet the family</b><span>Connie Ventional, her story, a Sunday funnies page and a game.</span></a></div>'
   +'<h3 class="sub">Good to know</h3><ul><li>Press <b>/</b> anywhere to search. Type <b>help</b> at the C:\\&gt; prompt in the footer for commands.</li><li>The menu bar groups everything: Catalog, Timeline, Explore, Play, Theater, My stuff, Community.</li><li>Your lists, scores and prizes stay in this browser. <a href="#/backup">Back them up</a> if you care about them.</li><li>Themes, motion and the CRT effect are the three buttons at the top right.</li></ul></section>'}

 return{mount:function(el,page,args){app=el;try{if(page==="start")setTimeout(function(){if(typeof mascotGreet==="function")mascotGreet(app)},0);
   if(page==="wish")wish(args[0]);else if(page==="kiosk")kiosk(args[0]==="go");else if(page==="prizes")prizes();else if(page==="backup")backup();else if(page==="maker")maker(args[0]);else if(page==="manuals")manuals();else if(page==="labels")labels(args[0]);else if(page==="scan")scan();else if(page==="about")about();else if(page==="start")start()
  }catch(e){app.innerHTML='<section><h2>Something broke</h2><p class="empty">This page could not load ('+E(e.message)+').</p></section>'}},unmount:function(){kStop();if(window.CMLabelUI)CMLabelUI.unmount()}}})();
