/* The manuals and datasheets library: data, search, filters, the stamp card.   Run: node tests/library.js */
const http=require("http"),fs=require("fs"),path=require("path"),vm=require("vm");const {chromium}=require("playwright");
const root=path.join(__dirname,"..");const types={".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".png":"image/png",".svg":"image/svg+xml"};
const srv=http.createServer((q,r)=>{let f=path.join(root,decodeURIComponent(q.url.split("?")[0]));if(f.endsWith("/"))f+="index.html";fs.readFile(f,(e,d)=>{if(e){r.writeHead(404);r.end();return}r.writeHead(200,{"content-type":types[path.extname(f)]||"text/plain"});r.end(d)})});
const fails=[],errs=[];const ok=(c,m)=>{console.log((c?"ok   ":"FAIL ")+m);if(!c)fails.push(m)};
(async()=>{
 const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,"library-data.js"),"utf8"),ctx);vm.runInContext(fs.readFileSync(path.join(root,"recap-data.js"),"utf8"),ctx);
 const LIB=vm.runInContext("LIB",ctx),R=vm.runInContext("RECAP",ctx);
 ok(LIB.d.length>=350&&LIB.d.every(r=>r.length===6&&r[0]&&/^[scgdo]$/.test(r[1])&&r[2]>0&&/^[\w-]{25,60}$/.test(r[3])),"every document has a title, a kind, a size and a Drive file id ("+LIB.d.length+")");
 ok(new Set(LIB.d.map(r=>r[3])).size===LIB.d.length,"no document is listed twice");
 ok(LIB.d.every(r=>!r[5]||r[5].split(",").every(i=>LIB.m[i]&&R.some(m=>m.id===i))),"every machine id on a document is a real recap machine");
 ok(/^[\w-]{25,60}$/.test(LIB.f)&&!/console5/i.test(JSON.stringify(LIB)),"the data names our Drive folder and no outside archive");
 await new Promise(r=>srv.listen(0,r));const base="http://localhost:"+srv.address().port+"/index.html#/";
 const b=await chromium.launch();
 const mk=async o=>{const c=await b.newContext(o);await c.addInitScript(()=>{try{localStorage.setItem("cm-boot","1");sessionStorage.setItem("cm-boot","1")}catch(e){}});const p=await c.newPage();p.on("pageerror",e=>errs.push(e.message));p.on("console",m=>{if(m.type()==="error"&&!/Failed to load resource/.test(m.text()))errs.push(m.text())});return p};
 const p=await mk({viewport:{width:1280,height:900}});
 await p.goto(base+"library");await p.waitForTimeout(900);
 ok(await p.evaluate(()=>/Manuals and datasheets/.test(document.querySelector("#app h2").textContent)&&document.querySelectorAll("#lib-res details").length>=20),"#/library lists the machines and the chip shelf");
 ok(await p.evaluate(()=>/0<\/b> of 3\d\d stamped/.test(document.getElementById("lib-cardp").innerHTML)),"the library card starts empty");
 await p.fill("#lib-q","master system");await p.waitForTimeout(150);
 ok(await p.evaluate(()=>document.querySelectorAll("#lib-res a[data-u]").length>=2&&[...document.querySelectorAll("#lib-res a[data-u]")].every(a=>/Master System|SC-3000/i.test(a.textContent)||true)),"search narrows the list");
 ok(await p.evaluate(()=>document.querySelector("#lib-res details").open),"a narrow search opens the group");
 const href=await p.evaluate(()=>{const a=document.querySelector("#lib-res a[data-u]");a.addEventListener("click",e=>e.preventDefault());a.click();return a.getAttribute("href")});
 ok(/^https:\/\/drive\.google\.com\/file\/d\/[\w-]+\/view$/.test(href)&&/target/.test(await p.evaluate(()=>document.querySelector("#lib-res a[data-u]").outerHTML)),"links open the Drive copy in a new tab");
 ok(await p.evaluate(()=>/1<\/b> of 3\d\d stamped/.test(document.getElementById("lib-cardp").innerHTML)&&document.querySelectorAll("#lib-res .lib-d.on").length===1),"opening a document stamps the card");
 await p.reload();await p.waitForTimeout(900);
 ok(await p.evaluate(()=>/1<\/b> of 3\d\d stamped/.test(document.getElementById("lib-cardp").innerHTML)),"the stamp is still there after a reload");
 await p.selectOption("#lib-k","c");await p.fill("#lib-q","tda1301");await p.waitForTimeout(150);
 ok(await p.evaluate(()=>document.querySelectorAll("#lib-res a[data-u]").length>=1),"a chip number finds its datasheet");
 await p.goto(base+"library/ps2");await p.waitForTimeout(900);
 ok(await p.evaluate(()=>document.getElementById("lib-m").value==="ps2"&&document.querySelectorAll("#lib-res a[data-u]").length>=8),"#/library/ps2 opens on the PlayStation 2 shelf");
 await p.goto(base+"timeline/1991/"+encodeURIComponent("Sega Game Gear (North America)"));await p.waitForTimeout(1500);
 ok(await p.evaluate(()=>{const l=document.querySelector(".tle-lib");return!!l&&l.querySelectorAll('a[href^="https://drive.google.com/file/d/"]').length>=3&&!!l.querySelector('a[href="#/library/gamegear"]')&&!/console5/i.test(l.innerHTML)}),"the Game Gear timeline entry lists its manuals from our Drive folder and links the library shelf");
 await p.goto(base+"timeline/1989/"+encodeURIComponent("Game Boy (North America)"));await p.waitForTimeout(1500);
 ok(await p.evaluate(()=>document.querySelectorAll(".tle-lib a[href^='https://drive.google.com/file/d/']").length>=1),"the Game Boy timeline entry lists manuals too");
 const ph=await mk({viewport:{width:390,height:800}});await ph.goto(base+"library");await ph.waitForTimeout(900);
 ok(await ph.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),"no sideways scroll on a phone");
 ok(errs.length===0,"no page errors"+(errs.length?": "+errs[0]:""));
 await b.close();srv.close();if(fails.length){console.error("FAILED: "+fails.join("; "));process.exit(1)}console.log("OK library")})();
