// Keeps youtube-data.js in step with the Conventional Memory YouTube channel, newest first.
// Runs from .github/workflows/youtube.yml every few hours, so the Retro Theater needs no manual updates.
// It finds the channel from its @handle, reads the channel's public RSS feed (the 15 newest uploads) and merges them into the
// existing list, so older videos stay even after they fall out of the feed. Nothing is written when nothing changed.
// Test hook: YT_FEED_FILE=path/to/feed.xml (and YT_CHANNEL_ID) skips the network.
var fs=require("fs"),path=require("path");
var FILE=path.join(__dirname,"..","youtube-data.js"),HANDLE=process.env.YT_HANDLE||"ConventionalMemory",MAX=80;
function dec(s){return String(s).replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'")}
function readOld(){try{var t=fs.readFileSync(FILE,"utf8"),v=t.match(/^var YT_VIDEOS=(\[[\s\S]*?\]);\s*$/m),c=t.match(/^var YT_CHANNEL=(\{.*\});\s*$/m);return{videos:v?JSON.parse(v[1]):[],channel:c?JSON.parse(c[1]):{}}}catch(e){return{videos:[],channel:{}}}}
function parseFeed(xml){var out=[],re=/<entry>([\s\S]*?)<\/entry>/g,m;
 while((m=re.exec(xml))){var e=m[1],id=(e.match(/<yt:videoId>([\w-]{11})<\/yt:videoId>/)||[])[1],t=(e.match(/<title>([\s\S]*?)<\/title>/)||[])[1],d=(e.match(/<published>([^<]+)<\/published>/)||[])[1];
  if(id&&t&&d)out.push({id:id,t:dec(t).trim().slice(0,160),d:d.slice(0,10)})}
 return out}
async function get(u){var r=await fetch(u,{headers:{"user-agent":"Mozilla/5.0 (compatible; ConventionalMemoryBot/1.0)","accept-language":"en-US,en;q=0.9"}});if(!r.ok)throw new Error(u+" -> "+r.status);return r.text()}
async function channelId(){if(process.env.YT_CHANNEL_ID)return process.env.YT_CHANNEL_ID;
 var h=await get("https://www.youtube.com/@"+HANDLE),m=h.match(/"channelId":"(UC[\w-]{22})"/)||h.match(/youtube\.com\/channel\/(UC[\w-]{22})/)||h.match(/"externalId":"(UC[\w-]{22})"/);
 if(!m)throw new Error("could not find the channel id for @"+HANDLE);return m[1]}
async function main(){var old=readOld(),id=old.channel.id||"",xml;
 if(process.env.YT_FEED_FILE){xml=fs.readFileSync(process.env.YT_FEED_FILE,"utf8");id=id||process.env.YT_CHANNEL_ID||""}
 else{try{if(!id)id=await channelId();xml=await get("https://www.youtube.com/feeds/videos.xml?channel_id="+id)}catch(e){console.error("YouTube not reachable ("+e.message+"); leaving youtube-data.js as it is.");return}}
 var fresh=parseFeed(xml);if(!fresh.length){console.error("The feed had no videos; leaving youtube-data.js as it is.");return}
 var by={};old.videos.concat(fresh).forEach(function(v){by[v.id]=v});
 var list=Object.keys(by).map(function(k){return by[k]}).sort(function(a,b){return a.d<b.d?1:a.d>b.d?-1:0}).slice(0,MAX);
 var body="// Generated by tools/build-youtube.js (see .github/workflows/youtube.yml). Do not edit by hand: it is rewritten every few hours.\n// Newest video first. id, title, date published.\nvar YT_CHANNEL="+JSON.stringify({handle:HANDLE,id:id})+";\nvar YT_VIDEOS="+JSON.stringify(list)+";\n";
 var cur="";try{cur=fs.readFileSync(FILE,"utf8")}catch(e){}
 if(cur!==body){fs.writeFileSync(FILE,body);console.log("youtube-data.js updated: "+list.length+" videos, newest "+(list[0]||{}).d)}else console.log("youtube-data.js already up to date")}
if(require.main===module)main().catch(function(e){console.error(e);process.exit(1)});
module.exports={parseFeed:parseFeed};
